/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const AlignLeft = /* @__PURE__ */ createIcon("AlignLeft", {
	linear: [
		["path", { d: "M3 6H21", stroke: "currentColor" }],
		["path", { d: "M3 12H12", stroke: "currentColor" }],
		["path", { d: "M3 18H21", stroke: "currentColor" }],
	],
});
