/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const AlignRight = createIcon("AlignRight", {
	linear: [
		["path", { d: "M3 6H21", stroke: "currentColor" }],
		["path", { d: "M12 12H21", stroke: "currentColor" }],
		["path", { d: "M3 18H21", stroke: "currentColor" }],
	],
});
