/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const AlignRight = createIcon("AlignRight", {
	linear: [
		["path", { d: "M3.75 4.75H20.25", stroke: "currentColor" }],
		["path", { d: "M11.75 12H20.25", stroke: "currentColor" }],
		["path", { d: "M3.75 19.25H20.25", stroke: "currentColor" }],
	],
});
