/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const AlignLeft = createIcon("AlignLeft", {
	linear: [
		["path", { d: "M3.75 4.75H20.25", stroke: "currentColor" }],
		["path", { d: "M3.75 12H12.25", stroke: "currentColor" }],
		["path", { d: "M3.75 19.25H20.25", stroke: "currentColor" }],
	],
});
