/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const AlignCenter = createIcon("AlignCenter", {
	linear: [
		["path", { d: "M3 6H21", stroke: "currentColor" }],
		["path", { d: "M7.5 12H16.5", stroke: "currentColor" }],
		["path", { d: "M3 18H21", stroke: "currentColor" }],
	],
});
