/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Analytics = /* @__PURE__ */ createIcon("Analytics", {
	linear: [
		["path", { d: "M4 9V20", stroke: "currentColor" }],
		["path", { d: "M8 4V20", stroke: "currentColor" }],
		["path", { d: "M12 11V20", stroke: "currentColor" }],
		["path", { d: "M16 7V20", stroke: "currentColor" }],
		["path", { d: "M20 14V20", stroke: "currentColor" }],
	],
});
