/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.2 8.7V20.8", stroke: "currentColor" }],
	["path", { d: "M7.6 3.2V20.8", stroke: "currentColor" }],
	["path", { d: "M12 10.9V20.8", stroke: "currentColor" }],
	["path", { d: "M16.4 6.5V20.8", stroke: "currentColor" }],
	["path", { d: "M20.8 14.2V20.8", stroke: "currentColor" }],
];

export const Analytics = /* @__PURE__ */ createIcon("Analytics", {
	linear: nodes,
	bold: nodes,
});
