/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Anthropic = /* @__PURE__ */ createIcon("Anthropic", {
	bold: [
		["path", { transform: "translate(12 12) scale(0.96916459) translate(-11.99841934 -12)", d: "M17.0977 4H13.5611L19.8941 20H23.3484L17.0977 4ZM6.89916 4L0.648438 20H4.18503L5.58322 16.6359H12.1629L13.4789 19.9179H17.0155L10.6003 4H6.98141H6.89916ZM6.57018 13.6821L8.70858 8.02051L10.9292 13.6821H6.65242H6.57018Z", fill: "currentColor" }],
	],
});
