/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { "data-honeyicons-bounds": "", d: "M20.5324 21.2328C21.7048 22.1122 23.4635 21.526 21.8514 19.9138C17.015 15.224 18.0409 2.32715 12.0321 2.32715C6.02333 2.32715 7.04921 15.224 2.21288 19.9138C0.45421 21.6725 2.35942 22.1122 3.53188 21.2328C8.07512 18.1552 7.782 12.7326 12.0321 12.7326C16.2822 12.7326 15.9891 18.1552 20.5324 21.2328Z", fill: "#3186FF" }],
	["g", { mask: "url(#antigravity-color-mask)" }, [
		["path", { d: "M0.609 -2.041C0.252 1.101 2.959 3.988 6.655 4.408C10.352 4.828 13.638 2.62 13.994 -0.521C14.351 -3.662 11.644 -6.55 7.948 -6.97C4.251 -7.389 0.965 -5.182 0.609 -2.041Z", fill: "#FFE432", filter: "url(#antigravity-color-0)" }],
		["path", { d: "M14.86 8.231C15.786 12.218 19.84 14.683 23.915 13.737C27.99 12.791 30.543 8.791 29.616 4.803C28.691 0.817 24.637 -1.649 20.562 -0.702C16.487 0.245 13.934 4.244 14.86 8.232Z", fill: "#FC413D", filter: "url(#antigravity-color-1)" }],
		["path", { d: "M-9.388 10.906C-8.217 15.021 -2.948 17.127 2.384 15.612C7.714 14.095 11.087 9.53 9.917 5.416C8.747 1.301 3.477 -0.805 -1.854 0.71C-7.185 2.226 -10.558 6.79 -9.388 10.906Z", fill: "#00B95C", filter: "url(#antigravity-color-2)" }],
		["path", { d: "M-9.388 10.906C-8.217 15.021 -2.948 17.127 2.384 15.612C7.714 14.095 11.087 9.53 9.917 5.416C8.747 1.301 3.477 -0.805 -1.854 0.71C-7.185 2.226 -10.558 6.79 -9.388 10.906Z", fill: "#00B95C", filter: "url(#antigravity-color-3)" }],
		["path", { d: "M-5.157 14.317C-2.224 17.313 2.828 17.124 6.127 13.895C9.426 10.666 9.721 5.618 6.788 2.622C3.854 -0.374 -1.198 -0.185 -4.497 3.045C-7.795 6.273 -8.091 11.321 -5.157 14.317Z", fill: "#00B95C", filter: "url(#antigravity-color-4)" }],
		["path", { d: "M10.19 25.617C11.1 29.539 14.901 32.007 18.678 31.13C22.455 30.253 24.778 26.363 23.867 22.441C22.957 18.518 19.156 16.05 15.379 16.928C11.603 17.804 9.28 21.695 10.19 25.616Z", fill: "#3186FF", filter: "url(#antigravity-color-5)" }],
		["path", { d: "M3.75 -5.71C1.843 -1.461 3.931 3.615 8.412 5.627C12.894 7.639 18.074 5.825 19.982 1.576C21.889 -2.673 19.802 -7.749 15.321 -9.76C10.839 -11.773 5.659 -9.959 3.751 -5.709Z", fill: "#FBBC04", filter: "url(#antigravity-color-6)" }],
		["path", { d: "M-1.359 35.303C-5.976 33.49 1.915 18.575 3.877 13.576C5.84 8.578 11.175 5.995 15.791 7.808C20.41 9.62 25.883 19.605 23.92 24.604C21.958 29.603 3.259 37.115 -1.359 35.303Z", fill: "#3186FF", filter: "url(#antigravity-color-7)" }],
		["path", { d: "M26.621 16.739C25.385 18.182 22.159 17.446 19.415 15.096C16.672 12.745 15.45 9.67 16.686 8.227C17.922 6.784 21.149 7.52 23.892 9.871C26.635 12.221 27.858 15.296 26.621 16.739Z", fill: "#749BFF", filter: "url(#antigravity-color-8)" }],
		["path", { d: "M17.393 9.395C22.476 12.833 28.332 13.061 30.471 9.9C32.608 6.739 30.219 1.388 25.135 -2.051C20.051 -5.491 14.195 -5.718 12.057 -2.556C9.919 0.604 12.308 5.955 17.393 9.395Z", fill: "#FC413D", filter: "url(#antigravity-color-9)" }],
		["path", { d: "M0.699 3.801C-0.561 6.84 -0.15 9.897 1.618 10.629C3.385 11.362 5.839 9.492 7.099 6.454C8.359 3.415 7.948 0.358 6.18 -0.375C4.413 -1.107 1.959 0.763 0.699 3.801Z", fill: "#FFEE48", filter: "url(#antigravity-color-10)" }],
	]],
	["defs", {}, [
		["mask", { id: "antigravity-color-mask", x: "1.5", y: "2.327", width: "21", height: "20.125", maskUnits: "userSpaceOnUse" }, [
			["path", { d: "M20.5324 21.2328C21.7048 22.1122 23.4635 21.526 21.8514 19.9138C17.015 15.224 18.0409 2.32715 12.0321 2.32715C6.02333 2.32715 7.04921 15.224 2.21288 19.9138C0.45421 21.6725 2.35942 22.1122 3.53188 21.2328C8.07512 18.1552 7.782 12.7326 12.0321 12.7326C16.2822 12.7326 15.9891 18.1552 20.5324 21.2328Z", fill: "#fff" }],
		]],
		["filter", { id: "antigravity-color-0", x: "-1.377", y: "-8.975", width: "17.358", height: "15.389", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "0.977" }],
		]],
		["filter", { id: "antigravity-color-1", x: "5.219", y: "-10.354", width: "34.038", height: "33.745", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "4.725" }],
		]],
		["filter", { id: "antigravity-color-2", x: "-17.653", y: "-7.816", width: "35.836", height: "31.953", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "4.017" }],
		]],
		["filter", { id: "antigravity-color-3", x: "-17.653", y: "-7.816", width: "35.836", height: "31.953", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "4.017" }],
		]],
		["filter", { id: "antigravity-color-4", x: "-15.212", y: "-7.541", width: "32.053", height: "32.021", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "4.017" }],
		]],
		["filter", { id: "antigravity-color-5", x: "2.358", y: "9.116", width: "29.342", height: "29.826", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "3.818" }],
		]],
		["filter", { id: "antigravity-color-6", x: "-3.875", y: "-17.5", width: "31.481", height: "30.867", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "3.46" }],
		]],
		["filter", { id: "antigravity-color-7", x: "-8.965", y: "1.05", width: "39.475", height: "40.708", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "3.09" }],
		]],
		["filter", { id: "antigravity-color-8", x: "10.674", y: "1.96", width: "21.957", height: "21.047", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "2.764" }],
		]],
		["filter", { id: "antigravity-color-9", x: "6.604", y: "-9.457", width: "29.32", height: "26.256", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "2.335" }],
		]],
		["filter", { id: "antigravity-color-10", x: "-5.811", y: "-6.314", width: "19.42", height: "22.882", filterUnits: "userSpaceOnUse", colorInterpolationFilters: "sRGB" }, [
			["feGaussianBlur", { stdDeviation: "2.89" }],
		]],
	]],
];

export const AntigravityColor = /* @__PURE__ */ createIcon("AntigravityColor", {
	linear: nodes,
	bold: nodes,
});
