/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const AppWindow = /* @__PURE__ */ createIcon("AppWindow", {
	linear: [
		["path", { d: "M10.9 2.1L13.1 2.1C17.2481 2.1 19.3227 2.1 20.6108 3.3892C21.9 4.6773 21.9 6.7519 21.9 10.9L21.9 13.1C21.9 17.2481 21.9 19.3227 20.6108 20.6108C19.3227 21.9 17.2481 21.9 13.1 21.9L10.9 21.9C6.7519 21.9 4.6773 21.9 3.3892 20.6108C2.1 19.3227 2.1 17.2481 2.1 13.1L2.1 10.9C2.1 6.7519 2.1 4.6773 3.3892 3.3892C4.6773 2.1 6.7519 2.1 10.9 2.1ZM2.265 8.26H21.735", stroke: "currentColor" }],
		["circle", { cx: "5.84", cy: "5.235", r: "0.99", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "8.81", cy: "5.235", r: "0.99", fill: "currentColor", stroke: "none" }],
	],
});
