/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Archive = /* @__PURE__ */ createIcon("Archive", {
	linear: [
		["path", { d: "M4.5 6.15H19.5C20.85 6.15 21.9 7.2 21.9 8.55L21.1 17.4C20.85 20.2 19.2 21.9 16.4 21.9H7.6C4.8 21.9 3.15 20.2 2.9 17.4L2.1 8.55C2.1 7.2 3.15 6.15 4.5 6.15ZM4.95 6.15V4.35C4.95 3.05 5.95 2.1 7.25 2.1H16.75C18.05 2.1 19.05 3.05 19.05 4.35V6.15M9 17.1H15", stroke: "currentColor" }],
	],
});
