/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowLeft = /* @__PURE__ */ createIcon("ArrowLeft", {
	linear: [
		["path", { d: "M4.85 12.0022H19.7M10.8999 18.6022C10.8999 18.6022 4.3 13.7413 4.3 12.0021C4.3 10.2629 10.9 5.4021 10.9 5.4021", stroke: "currentColor" }],
	],
});
