/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowUp = /* @__PURE__ */ createIcon("ArrowUp", {
	linear: [
		["path", { d: "M12 4.85V19.7M18.6 10.9C18.6 10.9 13.7392 4.3 12 4.3C10.2607 4.3 5.4 10.9 5.4 10.9", stroke: "currentColor" }],
	],
});
