/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M15.3 6.1154C15.3 6.1154 7.6678 5.5183 6.5931 6.5931C5.5183 7.6678 6.1154 15.3 6.1154 15.3M7.05 7.05L18.05 18.05", stroke: "currentColor" }],
];

export const ArrowUpLeft = /* @__PURE__ */ createIcon("ArrowUpLeft", {
	linear: nodes,
	bold: nodes,
});
