/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ArrowRight02 = createIcon("ArrowRight02", {
	linear: [
		["path", { d: "M18.5 12L4.99997 12", stroke: "currentColor" }],
		["path", { d: "M13 18C13 18 19 13.5811 19 12C19 10.4188 13 6 13 6", stroke: "currentColor" }],
	],
});
