/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowUp = /* @__PURE__ */ createIcon("ArrowUp", {
	linear: [
		["path", { d: "M12 5.5V19", stroke: "currentColor" }],
		["path", { d: "M18 11C18 11 13.5811 5.00001 12 5C10.4188 4.99999 6 11 6 11", stroke: "currentColor" }],
	],
});
