/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M12 19.1522V4.3021M18.6 13.1022C18.6 13.1022 13.7392 19.7021 12 19.7022C10.2607 19.7022 5.4 13.1022 5.4 13.1022", stroke: "currentColor" }],
];

export const ArrowDown = /* @__PURE__ */ createIcon("ArrowDown", {
	linear: nodes,
	bold: nodes,
});
