/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowDownRight = /* @__PURE__ */ createIcon("ArrowDownRight", {
	linear: [
		["path", { d: "M8.7 17.8847C8.7 17.8847 16.3321 18.4816 17.4069 17.4069C18.4816 16.3321 17.8846 8.7 17.8846 8.7M16.95 16.95L5.95 5.95", stroke: "currentColor" }],
	],
});
