/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowDownLeft = /* @__PURE__ */ createIcon("ArrowDownLeft", {
	linear: [
		["path", { d: "M15.3 17.8847C15.3 17.8847 7.6678 18.4816 6.5931 17.4069C5.5183 16.3321 6.1154 8.7 6.1154 8.7M7.05 16.95L18.05 5.95", stroke: "currentColor" }],
	],
});
