/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M19.15 12L4.3 12M13.1 18.6C13.1 18.6 19.7 13.7392 19.7 12C19.7 10.2607 13.1 5.4 13.1 5.4", stroke: "currentColor" }],
];

export const ArrowRight = /* @__PURE__ */ createIcon("ArrowRight", {
	linear: nodes,
	bold: nodes,
});
