/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ArrowDown = /* @__PURE__ */ createIcon("ArrowDown", {
	linear: [
		["path", { d: "M12 18.502V5.00195 M18 13.002C18 13.002 13.5811 19.0019 12 19.002C10.4188 19.002 6 13.002 6 13.002", stroke: "currentColor" }],
	],
});
