/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ArrowUpLeft = createIcon("ArrowUpLeft", {
	linear: [
		["path", { d: "M15 6.65032C15 6.65032 8.06166 6.10759 7.08461 7.08463C6.10755 8.06167 6.65037 15 6.65037 15M7.5 7.5L17.5 17.5", stroke: "currentColor" }],
	],
});
