/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M8.7 6.1154C8.7 6.1154 16.3321 5.5183 17.4069 6.5931C18.4816 7.6678 17.8846 15.3 17.8846 15.3M16.95 7.05L5.95 18.05", stroke: "currentColor" }],
];

export const ArrowUpRight = /* @__PURE__ */ createIcon("ArrowUpRight", {
	linear: nodes,
	bold: nodes,
});
