/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Atom = /* @__PURE__ */ createIcon("Atom", {
	linear: [
		["path", { d: "M5.07 5.07C3.625 6.515 5.557 10.789 9.384 14.616C13.211 18.443 17.485 20.375 18.93 18.93C20.375 17.485 18.443 13.211 14.616 9.384C10.789 5.557 6.515 3.625 5.07 5.07Z M5.07 18.93C6.515 20.375 10.789 18.443 14.616 14.616C18.443 10.789 20.375 6.515 18.93 5.07C17.485 3.625 13.211 5.557 9.384 9.384C5.557 13.211 3.625 17.485 5.07 18.93Z", stroke: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "1.6", fill: "currentColor", stroke: "none" }],
	],
});
