/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4.377 4.377C2.7875 5.9665 4.9127 10.6679 9.1224 14.8776C13.3321 19.0873 18.0335 21.2125 19.623 19.623C21.2125 18.0335 19.0873 13.3321 14.8776 9.1224C10.6679 4.9127 5.9665 2.7875 4.377 4.377ZM4.377 19.623C5.9665 21.2125 10.6679 19.0873 14.8776 14.8776C19.0873 10.6679 21.2125 5.9665 19.623 4.377C18.0335 2.7875 13.3321 4.9127 9.1224 9.1224C4.9127 13.3321 2.7875 18.0335 4.377 19.623Z", stroke: "currentColor" }],
	["circle", { cx: "12", cy: "12", r: "1.76", fill: "currentColor", stroke: "none" }],
];

export const Atom = /* @__PURE__ */ createIcon("Atom", {
	linear: nodes,
	bold: nodes,
});
