/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Award = /* @__PURE__ */ createIcon("Award", {
	linear: [
		["path", { d: "M6.5 9A5.5 5.5 0 1 0 17.5 9A5.5 5.5 0 1 0 6.5 9Z M8.6 13.4L7.761 19.611C7.664 20.324 8.029 20.585 8.673 20.263L10.927 19.137C11.571 18.815 12.429 18.815 13.073 19.137L15.327 20.263C15.971 20.585 16.336 20.324 16.239 19.611L15.4 13.4", stroke: "currentColor" }],
	],
});
