/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Ban = /* @__PURE__ */ createIcon("Ban", {
	linear: [
		["path", { d: "M3 12A9 9 0 1 0 21 12A9 9 0 1 0 3 12Z M5.636 5.636L18.364 18.364", stroke: "currentColor" }],
	],
});
