/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Ban = /* @__PURE__ */ createIcon("Ban", {
	linear: [
		["path", { d: "M2.1 12A9.9 9.9 0 1 0 21.9 12A9.9 9.9 0 1 0 2.1 12ZM4.9996 4.9996L19.0004 19.0004", stroke: "currentColor" }],
	],
	bold: [
		["path", { d: "M12 22.8C6.035 22.8 1.2 17.965 1.2 12C1.2 6.035 6.035 1.2 12 1.2C17.965 1.2 22.8 6.035 22.8 12C22.8 17.965 17.965 22.8 12 22.8ZM18.969 17.696L6.304 5.031C5.839 5.412 5.412 5.839 5.031 6.304L17.696 18.969C18.161 18.588 18.588 18.161 18.969 17.696Z", fill: "currentColor" }],
	],
});
