/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Bank = /* @__PURE__ */ createIcon("Bank", {
	linear: [
		["path", { d: "M2.65 8.095C2.65 7.38 3.035 6.83 3.805 6.39L10.075 2.705C10.9 2.232 11.395 2.1 12 2.1C12.605 2.1 13.1 2.232 13.925 2.705L20.195 6.39C20.965 6.83 21.35 7.38 21.35 8.095C21.35 9.14 20.855 9.58 19.81 9.58H4.19C3.145 9.58 2.65 9.14 2.65 8.095ZM5.4 12.99V17.94M9.8 12.99V17.94M14.2 12.99V17.94M18.6 12.99V17.94M2.65 21.35H21.35", stroke: "currentColor" }],
	],
});
