/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Barcode = /* @__PURE__ */ createIcon("Barcode", {
	linear: [
		["path", { d: "M3.9 5.5V18.5 M6.9 5.5V18.5 M9.9 5.5V18.5 M10.8 5.5V18.5 M13.8 5.5V18.5 M16.8 5.5V18.5 M17.7 5.5V18.5 M20.1 5.5V18.5", stroke: "currentColor" }],
	],
});
