/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 4.85V19.15M6.555 4.85V19.15M7.545 4.85V19.15M12 4.85V19.15M16.455 4.85V19.15M17.445 4.85V19.15M21.9 4.85V19.15", stroke: "currentColor" }],
];

export const Barcode = /* @__PURE__ */ createIcon("Barcode", {
	linear: nodes,
	bold: nodes,
});
