/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Bold = /* @__PURE__ */ createIcon("Bold", {
	linear: [
		["path", { d: "M13.1 3.2H9.8C7.7258 3.2 6.6887 3.2 6.0444 3.8444C5.4 4.4887 5.4 5.5258 5.4 7.6V12H13.1C15.53 12 17.5 10.03 17.5 7.6C17.5 5.1699 15.53 3.2 13.1 3.2ZM14.2 12H5.4V16.4C5.4 18.4742 5.4 19.5112 6.0444 20.1556C6.6887 20.8 7.7258 20.8 9.8 20.8H14.2C16.63 20.8 18.6 18.83 18.6 16.4C18.6 13.97 16.63 12 14.2 12Z", stroke: "currentColor" }],
	],
});
