/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Book = /* @__PURE__ */ createIcon("Book", {
	linear: [
		["path", { d: "M19 16V4.5C19 3.67 18.33 3 17.5 3H9C6.79 3 5 4.79 5 7V18.5 M19 16H7.5C6.12 16 5 17.12 5 18.5C5 19.88 6.12 21 7.5 21H17.5C18.33 21 19 20.33 19 19.5V16 M9 7.5H15", stroke: "currentColor" }],
	],
});
