/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Bookmarks = /* @__PURE__ */ createIcon("Bookmarks", {
	linear: [
		["path", { d: "M8 5.88L8 5.1A3.1 3.1 0 0 1 11.1 2L18.9 2A3.1 3.1 0 0 1 22 5.1L22 16.39A1.6 1.6 0 0 1 19.621 17.788L16 15.77M5.1 5.88L12.9 5.88A3.1 3.1 0 0 1 16 8.98L16 20.277A1.6 1.6 0 0 1 13.621 21.675L9.779 19.534A1.6 1.6 0 0 0 8.221 19.534L4.379 21.675A1.6 1.6 0 0 1 2 20.277L2 8.98A3.1 3.1 0 0 1 5.1 5.88Z", stroke: "currentColor" }],
	],
});
