/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Braces = /* @__PURE__ */ createIcon("Braces", {
	linear: [
		["path", { d: "M8.15 3.2C6.39 3.2 5.4 4.19 5.4 5.95V9.14C5.4 10.57 4.52 11.56 3.2 12C4.52 12.44 5.4 13.43 5.4 14.86V18.05C5.4 19.81 6.39 20.8 8.15 20.8M15.85 3.2C17.61 3.2 18.6 4.19 18.6 5.95L18.6 9.14C18.6 10.57 19.48 11.56 20.8 12C19.48 12.44 18.6 13.43 18.6 14.86L18.6 18.05C18.6 19.81 17.61 20.8 15.85 20.8", stroke: "currentColor" }],
	],
});
