/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Broadcast = /* @__PURE__ */ createIcon("Broadcast", {
	linear: [
		["circle", { cx: "12", cy: "12", r: "2", stroke: "currentColor" }],
		["path", { d: "M20 18C21.26 16.33 22 14.25 22 12C22 9.75 21.26 7.67 20 6", stroke: "currentColor" }],
		["path", { d: "M4 6C2.74 7.67 2 9.75 2 12C2 14.25 2.74 16.33 4 18", stroke: "currentColor" }],
		["path", { d: "M16.8 15.6C17.55 14.6 18 13.35 18 12C18 10.65 17.55 9.4 16.8 8.4", stroke: "currentColor" }],
		["path", { d: "M7.2 8.4C6.45 9.4 6 10.65 6 12C6 13.35 6.45 14.6 7.2 15.6", stroke: "currentColor" }],
	],
});

/** @deprecated Use Broadcast instead. */
export const Radar = Broadcast;
