/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Building = /* @__PURE__ */ createIcon("Building", {
	linear: [
		["path", { d: "M4.08 21.24V8.641C4.08 7.3435 4.08 6.6948 4.4185 6.1916C4.757 5.6883 5.3568 5.4453 6.5565 4.9593L9.5265 3.756C11.9918 2.7572 13.2244 2.2578 14.0972 2.8481C14.97 3.4384 14.97 4.7715 14.97 7.4377V21.24M14.97 8.535H15.96C17.8267 8.535 18.7601 8.535 19.3401 9.1149C19.92 9.6949 19.92 10.6283 19.92 12.495V21.24M2.1 21.405H21.9M8.04 8.535H11.01M8.04 12.495H11.01M8.04 16.455H11.01", stroke: "currentColor" }],
	],
});
