/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Calendar = /* @__PURE__ */ createIcon("Calendar", {
	linear: [
		["path", { d: "M10.3935 3.9675H13.6065C17.3764 3.9675 19.3042 3.9675 20.4716 5.1349C21.639 6.2916 21.639 8.2194 21.639 12V13.6065C21.639 17.3764 21.639 19.3042 20.4716 20.4716C19.3042 21.639 17.3764 21.639 13.6065 21.639H10.3935C6.6129 21.639 4.6851 21.639 3.5284 20.4716C2.361 19.3042 2.361 17.3764 2.361 13.6065V12C2.361 8.2194 2.361 6.2916 3.5284 5.1349C4.6851 3.9675 6.6129 3.9675 10.3935 3.9675ZM7.1805 2.0933V5.574M16.8195 2.0933V5.574M2.6288 9.3225H21.3713", stroke: "currentColor" }],
		["circle", { cx: "7.1805", cy: "13.6065", r: "1.071", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "7.1805", cy: "17.355", r: "1.071", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "12", cy: "13.6065", r: "1.071", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "12", cy: "17.355", r: "1.071", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "16.8195", cy: "13.6065", r: "1.071", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "16.8195", cy: "17.355", r: "1.071", fill: "currentColor", stroke: "none" }],
	],
});
