/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const CartBag = /* @__PURE__ */ createIcon("CartBag", {
	linear: [
		["path", { d: "M11.64 4.75H12.36C15.45 4.75 17 4.75 17.9 5.5C18.8 6.25 19.1 7.8 19.65 10.65C20.45 14.95 20.85 17.1 19.7 18.45C18.55 19.75 16.6 19.75 12.36 19.75H11.64C7.4 19.75 5.45 19.75 4.3 18.45C3.15 17.1 3.55 14.95 4.35 10.65C4.9 7.8 5.2 6.25 6.1 5.5C7 4.75 8.55 4.75 11.64 4.75Z", stroke: "currentColor" }],
		["path", { d: "M8.9 7.75C9.35 9.05 10.6 10 12 10C13.4 10 14.65 9.05 15.1 7.75", stroke: "currentColor" }],
	],
});
