/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.65 2.65V14.75C2.65 17.863 2.65 19.414 3.618 20.382C4.586 21.35 6.137 21.35 9.25 21.35H21.35M7.38 15.52L9.7307 12.8756C10.4325 12.0858 11.4324 12.0209 12.2299 12.7128L12.8701 13.2672C13.6676 13.9591 14.6752 13.9008 15.3891 13.1231L20.25 7.82", stroke: "currentColor" }],
];

export const ChartLine = /* @__PURE__ */ createIcon("ChartLine", {
	linear: nodes,
	bold: nodes,
});
