/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChartPie = /* @__PURE__ */ createIcon("ChartPie", {
	linear: [
		["path", { d: "M10.6 5.3A7.7 7.7 0 1 0 18.3 13H11.6C11.05 13 10.6 12.55 10.6 12Z M13.4 3.3A7.7 7.7 0 0 1 20.7 10.6H14.4C13.85 10.6 13.4 10.15 13.4 9.6Z", stroke: "currentColor" }],
	],
});
