/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChartAnalysis = /* @__PURE__ */ createIcon("ChartAnalysis", {
	linear: [
		["path", { d: "M2.1 10.9L4.85 8.15C5.9688 7.0312 6.5281 6.4719 7.201 6.3478C7.4648 6.2991 7.7352 6.2991 7.999 6.3478C8.6719 6.4719 9.2312 7.0312 10.35 8.15C11.4688 9.2688 12.0282 9.8282 12.7009 9.9522C12.9648 10.0009 13.2352 10.0009 13.4991 9.9522C14.1718 9.8282 14.7312 9.2688 15.85 8.15L21.9 2.1", stroke: "currentColor" }],
		["path", { d: "M2.1 15.3V21.9M8.7 13.1V21.9M15.3 16.4V21.9M21.9 8.7V21.9", stroke: "currentColor" }],
	],
});
