/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChartLine = /* @__PURE__ */ createIcon("ChartLine", {
	linear: [
		["path", { d: "M3.5 3.5V14.5C3.5 17.33 3.5 18.74 4.38 19.62C5.26 20.5 6.67 20.5 9.5 20.5H20.5 M7.8 15.2L9.937 12.796C10.575 12.078 11.484 12.019 12.209 12.648L12.791 13.152C13.516 13.781 14.432 13.728 15.081 13.021L19.5 8.2", stroke: "currentColor" }],
	],
});
