/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChartPie = /* @__PURE__ */ createIcon("ChartPie", {
	linear: [
		["path", { d: "M9.975 6.15A7.875 7.875 0 1 0 17.85 14.025H11.075C10.47 14.025 9.975 13.53 9.975 12.925ZM14.025 2.1A7.875 7.875 0 0 1 21.9 9.975H15.125C14.52 9.975 14.025 9.48 14.025 8.875Z", stroke: "currentColor" }],
	],
});
