/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4.3 13.3851L7.1444 16.3525C7.8777 17.1175 8.2444 17.5 8.7 17.5C9.1557 17.5 9.5223 17.1175 10.2557 16.3525L19.7 6.5", stroke: "currentColor" }],
];

export const Check = /* @__PURE__ */ createIcon("Check", {
	linear: nodes,
	bold: nodes,
});
