/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChevronRight = /* @__PURE__ */ createIcon("ChevronRight", {
	linear: [
		["path", { d: "M9.00005 6C9.00005 6 15 10.4189 15 12C15 13.5812 9 18 9 18", stroke: "currentColor" }],
	],
});
