/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M18.6 8.7001C18.6 8.7001 13.7392 15.3 12 15.3C10.2607 15.3 5.4 8.7 5.4 8.7", stroke: "currentColor" }],
];

export const ChevronDown = /* @__PURE__ */ createIcon("ChevronDown", {
	linear: nodes,
	bold: nodes,
});
