/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M18.6 11.45C18.6 11.45 13.7392 4.85 12 4.85C10.2607 4.85 5.4 11.45 5.4 11.45", stroke: "currentColor" }],
	["path", { d: "M18.6 19.15C18.6 19.15 13.7392 12.55 12 12.55C10.2607 12.55 5.4 19.15 5.4 19.15", stroke: "currentColor" }],
];

export const ChevronsUp = /* @__PURE__ */ createIcon("ChevronsUp", {
	linear: nodes,
	bold: nodes,
});
