/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ChevronsRight = createIcon("ChevronsRight", {
	linear: [
		["path", { d: "M12.5 18C12.5 18 18.5 13.5811 18.5 12C18.5 10.4188 12.5 6 12.5 6", stroke: "currentColor" }],
		["path", { d: "M5.50005 18C5.50005 18 11.5 13.5811 11.5 12C11.5 10.4188 5.5 6 5.5 6", stroke: "currentColor" }],
	],
});

/** @deprecated Use ChevronsRight instead. */
export const ArrowRightDouble = ChevronsRight;
