/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M8.7001 5.4C8.7001 5.4 15.3 10.2608 15.3 12C15.3 13.7393 8.7 18.6 8.7 18.6", stroke: "currentColor" }],
];

export const ChevronRight = /* @__PURE__ */ createIcon("ChevronRight", {
	linear: nodes,
	bold: nodes,
});
