/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChevronLeft = /* @__PURE__ */ createIcon("ChevronLeft", {
	linear: [
		["path", { d: "M15 6C15 6 9.00001 10.4189 9 12C8.99999 13.5812 15 18 15 18", stroke: "currentColor" }],
	],
});
