/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChevronLeft = /* @__PURE__ */ createIcon("ChevronLeft", {
	linear: [
		["path", { d: "M15.3 5.4C15.3 5.4 8.7 10.2608 8.7 12C8.7 13.7393 15.3 18.6 15.3 18.6", stroke: "currentColor" }],
	],
});
