/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M18.5998 15.3C18.5998 15.3 13.739 8.7 11.9998 8.7C10.2606 8.7 5.3998 15.3 5.3998 15.3", stroke: "currentColor" }],
];

export const ChevronUp = /* @__PURE__ */ createIcon("ChevronUp", {
	linear: nodes,
	bold: nodes,
});
