/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M12.55 18.6C12.55 18.6 19.15 13.7392 19.15 12C19.15 10.2607 12.55 5.4 12.55 5.4", stroke: "currentColor" }],
	["path", { d: "M4.8501 18.6C4.8501 18.6 11.45 13.7392 11.45 12C11.45 10.2607 4.85 5.4 4.85 5.4", stroke: "currentColor" }],
];

export const ChevronsRight = /* @__PURE__ */ createIcon("ChevronsRight", {
	linear: nodes,
	bold: nodes,
});
