/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ChevronDown = /* @__PURE__ */ createIcon("ChevronDown", {
	linear: [
		["path", { d: "M18 9.00005C18 9.00005 13.5811 15 12 15C10.4188 15 6 9 6 9", stroke: "currentColor" }],
	],
});
