/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ClapperboardText = /* @__PURE__ */ createIcon("ClapperboardText", {
	linear: [
		["path", { d: "M12 3C7.75736 3 5.63604 3 4.31802 4.31802C3 5.63604 3 7.75736 3 12C3 16.2426 3 18.364 4.31802 19.682C5.63604 21 7.75736 21 12 21C16.2426 21 18.364 21 19.682 19.682C21 18.364 21 16.2426 21 12C21 7.75736 21 5.63604 19.682 4.31802C18.364 3 16.2426 3 12 3Z", stroke: "currentColor" }],
		["path", { d: "M3.25 8H20.75M7 8L10.072 3.2M13.25 8L16.25 3.3125", stroke: "currentColor" }],
		["path", { d: "M6.75 13H14.75M6.75 16.5H12", stroke: "currentColor" }],
	],
});
