/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ClapperboardText = /* @__PURE__ */ createIcon("ClapperboardText", {
	linear: [
		["path", { d: "M12 2.1C7.3331 2.1 4.9996 2.1 3.5498 3.5498C2.1 4.9996 2.1 7.3331 2.1 12C2.1 16.6669 2.1 19.0004 3.5498 20.4502C4.9996 21.9 7.3331 21.9 12 21.9C16.6669 21.9 19.0004 21.9 20.4502 20.4502C21.9 19.0004 21.9 16.6669 21.9 12C21.9 7.3331 21.9 4.9996 20.4502 3.5498C19.0004 2.1 16.6669 2.1 12 2.1ZM2.375 7.6H21.625M6.5 7.6L9.8792 2.32M13.375 7.6L16.675 2.4437M6.225 13.1H15.025M6.225 16.95H12", stroke: "currentColor" }],
	],
});
