/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Clock = /* @__PURE__ */ createIcon("Clock", {
	linear: [
		["circle", { cx: "12", cy: "12", r: "10", stroke: "currentColor" }],
		["path", { d: "M12 7V12L15 14", stroke: "currentColor" }],
	],
});
