/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const CornerDownRight = /* @__PURE__ */ createIcon("CornerDownRight", {
	linear: [
		["path", { d: "M4.5 4V10C4.5 12.83 4.5 14.24 5.38 15.12C6.26 16 7.67 16 10.5 16H19.5 M16 20C16 20 20 17.054 20 16C20 14.946 16 12 16 12", stroke: "currentColor" }],
	],
});
