/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const CornerDownRight = /* @__PURE__ */ createIcon("CornerDownRight", {
	linear: [
		["path", { d: "M3.75 3.2V9.8C3.75 12.913 3.75 14.464 4.718 15.432C5.686 16.4 7.237 16.4 10.35 16.4H20.25M16.4 20.8C16.4 20.8 20.8 17.5594 20.8 16.4C20.8 15.2406 16.4 12 16.4 12", stroke: "currentColor" }],
	],
});
