/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Crop = /* @__PURE__ */ createIcon("Crop", {
	linear: [
		["path", { d: "M5.227 2.101V13.563C5.227 16.019 5.227 17.2475 5.9897 18.0103C6.7535 18.773 7.981 18.773 10.437 18.773H21.899M18.773 21.899V10.437C18.773 7.981 18.773 6.7535 18.0103 5.9897C17.2475 5.227 16.019 5.227 13.563 5.227H2.101", stroke: "currentColor" }],
	],
});
