/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Crop = /* @__PURE__ */ createIcon("Crop", {
	linear: [
		["path", { d: "M4 2V14C4 16.8284 4 18.2426 4.87868 19.1213C5.75736 20 7.17157 20 10 20H22 M20 22V12C20 8.22877 20 6.34315 18.8284 5.17158C17.6569 4 15.7712 4 12 4H2", stroke: "currentColor" }],
	],
});
