/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Crop = /* @__PURE__ */ createIcon("Crop", {
	linear: [
		["path", { d: "M5.5 2.5V13.5C5.5 15.857 5.5 17.036 6.232 17.768C6.965 18.5 8.143 18.5 10.5 18.5H21.5 M18.5 21.5V10.5C18.5 8.143 18.5 6.965 17.768 6.232C17.036 5.5 15.857 5.5 13.5 5.5H2.5", stroke: "currentColor" }],
	],
});
