/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const CursorClick = /* @__PURE__ */ createIcon("CursorClick", {
	linear: [
		["path", { d: "M8.315 7.38L19.601 11.56C20.492 11.89 20.5008 12.3542 19.623 12.7194L16.213 14.1406C15.3352 14.5058 14.5058 15.3352 14.1406 16.213L12.7194 19.623C12.3542 20.5008 11.89 20.492 11.56 19.601L7.38 8.315C7.05 7.424 7.424 7.05 8.315 7.38ZM7.49 4.41V2.32M4.41 7.49H2.32M5.29 5.29L3.86 3.86", stroke: "currentColor" }],
	],
});
