/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Dollar = /* @__PURE__ */ createIcon("Dollar", {
	linear: [
		["path", { d: "M16.4 7.6C16.2 5.9 14.4 4.6 12 4.6C9.5 4.6 7.6 6 7.6 7.9C7.6 10 9.6 11 12 11.5C14.6 12 16.6 13.1 16.6 15.4C16.6 17.6 14.6 19.2 12 19.2C9.4 19.2 7.4 17.9 7.3 16 M12 2.6V4.6M12 19.2V21.4", stroke: "currentColor" }],
	],
});
