/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Dollar = /* @__PURE__ */ createIcon("Dollar", {
	linear: [
		["path", { d: "M16.6332 7.3668C16.4226 5.5767 14.5272 4.2078 12 4.2078C9.3675 4.2078 7.3668 5.682 7.3668 7.6827C7.3668 9.894 9.4728 10.947 12 11.4735C14.7378 12 16.8438 13.1583 16.8438 15.5802C16.8438 17.8968 14.7378 19.5816 12 19.5816C9.2622 19.5816 7.1562 18.2127 7.0509 16.212M12 2.1018V4.2078M12 19.5816V21.8982", stroke: "currentColor" }],
	],
});
