/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Download = /* @__PURE__ */ createIcon("Download", {
	linear: [
		["path", { d: "M3 15V16.5C3 18.6213 3 19.68198 3.65901 20.34099C4.31802 21 5.37868 21 7.5 21H16.5C18.6213 21 19.68198 21 20.34099 20.34099C21 19.68198 21 18.6213 21 16.5V15 M12,14.875l0,-10.125 M7.5,10.75c0,0 3.31418,4.49999 4.5,4.5c1.1859,0.00001 4.5,-4.5 4.5,-4.5", stroke: "currentColor" }],
	],
});
