/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 15.3V16.95C2.1 19.2834 2.1 20.4502 2.8249 21.1751C3.5498 21.9 4.7165 21.9 7.05 21.9H16.95C19.2834 21.9 20.4502 21.9 21.1751 21.1751C21.9 20.4502 21.9 19.2834 21.9 16.95V15.3M12 15.1625l0 -11.1375M7.05 10.625c0 0 3.6456 4.95 4.95 4.95c1.3045 0 4.95 -4.95 4.95 -4.95", stroke: "currentColor" }],
];

export const Download = /* @__PURE__ */ createIcon("Download", {
	linear: nodes,
	bold: nodes,
});
