/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Droplet = /* @__PURE__ */ createIcon("Droplet", {
	linear: [
		["path", { d: "M12 2.32C10.13 4.19 4.85 9.69 4.85 14.64C4.85 18.655 8.051 21.9 12 21.9C15.949 21.9 19.15 18.655 19.15 14.64C19.15 9.69 13.87 4.19 12 2.32Z", stroke: "currentColor" }],
	],
	bold: [
		["path", { d: "M11.364 1.684Q11.682 1.365 12 1.365Q12.318 1.365 12.636 1.684Q20.05 9.097 20.05 14.64Q20.05 18.019 17.697 20.407Q15.339 22.8 12 22.8Q8.661 22.8 6.303 20.407Q3.95 18.019 3.95 14.64Q3.95 9.097 11.364 1.684Z", fill: "currentColor" }],
	],
});
