/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Droplet = /* @__PURE__ */ createIcon("Droplet", {
	linear: [
		["path", { d: "M12 2.32C10.13 4.19 4.85 9.69 4.85 14.64C4.85 18.655 8.051 21.9 12 21.9C15.949 21.9 19.15 18.655 19.15 14.64C19.15 9.69 13.87 4.19 12 2.32Z", stroke: "currentColor" }],
	],
});
