/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Droplet = /* @__PURE__ */ createIcon("Droplet", {
	linear: [
		["path", { d: "M12 3.2C10.3 4.9 5.5 9.9 5.5 14.4C5.5 18.05 8.41 21 12 21C15.59 21 18.5 18.05 18.5 14.4C18.5 9.9 13.7 4.9 12 3.2Z", stroke: "currentColor" }],
	],
});
