/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Edit = createIcon("Edit", {
	linear: [
		["path", { d: "M16.3872 3.9192L17.5414 2.765A2.6118 2.6118 0 0 1 21.235 6.4586L13.617 14.0766L9 15L9.9234 10.383L16.3872 3.9192ZM16.3872 3.9192L20.0808 7.6128", stroke: "currentColor" }],
		["path", { d: "M6 15H3.75C2.7835 15 2 15.7835 2 16.75C2 17.7165 2.7835 18.5 3.75 18.5H13.25C14.2165 18.5 15 19.2835 15 20.25C15 21.2165 14.2165 22 13.25 22H11", stroke: "currentColor" }],
	],
});

/** @deprecated Use Edit instead. */
export const Edit01 = Edit;
