/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const EditOff = /* @__PURE__ */ createIcon("EditOff", {
	linear: [
		["path", { d: "M10.962 7.356L15.141 3.177C16.712 1.619 19.247 1.625 20.811 3.189C22.375 4.753 22.381 7.288 20.823 8.859L16.644 13.038M13.038 16.644L9.36 20.322C9.193 20.49 8.979 20.604 8.747 20.651L2 22L3.349 15.253C3.396 15.021 3.51 14.807 3.678 14.64L7.356 10.962M13.365 4.953L19.047 10.635M2 2L22 22", stroke: "currentColor" }],
	],
});
