/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const FileCode = /* @__PURE__ */ createIcon("FileCode", {
	linear: [
		["path", { d: "M11.4 3C12.58 3 13.12 3.4 14.4 4.55L17.6 7.45C19.23 8.93 20 9.65 20 12C20 16.2426 20 18.364 18.8284 19.682C17.6569 21 15.7712 21 12 21C8.2288 21 6.3431 21 5.1716 19.682C4 18.364 4 16.2426 4 12C4 7.7574 4 5.636 5.1716 4.318C6.3431 3 8.0288 3 11.4 3Z", stroke: "currentColor" }],
		["path", { d: "M12.8 3.45V6.2C12.8 8.0856 12.8 9.0284 13.3858 9.6142C13.9716 10.2 14.9144 10.2 16.8 10.2H19.55", stroke: "currentColor" }],
		["path", { d: "M8.5 13.2L7.1 14.6L8.5 16M11.9 13.2L10.1 18M13.1 15.6L14.5 17L13.1 18.4", stroke: "currentColor" }],
	],
});
