/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const FileText = /* @__PURE__ */ createIcon("FileText", {
	linear: [
		["path", { d: "M10.29 3C11.55 3 12.27 3 12.9 3.22C13.53 3.5 14.07 3.95 14.97 4.75L18.57 8C19.65 8.94 20.19 9.53 20.59 10.29C20.95 11.19 21 11.91 21 13.3V13.8C21 17.18 21 18.91 19.95 19.95C18.91 21 17.18 21 13.8 21H10.2C6.82 21 5.09 21 4.05 19.95C3 18.91 3 17.18 3 13.8V10.2C3 6.82 3 5.09 4.05 4.05C5.09 3 6.82 3 10.29 3Z", stroke: "currentColor" }],
		["path", { d: "M12.9 3.36V5.7C12.9 7.81 12.9 8.85 13.53 9.57C14.25 10.2 15.29 10.2 17.4 10.2H20.55", stroke: "currentColor" }],
		["path", { d: "M6.6 14.25H13.8M6.6 17.4H10.95", stroke: "currentColor" }],
	],
});
