/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const FileAdd = /* @__PURE__ */ createIcon("FileAdd", {
	linear: [
		["path", { d: "M11.4 21H12C15.7712 21 17.6569 21 18.8284 19.682C20 18.364 20 16.2426 20 12C20 9.65 19.23 8.93 17.6 7.45L14.4 4.55C13.12 3.4 12.58 3 11.4 3C8.0288 3 6.3431 3 5.1716 4.318C4 5.636 4 7.7574 4 12V13.1", stroke: "currentColor" }],
		["path", { d: "M12.8 3.45V6.2C12.8 8.0856 12.8 9.0284 13.3858 9.6142C13.9716 10.2 14.9144 10.2 16.8 10.2H19.55", stroke: "currentColor" }],
		["path", { d: "M6.6 14.05V21.25M3 17.65H10.2", stroke: "currentColor" }],
	],
});
