/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Fingerprint = /* @__PURE__ */ createIcon("Fingerprint", {
	linear: [
		["path", { d: "M3.7682 7.6236C5.2166 4.3413 8.1863 2.101 12 2.101C16.8911 2.101 20.857 6.0669 20.857 10.958V12.521C20.857 14.5216 20.6173 16.3764 20.1276 18.0436", stroke: "currentColor" }],
		["path", { d: "M3.143 11.479V12.521C3.143 14.5216 3.3827 16.3764 3.8724 18.0436", stroke: "currentColor" }],
		["path", { d: "M8.353 21.378C7.6653 18.5438 7.311 15.647 7.311 12.521V10.958C7.311 8.3686 9.4106 6.269 12 6.269C14.5894 6.269 16.689 8.3686 16.689 10.958V12.521C16.689 15.647 16.3347 18.5438 15.647 21.378", stroke: "currentColor" }],
		["path", { d: "M12 10.437V12.521C12 14.7092 12.0834 16.7932 12.3647 18.773", stroke: "currentColor" }],
	],
});
