/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Fingerprint = /* @__PURE__ */ createIcon("Fingerprint", {
	linear: [
		["path", { d: "M4.1 7.8C5.49 4.65 8.34 2.5 12 2.5C16.694 2.5 20.5 6.306 20.5 11V12.5C20.5 14.42 20.27 16.2 19.8 17.8", stroke: "currentColor" }],
		["path", { d: "M3.5 11.5V12.5C3.5 14.42 3.73 16.2 4.2 17.8", stroke: "currentColor" }],
		["path", { d: "M8.5 21C7.84 18.28 7.5 15.5 7.5 12.5V11C7.5 8.515 9.515 6.5 12 6.5C14.485 6.5 16.5 8.515 16.5 11V12.5C16.5 15.5 16.16 18.28 15.5 21", stroke: "currentColor" }],
		["path", { d: "M12 10.5V12.5C12 14.6 12.08 16.6 12.35 18.5", stroke: "currentColor" }],
	],
});
