/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const FlipHorizontal = /* @__PURE__ */ createIcon("FlipHorizontal", {
	linear: [
		["path", { d: "M3.739 7.039L7.611 10.911C8.2644 11.5644 8.2644 12.4356 7.611 13.089L3.739 16.961C3.0856 17.6144 2.65 17.434 2.65 16.51L2.65 7.49C2.65 6.566 3.0856 6.3856 3.739 7.039ZM20.261 7.039L16.389 10.911C15.7356 11.5644 15.7356 12.4356 16.389 13.089L20.261 16.961C20.9144 17.6144 21.35 17.434 21.35 16.51L21.35 7.49C21.35 6.566 20.9144 6.3856 20.261 7.039ZM12 2.1V3.86M12 7.82V9.58M12 14.42V16.18M12 20.14V21.9", stroke: "currentColor" }],
	],
});
