/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const FlipHorizontal = /* @__PURE__ */ createIcon("FlipHorizontal", {
	linear: [
		["path", { d: "M4.49 7.49L8.01 11.01C8.604 11.604 8.604 12.396 8.01 12.99L4.49 16.51C3.896 17.104 3.5 16.94 3.5 16.1L3.5 7.9C3.5 7.06 3.896 6.896 4.49 7.49Z M19.51 7.49L15.99 11.01C15.396 11.604 15.396 12.396 15.99 12.99L19.51 16.51C20.104 17.104 20.5 16.94 20.5 16.1L20.5 7.9C20.5 7.06 20.104 6.896 19.51 7.49Z M12 3V4.6M12 8.2V9.8M12 14.2V15.8M12 19.4V21", stroke: "currentColor" }],
	],
});
