/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Forward = /* @__PURE__ */ createIcon("Forward", {
	linear: [
		["path", { d: "M15.3001 14.75c0 0 4.9499 -3.6457 4.9499 -4.9501c0 -1.3044 -4.95 -4.95 -4.95 -4.95M19.8375 9.8h-8.3875c-3.889 0 -5.8336 0 -7.0418 1.2082c-1.2082 1.2082 -1.2082 3.1528 -1.2082 7.0418v0.55", stroke: "currentColor" }],
	],
});
