/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Forward = /* @__PURE__ */ createIcon("Forward", {
	linear: [
		["path", { d: "M15.00008,14.5c0,0 4.49994,-3.31425 4.49995,-4.50008c0.00001,-1.18582 -4.50002,-4.49996 -4.50002,-4.49996M19.125,10h-7.625c-3.5355,0 -5.3033,0 -6.40165,1.09835c-1.09835,1.09835 -1.09835,2.86615 -1.09835,6.40165v0.5", stroke: "currentColor" }],
	],
});
