/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Gauge = /* @__PURE__ */ createIcon("Gauge", {
	linear: [
		["path", { d: "M5.389 19.711A9.35 9.35 0 1 1 18.611 19.711M10.02 13.1A1.98 1.98 0 1 0 13.98 13.1A1.98 1.98 0 1 0 10.02 13.1ZM13.4003 11.6997L16.356 8.744", stroke: "currentColor" }],
	],
});
