/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitCommit = /* @__PURE__ */ createIcon("GitCommit", {
	linear: [
		["path", { d: "M8.7 12A3.3 3.3 0 1 0 15.3 12A3.3 3.3 0 1 0 8.7 12ZM2.1 12H8.7M15.3 12H21.9", stroke: "currentColor" }],
	],
});
