/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitMergeConflict = /* @__PURE__ */ createIcon("GitMergeConflict", {
	linear: [
		["path", { d: "M6 11.75V20.25", stroke: "currentColor" }],
		["path", { d: "M11.75 6H16C17.1046 6 18 6.89543 18 8V15", stroke: "currentColor" }],
		["path", { d: "M18 21C19.6569 21 21 19.6569 21 18C21 16.3431 19.6569 15 18 15C16.3431 15 15 16.3431 15 18C15 19.6569 16.3431 21 18 21Z", stroke: "currentColor" }],
		["path", { d: "M3.5 3.5L8.5 8.5", stroke: "currentColor" }],
		["path", { d: "M8.5 3.5L3.5 8.5", stroke: "currentColor" }],
	],
});

/** @deprecated Use GitMergeConflict instead. */
export const MergeConflict = GitMergeConflict;
