/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitCommit = /* @__PURE__ */ createIcon("GitCommit", {
	linear: [
		["path", { d: "M8.7 12A3.3 3.3 0 1 0 15.3 12A3.3 3.3 0 1 0 8.7 12ZM2.1 12H8.7M15.3 12H21.9", stroke: "currentColor" }],
	],
	bold: [
		["path", { d: "M2.1 11.1H7.889Q8.131 9.929 9.03 9.03Q10.26 7.8 12 7.8Q13.74 7.8 14.97 9.03Q15.869 9.929 16.111 11.1H21.9Q22.8 11.1 22.8 12Q22.8 12.9 21.9 12.9H16.111Q15.869 14.071 14.97 14.97Q13.74 16.2 12 16.2Q10.26 16.2 9.03 14.97Q8.131 14.071 7.889 12.9H2.1Q1.2 12.9 1.2 12Q1.2 11.1 2.1 11.1Z", fill: "currentColor" }],
	],
});
