/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitBranch = /* @__PURE__ */ createIcon("GitBranch", {
	linear: [
		["circle", { cx: "6.5", cy: "5.25", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "6.5", cy: "18.75", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "17.5", cy: "8.25", r: "2.25", stroke: "currentColor" }],
		["path", { d: "M6.5 7.5V16.5", stroke: "currentColor" }],
		["path", { d: "M17.5 10.5C17.5 12.9 15.6 13.6 12 13.6C8.6 13.6 6.8 14.5 6.5 16.5", stroke: "currentColor" }],
	],
});
