/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitFork = /* @__PURE__ */ createIcon("GitFork", {
	linear: [
		["path", { d: "M3.25 5.25A2.25 2.25 0 1 0 7.75 5.25A2.25 2.25 0 1 0 3.25 5.25Z M16.25 5.25A2.25 2.25 0 1 0 20.75 5.25A2.25 2.25 0 1 0 16.25 5.25Z M9.75 18.75A2.25 2.25 0 1 0 14.25 18.75A2.25 2.25 0 1 0 9.75 18.75Z M5.5 7.5C5.5 11 7 12 10 12H14C17 12 18.5 11 18.5 7.5 M12 12V16.5", stroke: "currentColor" }],
	],
});
