/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitCommit = /* @__PURE__ */ createIcon("GitCommit", {
	linear: [
		["path", { d: "M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z M3 12H9M15 12H21", stroke: "currentColor" }],
	],
});
