/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const GitPullRequest = createIcon("GitPullRequest", {
	linear: [
		["path", { d: "M18 21C19.6569 21 21 19.6569 21 18C21 16.3431 19.6569 15 18 15C16.3431 15 15 16.3431 15 18C15 19.6569 16.3431 21 18 21Z", stroke: "currentColor" }],
		["path", { d: "M6 9C7.65685 9 9 7.65685 9 6C9 4.34315 7.65685 3 6 3C4.34315 3 3 4.34315 3 6C3 7.65685 4.34315 9 6 9Z", stroke: "currentColor" }],
		["path", { d: "M6 20.25V9", stroke: "currentColor" }],
		["path", { d: "M12 6H16C17.1046 6 18 6.89543 18 8V15", stroke: "currentColor" }],
		["path", { d: "M15 3L12 6L15 9", stroke: "currentColor" }],
	],
});
