/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitGraph = /* @__PURE__ */ createIcon("GitGraph", {
	linear: [
		["path", { d: "M2.375 4.575A2.475 2.475 0 1 0 7.325 4.575A2.475 2.475 0 1 0 2.375 4.575ZM2.375 19.425A2.475 2.475 0 1 0 7.325 19.425A2.475 2.475 0 1 0 2.375 19.425ZM16.675 4.575A2.475 2.475 0 1 0 21.625 4.575A2.475 2.475 0 1 0 16.675 4.575ZM4.85 7.05V16.95M12 2.1V21.9M19.15 7.05C19.15 11.45 17.94 14.75 15.575 16.675", stroke: "currentColor" }],
	],
});
