/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitFork = /* @__PURE__ */ createIcon("GitFork", {
	linear: [
		["circle", { cx: "5.5", cy: "5.25", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "18.5", cy: "5.25", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "12", cy: "18.75", r: "2.25", stroke: "currentColor" }],
		["path", { d: "M5.5 7.5C5.5 11 7 12 10 12H14C17 12 18.5 11 18.5 7.5", stroke: "currentColor" }],
		["path", { d: "M12 12V16.5", stroke: "currentColor" }],
	],
});
