/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitPullRequest = /* @__PURE__ */ createIcon("GitPullRequest", {
	linear: [
		["path", { d: "M3.25 5.25A2.25 2.25 0 1 0 7.75 5.25A2.25 2.25 0 1 0 3.25 5.25Z M3.25 18.75A2.25 2.25 0 1 0 7.75 18.75A2.25 2.25 0 1 0 3.25 18.75Z M16.25 18.75A2.25 2.25 0 1 0 20.75 18.75A2.25 2.25 0 1 0 16.25 18.75Z M5.5 7.5V16.5 M18.5 16.5V8.25C18.5 6.45 17.3 5.25 15.5 5.25H11.5 M14 2.85C14 2.85 11.5 4.6 11.5 5.25C11.5 5.9 14 7.65 14 7.65", stroke: "currentColor" }],
	],
});
