/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitPullRequest = /* @__PURE__ */ createIcon("GitPullRequest", {
	linear: [
		["circle", { cx: "5.5", cy: "5.25", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "5.5", cy: "18.75", r: "2.25", stroke: "currentColor" }],
		["circle", { cx: "18.5", cy: "18.75", r: "2.25", stroke: "currentColor" }],
		["path", { d: "M5.5 7.5V16.5", stroke: "currentColor" }],
		["path", { d: "M18.5 16.5V8.25C18.5 6.45 17.3 5.25 15.5 5.25H11.5", stroke: "currentColor" }],
		["path", { d: "M14 2.85C14 2.85 11.5 4.6 11.5 5.25C11.5 5.9 14 7.65 14 7.65", stroke: "currentColor" }],
	],
});
