/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GitBranch = /* @__PURE__ */ createIcon("GitBranch", {
	linear: [
		["path", { d: "M4.25 5.25A2.25 2.25 0 1 0 8.75 5.25A2.25 2.25 0 1 0 4.25 5.25Z M4.25 18.75A2.25 2.25 0 1 0 8.75 18.75A2.25 2.25 0 1 0 4.25 18.75Z M15.25 8.25A2.25 2.25 0 1 0 19.75 8.25A2.25 2.25 0 1 0 15.25 8.25Z M6.5 7.5V16.5 M17.5 10.5C17.5 12.9 15.6 13.6 12 13.6C8.6 13.6 6.8 14.5 6.5 16.5", stroke: "currentColor" }],
	],
});
