/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M1.969 16.25L8.969 4.126L15.031 7.626L8.031 19.75Z", fill: "#FBBC04" }],
	["path", { d: "M15.031 4.126L22.031 16.25A3.5 3.5 0 0 1 15.969 19.75L8.969 7.626A3.5 3.5 0 0 1 15.031 4.126Z", fill: "#4285F4" }],
	["circle", { cx: "5", cy: "18", r: "3.5", fill: "#34A853" }],
];

export const GoogleAdsColor = /* @__PURE__ */ createIcon("GoogleAdsColor", {
	linear: nodes,
	bold: nodes,
});
