/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.754 13.158L7.184 7.218A5 5 0 0 0 7.67 8.376L11.134 14.376L9.816 16.658A5 5 0 0 0 3.754 13.158ZM15.031 4.126L22.031 16.25A3.5 3.5 0 0 1 15.969 19.75L8.969 7.626A3.5 3.5 0 0 1 15.031 4.126Z", fill: "currentColor" }],
	["circle", { cx: "5", cy: "18", r: "3.5", fill: "currentColor" }],
];

export const GoogleAds = /* @__PURE__ */ createIcon("GoogleAds", {
	linear: nodes,
	bold: nodes,
});
