/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const GraduationCap = /* @__PURE__ */ createIcon("GraduationCap", {
	linear: [
		["path", { d: "M13.6745 4.7185L20.2245 8.0279C21.229 8.5354 21.229 9.2127 20.2245 9.7201L13.6745 13.0295C12.67 13.537 11.33 13.537 10.3255 13.0295L3.7755 9.7201C2.771 9.2127 2.771 8.5354 3.7755 8.0279L10.3255 4.7185C11.33 4.2111 12.67 4.2111 13.6745 4.7185ZM5.9564 10.8538V15.7512C5.9564 17.21 8.6656 19.294 12 19.294C15.3344 19.294 18.0436 17.21 18.0436 15.7512V10.8538M21.899 8.874V14.084", stroke: "currentColor" }],
	],
});
