/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["circle", { cx: "5", cy: "8", r: "1.9", fill: "currentColor" }],
	["circle", { cx: "5", cy: "16", r: "1.9", fill: "currentColor" }],
	["circle", { cx: "12", cy: "8", r: "1.9", fill: "currentColor" }],
	["circle", { cx: "12", cy: "16", r: "1.9", fill: "currentColor" }],
	["circle", { cx: "19", cy: "8", r: "1.9", fill: "currentColor" }],
	["circle", { cx: "19", cy: "16", r: "1.9", fill: "currentColor" }],
];

export const GripHorizontal = /* @__PURE__ */ createIcon("GripHorizontal", {
	linear: nodes,
	bold: nodes,
});
