/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Hamburger = createIcon("Hamburger", {
	linear: [
		["path", { d: "M4 7h16M4 12h16M4 17h16", stroke: "currentColor" }],
	],
});
