/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Heading = /* @__PURE__ */ createIcon("Heading", {
	linear: [
		["path", { d: "M6 4V20 M18 4V20 M6 12H18", stroke: "currentColor" }],
	],
});
