/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Heading1 = /* @__PURE__ */ createIcon("Heading1", {
	linear: [
		["path", { d: "M4 5V19M13 5V19M4 12H13 M16.9 13.8L18.7 12.6V19", stroke: "currentColor" }],
	],
});
