/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Heading2 = /* @__PURE__ */ createIcon("Heading2", {
	linear: [
		["path", { d: "M4 5V19M13 5V19M4 12H13 M16.4 14.2C16.6 13.4 17.3 12.9 18.1 12.9C19.1 12.9 19.9 13.6 19.9 14.6C19.9 16.2 16.4 17.3 16.4 19H19.9", stroke: "currentColor" }],
	],
});
