/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Heading3 = /* @__PURE__ */ createIcon("Heading3", {
	linear: [
		["path", { d: "M3.2 4.3V19.7M13.1 4.3V19.7M3.2 12H13.1M16.95 14.09C17.28 13.43 17.94 12.99 18.71 12.99C19.7 12.99 20.58 13.65 20.58 14.64C20.58 15.52 19.81 16.18 18.82 16.18C19.92 16.18 20.8 16.95 20.8 17.94C20.8 19.04 19.92 19.81 18.71 19.81C17.83 19.81 17.06 19.37 16.73 18.6", stroke: "currentColor" }],
	],
});
