/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Home = /* @__PURE__ */ createIcon("Home", {
	linear: [
		["path", { d: "M9.54434 3.81037l-4.71487 2.94679C3.4543 7.6412 2.96317 8.42701 3.25784 10.19509l1.0805 7.36698C4.73124 20.01774 5.61528 21 8.07094 21h7.85812c2.45566 0 3.3397-0.98226 3.7326-3.43793l1.0805-7.36698c0.29468-1.76808-0.19645-2.55389-1.57163-3.43793l-4.71487-2.94679c-1.76808-1.08049-3.14325-1.08049-4.91132 0Z", stroke: "currentColor" }],
		["path", { d: "M9.05321 17.07094h5.89358", stroke: "currentColor" }],
	],
});
