/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Home = /* @__PURE__ */ createIcon("Home", {
	linear: [
		["path", { d: "M3 12.2C3 10 3 9 3.4 8.25C3.8 7.5 4.6 7 6.3 5.95L8.3 4.7C10.1 3.6 11 3 12 3C13 3 13.9 3.6 15.7 4.7L17.7 5.95C19.4 7 20.2 7.5 20.6 8.25C21 9 21 10 21 12.2V13.75C21 17.5 21 19.2 20.1 20.1C19.2 21 17.6 21 14 21H10C6.4 21 4.8 21 3.9 20.1C3 19.2 3 17.5 3 13.75V12.2Z", stroke: "currentColor" }],
		["path", { d: "M9 17.25H15", stroke: "currentColor" }],
	],
});
