/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Home = /* @__PURE__ */ createIcon("Home", {
	linear: [
		["path", { d: "M2.1 12.22C2.1 9.8 2.1 8.7 2.54 7.875C2.98 7.05 3.86 6.5 5.73 5.345L7.93 3.97C9.91 2.76 10.9 2.1 12 2.1C13.1 2.1 14.09 2.76 16.07 3.97L18.27 5.345C20.14 6.5 21.02 7.05 21.46 7.875C21.9 8.7 21.9 9.8 21.9 12.22V13.925C21.9 18.05 21.9 19.92 20.91 20.91C19.92 21.9 18.16 21.9 14.2 21.9H9.8C5.84 21.9 4.08 21.9 3.09 20.91C2.1 19.92 2.1 18.05 2.1 13.925V12.22Z", stroke: "currentColor" }],
		["path", { d: "M8.7 17.775H15.3", stroke: "currentColor" }],
	],
});
