/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Image = /* @__PURE__ */ createIcon("Image", {
	linear: [
		["path", { d: "M12 3C7.75736 3 5.63604 3 4.31802 4.31802C3 5.63604 3 7.75736 3 12C3 16.2426 3 18.364 4.31802 19.682C5.63604 21 7.75736 21 12 21C16.2426 21 18.364 21 19.682 19.682C21 18.364 21 16.2426 21 12C21 7.75736 21 5.63604 19.682 4.31802C18.364 3 16.2426 3 12 3Z", stroke: "currentColor" }],
		["path", { d: "M3 13L5.13 11.1363C5.9211 10.4441 7.1129 10.4838 7.8564 11.2273L11.6436 15.0145C12.33 15.7009 13.4103 15.7944 14.2043 15.2364L14.5486 14.9944C15.5012 14.3249 16.7902 14.4025 17.6556 15.1814L20.6 17.8314", stroke: "currentColor" }],
		["circle", { cx: "15.5", cy: "8", r: "1.5", stroke: "currentColor" }],
	],
});

/** @deprecated Use Image instead. */
export const Images = Image;
