/* Generated by scripts/build-icons.ts. Do not edit. */
export { Home } from "./home";
export { Search } from "./search";
export { SendMessage } from "./send-message";
export { Snapchat } from "./snapchat";
export { Trash } from "./trash";
export { X } from "./x";
