/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Indent = /* @__PURE__ */ createIcon("Indent", {
	linear: [
		["path", { d: "M3 4H21M11.5 9.3H21M11.5 14.7H21M3 20H21 M4.2 15C4.2 15 7.2 12.79 7.2 12C7.2 11.21 4.2 9 4.2 9", stroke: "currentColor" }],
	],
});
