/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M10.5334 3.2H20.8M7.5986 20.8L16.3986 3.2M3.1986 20.8L13.4653 20.8", stroke: "currentColor" }],
];

export const Italic = /* @__PURE__ */ createIcon("Italic", {
	linear: nodes,
	bold: nodes,
});
