/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Kanban = /* @__PURE__ */ createIcon("Kanban", {
	linear: [
		["path", { d: "M4.3 3.2V18.6M12 3.2V11.45M19.7 3.2V21.9", stroke: "currentColor" }],
	],
});
