/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Kanban = /* @__PURE__ */ createIcon("Kanban", {
	linear: [
		["path", { d: "M5 4V18M12 4V11.5M19 4V21", stroke: "currentColor" }],
	],
});
