/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Key = /* @__PURE__ */ createIcon("Key", {
	linear: [
		["path", { d: "M9.58 8.48A5.94 5.94 0 1 0 21.46 8.48A5.94 5.94 0 1 0 9.58 8.48ZM11.3202 12.6798L3.64 20.36M6.06 17.94L8.26 20.14M9.03 14.97L10.9 16.84", stroke: "currentColor" }],
		["circle", { cx: "16.29", cy: "7.71", r: "1.43", fill: "currentColor", stroke: "none" }],
	],
});
