/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const LayoutAlignLeft = /* @__PURE__ */ createIcon("LayoutAlignLeft", {
	linear: [
		["path", { d: "M10.9 2.1H13.1C17.2483 2.1 19.3226 2.1 20.6112 3.3887C21.9 4.6775 21.9 6.7516 21.9 10.9V13.1C21.9 17.2483 21.9 19.3226 20.6112 20.6112C19.3226 21.9 17.2483 21.9 13.1 21.9H10.9C6.7516 21.9 4.6775 21.9 3.3887 20.6112C2.1 19.3226 2.1 17.2483 2.1 13.1V10.9C2.1 6.7516 2.1 4.6775 3.3887 3.3887C4.6775 2.1 6.7516 2.1 10.9 2.1Z", stroke: "currentColor" }],
		["path", { d: "M7.6054 16.4054L7.6054 7.6054", stroke: "currentColor" }],
	],
});
