/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const LifeBuoy = /* @__PURE__ */ createIcon("LifeBuoy", {
	linear: [
		["path", { d: "M2.75 12A9.25 9.25 0 1 0 21.25 12A9.25 9.25 0 1 0 2.75 12Z M8.25 12A3.75 3.75 0 1 0 15.75 12A3.75 3.75 0 1 0 8.25 12Z M9.35 9.35L5.46 5.46M14.65 9.35L18.54 5.46M14.65 14.65L18.54 18.54M9.35 14.65L5.46 18.54", stroke: "currentColor" }],
	],
});
