/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const LifeBuoy = /* @__PURE__ */ createIcon("LifeBuoy", {
	linear: [
		["path", { d: "M2.1025 12A9.8975 9.8975 0 1 0 21.8975 12A9.8975 9.8975 0 1 0 2.1025 12ZM7.9875 12A4.0125 4.0125 0 1 0 16.0125 12A4.0125 4.0125 0 1 0 7.9875 12ZM9.1645 9.1645L5.0022 5.0022M14.8355 9.1645L18.9978 5.0022M14.8355 14.8355L18.9978 18.9978M9.1645 14.8355L5.0022 18.9978", stroke: "currentColor" }],
	],
});
