/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 5.4h18.7M2.1 10.9h18.7M2.1 16.4h8.8", stroke: "currentColor" }],
	["path", { d: "M21.9 18.6C21.9 18.6 19.0645 15.3 18.05 15.3C17.0354 15.3 14.2 18.6 14.2 18.6", stroke: "currentColor" }],
];

export const ListUp = /* @__PURE__ */ createIcon("ListUp", {
	linear: nodes,
	bold: nodes,
});
