/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListOrdered = /* @__PURE__ */ createIcon("ListOrdered", {
	linear: [
		["path", { d: "M10.5 6H21M10.5 12H21M10.5 18H21 M3.9 4.6L5.3 3.8V8.4 M3.6 15.7C3.8 15.1 4.4 14.7 5 14.7C5.8 14.7 6.4 15.3 6.4 16C6.4 17.3 3.6 18.2 3.6 19.8H6.4", stroke: "currentColor" }],
	],
});
