/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListChecks = /* @__PURE__ */ createIcon("ListChecks", {
	linear: [
		["path", { d: "M3,8.19072l0.90504,0.94416c0.23333,0.24343 0.35,0.36512 0.49497,0.36512c0.14497,0 0.26164,-0.1217 0.49499,-0.36512l3.005,-3.13488M3,17.19072l0.90504,0.94416c0.23333,0.24343 0.35,0.36512 0.49497,0.36512c0.14497,0 0.26164,-0.12169 0.49499,-0.36512l3.005,-3.13488", stroke: "currentColor" }],
		["path", { d: "M11 6H21M11 10H21M11 15H21M11 19H21", stroke: "currentColor" }],
	],
});
