/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.0957 4.3H21.8957", stroke: "currentColor" }],
	["path", { d: "M5.3957 12H18.5957", stroke: "currentColor" }],
	["path", { d: "M8.6957 19.7H15.2957", stroke: "currentColor" }],
];

export const ListFilter = /* @__PURE__ */ createIcon("ListFilter", {
	linear: nodes,
	bold: nodes,
});
