/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListFilter = /* @__PURE__ */ createIcon("ListFilter", {
	linear: [
		["path", { d: "M2.99609 5H20.9961", stroke: "currentColor" }],
		["path", { d: "M5.99609 12H17.9961", stroke: "currentColor" }],
		["path", { d: "M8.99609 19H14.9961", stroke: "currentColor" }],
	],
});
