/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListChecks = /* @__PURE__ */ createIcon("ListChecks", {
	linear: [
		["path", { d: "M2.1 7.8098l0.9955 1.0386c0.2567 0.2678 0.385 0.4016 0.5445 0.4016c0.1595 0 0.2878 -0.1339 0.5445 -0.4016l3.3055 -3.4484M2.1 17.7098l0.9955 1.0386c0.2567 0.2678 0.385 0.4016 0.5445 0.4016c0.1595 0 0.2878 -0.1339 0.5445 -0.4016l3.3055 -3.4484", stroke: "currentColor" }],
		["path", { d: "M10.9 5.4H21.9M10.9 9.8H21.9M10.9 15.3H21.9M10.9 19.7H21.9", stroke: "currentColor" }],
	],
});
