/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 5.4h18.7M2.1 10.9h18.7M2.1 16.4h7.7", stroke: "currentColor" }],
	["path", { d: "M21.9 15.3C21.9 15.3 19.0645 18.6 18.05 18.6C17.0354 18.6 14.2 15.3 14.2 15.3", stroke: "currentColor" }],
];

export const ListDown = /* @__PURE__ */ createIcon("ListDown", {
	linear: nodes,
	bold: nodes,
});
