/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const List = /* @__PURE__ */ createIcon("List", {
	linear: [
		["path", { d: "M9.12109 5H21.1211M9.12109 12H21.1211M9.12109 19H21.1211", stroke: "currentColor" }],
		["circle", { cx: "3.12109", cy: "5", r: "1.15", fill: "currentColor" }],
		["circle", { cx: "3.12109", cy: "12", r: "1.15", fill: "currentColor" }],
		["circle", { cx: "3.12109", cy: "19", r: "1.15", fill: "currentColor" }],
	],
});
