/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ListUp = createIcon("ListUp", {
	linear: [
		["path", { d: "M3 6h17M3 11h17M3 16h8", stroke: "currentColor" }],
		["path", { d: "M21 18C21 18 18.42231 15 17.5 15C16.57763 15 14 18 14 18", stroke: "currentColor" }],
	],
});
