/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListDash = /* @__PURE__ */ createIcon("ListDash", {
	linear: [
		["path", { d: "M9 5L21 5", stroke: "currentColor" }],
		["path", { d: "M3 5L5 5", stroke: "currentColor" }],
		["path", { d: "M9 12L21 12", stroke: "currentColor" }],
		["path", { d: "M3 12L5 12", stroke: "currentColor" }],
		["path", { d: "M9 19L21 19", stroke: "currentColor" }],
		["path", { d: "M3 19L5 19", stroke: "currentColor" }],
	],
});
