/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ListOrdered = /* @__PURE__ */ createIcon("ListOrdered", {
	linear: [
		["path", { d: "M10.35 5.4H21.9M10.35 12H21.9M10.35 18.6H21.9M3.09 3.86L4.63 2.98V8.04M2.76 16.07C2.98 15.41 3.64 14.97 4.3 14.97C5.18 14.97 5.84 15.63 5.84 16.4C5.84 17.83 2.76 18.82 2.76 20.58H5.84", stroke: "currentColor" }],
	],
});
