/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ListDown = createIcon("ListDown", {
	linear: [
		["path", { d: "M3 6h17M3 11h17M3 16h7", stroke: "currentColor" }],
		["path", { d: "M21 15C21 15 18.42231 18 17.5 18C16.57763 18 14 15 14 15", stroke: "currentColor" }],
	],
});
