/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Locate = /* @__PURE__ */ createIcon("Locate", {
	linear: [
		["path", { d: "M4.9144 12A7.0856 7.0856 0 1 0 19.0856 12A7.0856 7.0856 0 1 0 4.9144 12ZM12 2.101V4.9144M12 19.0856V21.899M2.101 12H4.9144M19.0856 12H21.899", stroke: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "2.084", fill: "currentColor", stroke: "none" }],
	],
});
