/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Locate = /* @__PURE__ */ createIcon("Locate", {
	linear: [
		["path", { d: "M5.2 12A6.8 6.8 0 1 0 18.8 12A6.8 6.8 0 1 0 5.2 12Z M12 2.5V5.2M12 18.8V21.5M2.5 12H5.2M18.8 12H21.5", stroke: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "2", fill: "currentColor", stroke: "none" }],
	],
});
