/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Lock = /* @__PURE__ */ createIcon("Lock", {
	linear: [
		["path", { d: "M8.5 10.75H15.5C17.85 10.75 19.05 10.75 19.77 11.48C20.5 12.2 20.5 13.4 20.5 15.75V16.25C20.5 18.6 20.5 19.8 19.77 20.52C19.05 21.25 17.85 21.25 15.5 21.25H8.5C6.15 21.25 4.95 21.25 4.23 20.52C3.5 19.8 3.5 18.6 3.5 16.25V15.75C3.5 13.4 3.5 12.2 4.23 11.48C4.95 10.75 6.15 10.75 8.5 10.75Z M7 10.75V8C7 5.24 9.24 3 12 3C14.76 3 17 5.24 17 8V10.75 M12 14.25V17.75", stroke: "currentColor" }],
	],
});
