/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Login = /* @__PURE__ */ createIcon("Login", {
	linear: [
		["path", { d: "M15 3H16.5C18.6213 3 19.68198 3 20.34099 3.65901C21 4.31802 21 5.37868 21 7.5V16.5C21 18.6213 21 19.68198 20.34099 20.34099C19.68198 21 18.6213 21 16.5 21H15", stroke: "currentColor" }],
		["path", { d: "M13.375,12h-8.77502", stroke: "currentColor" }],
		["path", { d: "M9.8,15.9c0,0 3.9,-2.87229 3.9,-3.9c0,-1.02778 -3.9,-3.9 -3.9,-3.9", stroke: "currentColor" }],
	],
});
