/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M8.7 2.1H7.05C4.7166 2.1 3.5498 2.1 2.8249 2.8249C2.1 3.5498 2.1 4.7165 2.1 7.05V16.95C2.1 19.2834 2.1 20.4502 2.8249 21.1751C3.5498 21.9 4.7166 21.9 7.05 21.9H8.7M19.7825 12H10.13M15.85 16.29C15.85 16.29 20.14 13.1305 20.14 12C20.14 10.8694 15.85 7.71 15.85 7.71", stroke: "currentColor" }],
];

export const Logout = /* @__PURE__ */ createIcon("Logout", {
	linear: nodes,
	bold: nodes,
});
