/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const MagicWand = /* @__PURE__ */ createIcon("MagicWand", {
	linear: [
		["path", { d: "M3.8 20.2L11.9 12.1 M16.4 3C16.8 5.75 18.25 7.2 21 7.6C18.25 8 16.8 9.45 16.4 12.2C16 9.45 14.55 8 11.8 7.6C14.55 7.2 16 5.75 16.4 3Z", stroke: "currentColor" }],
		["circle", { cx: "7", cy: "5.4", r: "1.1", fill: "currentColor", stroke: "none" }],
	],
});
