/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Maximize = createIcon("Maximize", {
	linear: [
		["path", { d: "M14.75 3.60522C14.75 3.60522 19.60681 3.22531 20.29078 3.90924C20.97468 4.59317 20.59472 9.45 20.59472 9.45M14 10L20 4", stroke: "currentColor" }],
		["path", { d: "M9.25 20.39478C9.25 20.39478 4.39319 20.77469 3.70922 20.09076C3.02532 19.40683 3.40528 14.55 3.40528 14.55M10 14L4 20", stroke: "currentColor" }],
	],
});
