/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Maximize = /* @__PURE__ */ createIcon("Maximize", {
	linear: [
		["path", { d: "M15.025 2.7657C15.025 2.7657 20.3675 2.3478 21.1199 3.1002C21.8721 3.8525 21.4542 9.195 21.4542 9.195M14.31 9.91L21.1201 3.0999", stroke: "currentColor" }],
		["path", { d: "M8.975 21.2343C8.975 21.2343 3.6325 21.6522 2.8801 20.8998C2.1279 20.1475 2.5458 14.805 2.5458 14.805M9.69 14.09L2.8799 20.9001", stroke: "currentColor" }],
	],
});
