/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Menu = /* @__PURE__ */ createIcon("Menu", {
	linear: [
		["path", { d: "M4 7h16M4 12h16M4 17h16", stroke: "currentColor" }],
	],
});
