/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.2 6.5h17.6M3.2 12h17.6M3.2 17.5h17.6", stroke: "currentColor" }],
];

export const Menu = /* @__PURE__ */ createIcon("Menu", {
	linear: nodes,
	bold: nodes,
});
