/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Menu = /* @__PURE__ */ createIcon("Menu", {
	linear: [
		["path", { d: "M3.2 6.5h17.6M3.2 12h17.6M3.2 17.5h17.6", stroke: "currentColor" }],
	],
});
