/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const MicrophoneOff = /* @__PURE__ */ createIcon("MicrophoneOff", {
	linear: [
		["path", { d: "M8.6729 4.006C9.4409 3.0109 10.6454 2.37 12 2.37C14.32 2.37 16.2 4.25 16.2 6.57V10.7425C16.2 10.9907 16.1785 11.2339 16.1372 11.4703M12.9 7H15.9M3.75 9.86V10.75C3.75 15.3064 7.4436 19 12 19C12.7152 19 13.4092 18.909 14.071 18.7379M19.2875 14.6206C19.9019 13.4663 20.25 12.1488 20.25 10.75V9.86M12 19V21.8975M2.4 2.4L21.6 21.6", stroke: "currentColor" }],
	],
});
