/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Microphone = /* @__PURE__ */ createIcon("Microphone", {
	linear: [
		["path", { d: "M7.25 7.75C7.25 5.13 9.38 3 12 3C14.62 3 16.75 5.13 16.75 7.75V10C16.75 12.62 14.62 14.75 12 14.75C9.38 14.75 7.25 12.62 7.25 10V7.75Z M13 7H16.5M13 10.5H16.5 M4.75 10V10.75C4.75 14.75 8 18 12 18C16 18 19.25 14.75 19.25 10.75V10M12 18V21.25", stroke: "currentColor" }],
	],
});
