/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M21.075 9.3543C21.075 9.3543 15.7325 9.7721 14.9802 9.0199C14.2278 8.2675 14.6458 2.925 14.6458 2.925M21.9 2.1L14.9799 9.0201", stroke: "currentColor" }],
	["path", { d: "M2.925 14.6457C2.925 14.6457 8.2675 14.2279 9.0198 14.9801C9.7722 15.7325 9.3542 21.075 9.3542 21.075M2.1 21.9L9.0201 14.9799", stroke: "currentColor" }],
];

export const Minimize = /* @__PURE__ */ createIcon("Minimize", {
	linear: nodes,
	bold: nodes,
});
