/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Minimize = /* @__PURE__ */ createIcon("Minimize", {
	linear: [
		["path", { d: "M20.25 9.59479C20.25 9.59479 15.39316 9.97468 14.70923 9.29078C14.02529 8.60681 14.40526 3.75 14.40526 3.75M21 3L15 9", stroke: "currentColor" }],
		["path", { d: "M3.75 14.40521C3.75 14.40521 8.60684 14.02532 9.29077 14.70922C9.97471 15.39319 9.59474 20.25 9.59474 20.25M3 21L9 15", stroke: "currentColor" }],
	],
});
