/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4 12.9Q3.817 12.9 3.65 12.829Q3.488 12.761 3.364 12.636Q3.239 12.512 3.171 12.35Q3.1 12.183 3.1 12Q3.1 11.817 3.171 11.65Q3.239 11.488 3.364 11.364Q3.488 11.239 3.65 11.171Q3.817 11.1 4 11.1H20Q20.183 11.1 20.35 11.171Q20.512 11.239 20.636 11.364Q20.761 11.488 20.829 11.65Q20.9 11.817 20.9 12Q20.9 12.183 20.829 12.35Q20.761 12.512 20.636 12.636Q20.512 12.761 20.35 12.829Q20.183 12.9 20 12.9Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
];

export const Minus = /* @__PURE__ */ createIcon("Minus", {
	linear: nodes,
	bold: nodes,
});
