/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4.137 4.114H7.28V8.757H4.137ZM16.708 4.114H19.852V8.757H16.708Z", fill: "#FFD700" }],
	["path", { d: "M4.137 7.257H10.424V11.9H4.137ZM13.567 7.257H19.852V11.9H13.567Z", fill: "#FFAF00" }],
	["path", { d: "M4.137 12.044H7.28V18.186H4.137ZM10.424 12.044H13.567V16.686H10.424ZM16.708 12.044H19.852V18.186H16.708Z", fill: "#FA500F" }],
	["path", { d: "M4.137 10.4H19.852V13.544H4.137Z", fill: "#FF8205" }],
	["path", { d: "M1 16.686H10.424V19.829H1ZM13.567 16.686H23V19.829H13.567Z", fill: "#E10500" }],
];

export const MistralColor = /* @__PURE__ */ createIcon("MistralColor", {
	linear: nodes,
	bold: nodes,
});
