/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const MoreVertical = /* @__PURE__ */ createIcon("MoreVertical", {
	linear: [
		["circle", { cx: "12", cy: "6", r: "1.9", fill: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "1.9", fill: "currentColor" }],
		["circle", { cx: "12", cy: "18", r: "1.9", fill: "currentColor" }],
	],
});
