/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const MoreHorizontal = /* @__PURE__ */ createIcon("MoreHorizontal", {
	linear: [
		["circle", { cx: "6", cy: "12", r: "1.9", fill: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "1.9", fill: "currentColor" }],
		["circle", { cx: "18", cy: "12", r: "1.9", fill: "currentColor" }],
	],
});
