/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Mouse = /* @__PURE__ */ createIcon("Mouse", {
	linear: [
		["path", { d: "M5.4 8.92C5.4 5.18 8.37 2.1 12 2.1C15.63 2.1 18.6 5.18 18.6 8.92V15.08C18.6 18.82 15.63 21.9 12 21.9C8.37 21.9 5.4 18.82 5.4 15.08V8.92ZM12 6.28V9.36", stroke: "currentColor" }],
	],
});
