/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Mouse = /* @__PURE__ */ createIcon("Mouse", {
	linear: [
		["path", { d: "M5.4 8.92C5.4 5.18 8.37 2.1 12 2.1C15.63 2.1 18.6 5.18 18.6 8.92V15.08C18.6 18.82 15.63 21.9 12 21.9C8.37 21.9 5.4 18.82 5.4 15.08V8.92ZM12 6.28V9.36", stroke: "currentColor" }],
	],
	bold: [
		["path", { d: "M4.5 8.92Q4.5 5.749 6.692 3.482Q8.898 1.2 12 1.2Q15.102 1.2 17.308 3.482Q19.5 5.749 19.5 8.92V15.08Q19.5 18.251 17.308 20.518Q15.102 22.8 12 22.8Q8.898 22.8 6.692 20.518Q4.5 18.251 4.5 15.08ZM12.9 6.28Q12.9 5.38 12 5.38Q11.1 5.38 11.1 6.28V9.36Q11.1 10.26 12 10.26Q12.9 10.26 12.9 9.36Z", fill: "currentColor" }],
	],
});
