/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Mouse = /* @__PURE__ */ createIcon("Mouse", {
	linear: [
		["path", { d: "M6 9.2C6 5.8 8.7 3 12 3C15.3 3 18 5.8 18 9.2V14.8C18 18.2 15.3 21 12 21C8.7 21 6 18.2 6 14.8V9.2Z M12 6.8V9.6", stroke: "currentColor" }],
	],
});
