/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const MusicNote = /* @__PURE__ */ createIcon("MusicNote", {
	linear: [
		["path", { d: "M2.65 17.775A4.125 4.125 0 1 0 10.9 17.775A4.125 4.125 0 1 0 2.65 17.775ZM10.9 17.775V11.01M10.9 8.26C10.9 7.49 11.285 6.995 12 6.61L19.04 2.76C20.14 2.155 20.8 2.54 20.8 3.75V6.5C20.8 7.27 20.415 7.765 19.7 8.15L12.66 12C11.56 12.605 10.9 12.22 10.9 11.01V8.26Z", stroke: "currentColor" }],
	],
});
