/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Newspaper = /* @__PURE__ */ createIcon("Newspaper", {
	linear: [
		["path", { d: "M17.5 18.5V7C17.5 5.34 16.16 4 14.5 4H6C4.34 4 3 5.34 3 7V16.5C3 18.43 4.57 20 6.5 20H19C19.83 20 20.5 19.33 20.5 18.5V10C20.5 9.17 19.83 8.5 19 8.5H17.5 M17.5 18.5C17.5 19.33 18.17 20 19 20 M6.5 8H14M6.5 12H14M6.5 16H11", stroke: "currentColor" }],
	],
});
