/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Newspaper = /* @__PURE__ */ createIcon("Newspaper", {
	linear: [
		["path", { d: "M18.05 19.15V6.5C18.05 4.674 16.576 3.2 14.75 3.2H5.4C3.574 3.2 2.1 4.674 2.1 6.5V16.95C2.1 19.073 3.827 20.8 5.95 20.8H19.7C20.613 20.8 21.35 20.063 21.35 19.15V9.8C21.35 8.887 20.613 8.15 19.7 8.15H18.05M18.05 19.15C18.05 20.063 18.787 20.8 19.7 20.8M5.95 7.6H14.2M5.95 12H14.2M5.95 16.4H10.9", stroke: "currentColor" }],
	],
});
