/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3 21H12V7.5H16.5V21H21V3H3V21Z", fill: "#CB3837" }],
];

export const NpmColor = /* @__PURE__ */ createIcon("NpmColor", {
	linear: nodes,
	bold: nodes,
});
