/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Npm = createIcon("Npm", {
	linear: [
		["path", { d: "M3 21H12V7.5H16.5V21H21V3H3V21Z", fill: "currentColor" }],
	],
});
