/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 3.2H21.9M11.45 9.03H21.9M11.45 14.97H21.9M2.1 20.8H21.9M5.84 8.7C5.84 8.7 2.54 11.131 2.54 12C2.54 12.869 5.84 15.3 5.84 15.3", stroke: "currentColor" }],
];

export const Outdent = /* @__PURE__ */ createIcon("Outdent", {
	linear: nodes,
	bold: nodes,
});
