/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Outdent = /* @__PURE__ */ createIcon("Outdent", {
	linear: [
		["path", { d: "M3 4H21M11.5 9.3H21M11.5 14.7H21M3 20H21 M6.4 9C6.4 9 3.4 11.21 3.4 12C3.4 12.79 6.4 15 6.4 15", stroke: "currentColor" }],
	],
});
