/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Pen = /* @__PURE__ */ createIcon("Pen", {
	linear: [
		["path", { d: "M13.3649 4.9526L15.1407 3.1769A4.0181 4.0181 0 0 1 20.8231 8.8593L9.1031 20.5794L2 22L3.4206 14.8969L13.3649 4.9526ZM13.3649 4.9526L19.0474 10.6351", stroke: "currentColor" }],
	],
});
