/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Percent = /* @__PURE__ */ createIcon("Percent", {
	linear: [
		["path", { d: "M18.5 5.5L5.5 18.5 M4.7 7A2.3 2.3 0 1 0 9.3 7A2.3 2.3 0 1 0 4.7 7Z M14.7 17A2.3 2.3 0 1 0 19.3 17A2.3 2.3 0 1 0 14.7 17Z", stroke: "currentColor" }],
	],
});
