/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Percent = /* @__PURE__ */ createIcon("Percent", {
	linear: [
		["path", { d: "M19.15 4.85L4.85 19.15M3.97 6.5A2.53 2.53 0 1 0 9.03 6.5A2.53 2.53 0 1 0 3.97 6.5ZM14.97 17.5A2.53 2.53 0 1 0 20.03 17.5A2.53 2.53 0 1 0 14.97 17.5Z", stroke: "currentColor" }],
	],
});
