/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Play = createIcon("Play", {
	linear: [
		["path", { d: "M19.11774 9.61732C21.02745 10.65585 21.02745 13.34415 19.11774 14.38266L7.58696 20.65305C5.73091 21.6624 3.45 20.34867 3.45 18.27039L3.45 5.72961C3.45 3.65131 5.73091 2.33762 7.58695 3.34693L19.11774 9.61732Z", stroke: "currentColor" }],
	],
});
