/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const PlayMini = /* @__PURE__ */ createIcon("PlayMini", {
	linear: [
		["path", { d: "M5.4 12.0002V9.0632C5.4 5.4222 7.985 3.9262 11.142 5.7522L16.224 8.7002C19.381 10.5262 19.381 13.5072 16.224 15.3332L11.142 18.2812C7.985 20.0742 5.4 18.5892 5.4 14.9372V12.0002Z", stroke: "currentColor" }],
	],
});
