/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Play = /* @__PURE__ */ createIcon("Play", {
	linear: [
		["path", { d: "M19.8295 9.3791C21.9302 10.5214 21.9302 13.4786 19.8295 14.6209L7.1457 21.5184C5.104 22.6286 2.595 21.1835 2.595 18.8974L2.595 5.1026C2.595 2.8164 5.104 1.3714 7.1456 2.4816L19.8295 9.3791Z", stroke: "currentColor" }],
	],
	bold: [
		["path", { d: "M20.259 8.588Q22.305 9.701 22.305 12Q22.305 14.299 20.259 15.412L7.576 22.309Q5.602 23.382 3.656 22.261Q1.695 21.132 1.695 18.897L1.695 5.103Q1.695 2.868 3.656 1.739Q5.602 0.618 7.576 1.691Z", fill: "currentColor" }],
	],
});
