/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const PlayMini = /* @__PURE__ */ createIcon("PlayMini", {
	linear: [
		["path", { d: "M6 12.0002V9.33017C6 6.02017 8.35 4.66017 11.22 6.32017L15.84 9.00017C18.71 10.6602 18.71 13.3702 15.84 15.0302L11.22 17.7102C8.35 19.3402 6 17.9902 6 14.6702V12.0002Z", stroke: "currentColor" }],
	],
});
