/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M7.297 17.217A8.2 8.2 0 1 1 16.703 17.217 M8.747 13.753A4.6 4.6 0 1 1 15.253 13.753 M12 14.8V21", stroke: "currentColor" }],
	["circle", { cx: "12", cy: "10.5", r: "1.5", fill: "currentColor", stroke: "none" }],
];

export const Podcast = /* @__PURE__ */ createIcon("Podcast", {
	linear: nodes,
	bold: nodes,
});
