/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Pointer = /* @__PURE__ */ createIcon("Pointer", {
	linear: [
		["path", { d: "M5.0568 3.8875L19.1632 9.1125C20.2775 9.525 20.2885 10.1047 19.1918 10.5612L14.9282 12.3388C13.8315 12.7953 12.7953 13.8315 12.3388 14.9282L10.5612 19.1918C10.1047 20.2885 9.525 20.2775 9.1125 19.1632L3.8875 5.0568C3.475 3.9425 3.9425 3.475 5.0568 3.8875Z", stroke: "currentColor" }],
	],
});
