/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Pointer = /* @__PURE__ */ createIcon("Pointer", {
	linear: [
		["path", { d: "M5.688 4.625L18.512 9.375C19.525 9.75 19.535 10.277 18.538 10.692L14.662 12.308C13.665 12.723 12.723 13.665 12.308 14.662L10.692 18.538C10.277 19.535 9.75 19.525 9.375 18.512L4.625 5.688C4.25 4.675 4.675 4.25 5.688 4.625Z", stroke: "currentColor" }],
	],
});
