/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Power = /* @__PURE__ */ createIcon("Power", {
	linear: [
		["path", { d: "M18.7083 6C20.1334 7.59227 21 9.69494 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 9.69494 3.86656 7.59227 5.29168 6", stroke: "currentColor" }],
		["path", { d: "M12 3V12", stroke: "currentColor" }],
	],
});
