/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M19.3791 5.4C20.9467 7.1515 21.9 9.4644 21.9 12C21.9 17.4677 17.4677 21.9 12 21.9C6.5324 21.9 2.1 17.4677 2.1 12C2.1 9.4644 3.0532 7.1515 4.6208 5.4", stroke: "currentColor" }],
	["path", { d: "M12 2.1V12", stroke: "currentColor" }],
];

export const Power = /* @__PURE__ */ createIcon("Power", {
	linear: nodes,
	bold: nodes,
});
