/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Presentation = /* @__PURE__ */ createIcon("Presentation", {
	linear: [
		["path", { d: "M3 4H21 M4.5 4V12.5C4.5 14.43 6.07 16 8 16H16C17.93 16 19.5 14.43 19.5 12.5V4 M12 16V19 M8.8 21L12 19L15.2 21 M8 12L9.722 10.278C10.189 9.811 10.877 9.726 11.443 10.066L12.057 10.434C12.623 10.774 13.311 10.689 13.778 10.222L16 8", stroke: "currentColor" }],
	],
});
