/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const QuestionMark = /* @__PURE__ */ createIcon("QuestionMark", {
	linear: [
		["path", { d: "M7.49 7.82C7.49 5.18 9.58 3.09 12.11 3.09C14.64 3.09 16.73 5.07 16.73 7.49C16.73 9.25 15.74 10.46 14.42 11.34C13.1 12.22 12.11 13.21 12.11 14.75V15.52", stroke: "currentColor" }],
		["circle", { cx: "12.11", cy: "20.25", r: "1.265", fill: "currentColor", stroke: "none" }],
	],
});
