/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Redo = /* @__PURE__ */ createIcon("Redo", {
	linear: [
		["path", { d: "M20.25 8.7H9.25C5.9086 8.7 3.2 11.4086 3.2 14.75C3.2 18.0914 5.9086 20.8 9.25 20.8H13.1M16.4 4.3C16.4 4.3 20.8 7.5405 20.8 8.7C20.8 9.8595 16.4 13.1 16.4 13.1", stroke: "currentColor" }],
	],
});
