/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4.2038 14.8372A8.296 8.296 0 0 1 18.165 6.4489M13.8199 7.1375C13.8199 7.1375 17.6838 7.1116 18.165 6.4489C18.6472 5.7853 17.4764 2.1039 17.4764 2.1039M19.7962 9.1628C21.1546 12.8949 19.6779 17.0657 16.2735 19.1117C12.869 21.1567 8.4918 20.5024 5.835 17.5511M10.1801 16.8625C10.1801 16.8625 6.3162 16.8884 5.835 17.5511C5.3528 18.2147 6.5236 21.8961 6.5236 21.8961", stroke: "currentColor" }],
];

export const Refresh = /* @__PURE__ */ createIcon("Refresh", {
	linear: nodes,
	bold: nodes,
});
