/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Refresh = /* @__PURE__ */ createIcon("Refresh", {
	linear: [
		["path", { d: "M4.482 14.736A8 8 0 0 1 17.945 6.647 M13.755 7.311C13.755 7.311 17.481 7.286 17.945 6.647C18.41 6.007 17.281 2.457 17.281 2.457 M19.518 9.264C20.828 12.863 19.404 16.885 16.121 18.858C12.838 20.83 8.617 20.199 6.055 17.353 M10.245 16.689C10.245 16.689 6.519 16.714 6.055 17.353C5.59 17.993 6.719 21.543 6.719 21.543", stroke: "currentColor" }],
	],
});
