/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Reorder = /* @__PURE__ */ createIcon("Reorder", {
	linear: [
		["path", { d: "M4.3 5.4h15.4M4.3 9.8h15.4M4.3 14.2h15.4M4.3 18.6h15.4", stroke: "currentColor" }],
	],
});
