/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Reorder = /* @__PURE__ */ createIcon("Reorder", {
	linear: [
		["path", { d: "M5 6h14M5 10h14M5 14h14M5 18h14", stroke: "currentColor" }],
	],
});
