/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M8.6999 14.75c0 0 -4.9499 -3.6457 -4.9499 -4.9501c0 -1.3044 4.95 -4.95 4.95 -4.95M4.1625 9.8h8.3875c3.8891 0 5.8336 0 7.0418 1.2082c1.2082 1.2082 1.2082 3.1528 1.2082 7.0418v0.55", stroke: "currentColor" }],
];

export const Reply = /* @__PURE__ */ createIcon("Reply", {
	linear: nodes,
	bold: nodes,
});
