/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Rewind = /* @__PURE__ */ createIcon("Rewind", {
	linear: [
		["path", { d: "M3.373 10.713C2.342 11.274 2.342 12.726 3.373 13.287L9.6 16.673C10.602 17.217 11.834 16.508 11.834 15.386L11.834 8.614C11.834 7.492 10.602 6.783 9.6 7.327L3.373 10.713Z M12.623 10.713C11.592 11.274 11.592 12.726 12.623 13.287L18.85 16.673C19.852 17.217 21.084 16.508 21.084 15.386L21.084 8.614C21.084 7.492 19.852 6.783 18.85 7.327L12.623 10.713Z", stroke: "currentColor" }],
	],
});
