/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.5 12.5C3.5 16.347 6.084 19.715 9.8 20.711C13.516 21.706 17.438 20.082 19.361 16.75C21.285 13.419 20.731 9.21 18.01 6.49C15.29 3.769 11.082 3.215 7.75 5.139 M11.595 6.932C11.595 6.932 8.02 5.882 7.75 5.139C7.48 4.396 9.543 1.294 9.543 1.294", stroke: "currentColor" }],
];

export const RotateCcw = /* @__PURE__ */ createIcon("RotateCcw", {
	linear: nodes,
	bold: nodes,
});
