/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.5 13.306C3.5 17.153 6.084 20.521 9.8 21.517C13.516 22.512 17.438 20.888 19.361 17.556C21.285 14.225 20.731 10.016 18.01 7.296C15.29 4.575 11.082 4.021 7.75 5.945M11.595 7.738C11.595 7.738 8.02 6.688 7.75 5.945C7.48 5.202 9.543 2.1 9.543 2.1", stroke: "currentColor" }],
];

export const RotateCcw = /* @__PURE__ */ createIcon("RotateCcw", {
	linear: nodes,
	bold: nodes,
});
