/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M20.5 12.5A8.5 8.5 0 1 1 16.25 5.139 M12.405 6.932C12.405 6.932 15.98 5.882 16.25 5.139C16.52 4.396 14.457 1.294 14.457 1.294", stroke: "currentColor" }],
];

export const RotateCw = /* @__PURE__ */ createIcon("RotateCw", {
	linear: nodes,
	bold: nodes,
});
