/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Router = /* @__PURE__ */ createIcon("Router", {
	linear: [
		["path", { d: "M5.9 12H18.1C19.703 12 20.504 12 21.002 12.498C21.5 12.996 21.5 13.797 21.5 15.4V16.4C21.5 18.003 21.5 18.804 21.002 19.302C20.504 19.8 19.703 19.8 18.1 19.8H5.9C4.297 19.8 3.496 19.8 2.998 19.302C2.5 18.804 2.5 18.003 2.5 16.4V15.4C2.5 13.797 2.5 12.996 2.998 12.498C3.496 12 4.297 12 5.9 12Z M14.5 15.9H18 M9.379 7.365A3.2 3.2 0 0 1 14.621 7.365 M6.921 5.644A6.2 6.2 0 0 1 17.079 5.644", stroke: "currentColor" }],
		["circle", { cx: "6.5", cy: "15.9", r: "1.05", fill: "currentColor", stroke: "none" }],
		["circle", { cx: "9.6", cy: "15.9", r: "1.05", fill: "currentColor", stroke: "none" }],
	],
});
