/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Route = /* @__PURE__ */ createIcon("Route", {
	linear: [
		["path", { d: "M3.25 18.5A2.25 2.25 0 1 0 7.75 18.5A2.25 2.25 0 1 0 3.25 18.5Z M16.25 5.5A2.25 2.25 0 1 0 20.75 5.5A2.25 2.25 0 1 0 16.25 5.5Z M7.75 18.5H16.25C18.05 18.5 19.5 17.05 19.5 15.25C19.5 13.45 18.05 12 16.25 12H7.75C5.95 12 4.5 10.55 4.5 8.75C4.5 6.95 5.95 5.5 7.75 5.5H16.25", stroke: "currentColor" }],
	],
});
