/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Rows = /* @__PURE__ */ createIcon("Rows", {
	linear: [
		["path", { d: "M11 3L13 3C16.771 3 18.657 3 19.828 4.172C21 5.343 21 7.229 21 11L21 13C21 16.771 21 18.657 19.828 19.828C18.657 21 16.771 21 13 21L11 21C7.229 21 5.343 21 4.172 19.828C3 18.657 3 16.771 3 13L3 11C3 7.229 3 5.343 4.172 4.172C5.343 3 7.229 3 11 3Z M3.15 12H20.85", stroke: "currentColor" }],
	],
});
