/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Scan = /* @__PURE__ */ createIcon("Scan", {
	linear: [
		["path", { d: "M3.5 8.5V7.5C3.5 5.61 3.5 4.67 4.09 4.09C4.67 3.5 5.61 3.5 7.5 3.5H8.5 M20.5 8.5L20.5 7.5C20.5 5.61 20.5 4.67 19.91 4.09C19.33 3.5 18.39 3.5 16.5 3.5L15.5 3.5 M3.5 15.5L3.5 16.5C3.5 18.39 3.5 19.33 4.09 19.91C4.67 20.5 5.61 20.5 7.5 20.5L8.5 20.5 M20.5 15.5L20.5 16.5C20.5 18.39 20.5 19.33 19.91 19.91C19.33 20.5 18.39 20.5 16.5 20.5L15.5 20.5 M3.5 12H20.5", stroke: "currentColor" }],
	],
});
