/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Search = /* @__PURE__ */ createIcon("Search", {
	linear: [
		["path", { d: "M2.1 11.505A9.405 9.405 0 1 0 20.91 11.505A9.405 9.405 0 1 0 2.1 11.505ZM18.1558 18.1558L21.9 21.9", stroke: "currentColor" }],
	],
});
