/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Search = createIcon("Search", {
	linear: [
		["circle", { cx: "11.55", cy: "11.55", r: "8.55", stroke: "currentColor" }],
		["path", { d: "M17.5962 17.5962L21 21", stroke: "currentColor" }],
	],
});
