/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Send = /* @__PURE__ */ createIcon("Send", {
	linear: [
		["path", { d: "M21.4277 2.6772C19.1582 0.2331 2.0869 6.2202 2.101 8.4061C2.117 10.885 8.7678 11.6475 10.6112 12.1647C11.7198 12.4757 12.0167 12.7945 12.2723 13.957C13.4299 19.2216 14.0112 21.8401 15.3359 21.8986C17.4474 21.9919 23.6426 5.0624 21.4277 2.6772ZM11.4789 12.521L15.1259 8.874", stroke: "currentColor" }],
	],
});
