/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const SendMessage = createIcon("SendMessage", {
	linear: [
		["path", { d: "M12 3H7a4 4 0 0 0-4 4v10a4 4 0 0 0 4 4h10a4 4 0 0 0 4-4v-5", stroke: "currentColor" }],
		["path", { d: "m15.5 4.5 1.25-1.25a2.828427 2.828427 0 0 1 4 4L12.5 15.5l-5 1 1-5 7-7Zm0 0 4 4", stroke: "currentColor" }],
	],
});
