/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SidebarLeft = /* @__PURE__ */ createIcon("SidebarLeft", {
	linear: [
		["path", { d: "M10.5 3h3C16.7 3 18 3 19.5 4.5S21 7.3 21 10.5v3c0 3.2 0 4.5-1.5 6S16.7 21 13.5 21h-3C7.3 21 6 21 4.5 19.5S3 16.7 3 13.5v-3C3 7.3 3 6 4.5 4.5S7.3 3 10.5 3Z", stroke: "currentColor" }],
		["path", { d: "M9.3 3v18", stroke: "currentColor" }],
	],
});
