/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Signal = /* @__PURE__ */ createIcon("Signal", {
	linear: [
		["path", { d: "M4.5 19.5V16.5M9.17 19.5V13.2M13.83 19.5V9.4M18.5 19.5V5", stroke: "currentColor" }],
	],
});
