/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.75 20.25V16.95M8.887 20.25V13.32M14.013 20.25V9.14M19.15 20.25V4.3", stroke: "currentColor" }],
];

export const Signal = /* @__PURE__ */ createIcon("Signal", {
	linear: nodes,
	bold: nodes,
});
