/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SkipBack = /* @__PURE__ */ createIcon("SkipBack", {
	linear: [
		["path", { d: "M9.0509 10.1124C7.5384 10.9352 7.5384 13.0648 9.0509 13.8876L18.1831 18.853C19.6538 19.6527 21.46 18.6121 21.46 16.9665L21.46 7.0335C21.46 5.3879 19.6538 4.3473 18.1831 5.147L9.0509 10.1124ZM3.31 4.52L3.31 19.48", stroke: "currentColor" }],
	],
});
