/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SkipBack = /* @__PURE__ */ createIcon("SkipBack", {
	linear: [
		["path", { d: "M9.319 10.284C7.944 11.032 7.944 12.968 9.319 13.716L17.621 18.23C18.958 18.957 20.6 18.011 20.6 16.515L20.6 7.485C20.6 5.989 18.958 5.043 17.621 5.77L9.319 10.284Z M4.1 5.2L4.1 18.8", stroke: "currentColor" }],
	],
});
