/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Slash = /* @__PURE__ */ createIcon("Slash", {
	linear: [
		["path", { d: "M3.99219 20L19.9922 4", stroke: "currentColor" }],
	],
});
