/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.1914 20.8L20.7914 3.2", stroke: "currentColor" }],
];

export const Slash = /* @__PURE__ */ createIcon("Slash", {
	linear: nodes,
	bold: nodes,
});
