/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SlidersVerticalAlt = /* @__PURE__ */ createIcon("SlidersVerticalAlt", {
	linear: [
		["path", { d: "M7 20V15M7 12V4M4 15H10M17 20V12M17 9V4M14 9H20", stroke: "currentColor" }],
	],
});
