/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M5 20V14M5 11V4M9 8H15M2 14H8M16 12H22M12 8V4M12 20V11M19 12V4M19 20V15", stroke: "currentColor" }],
];

export const SlidersVertical = /* @__PURE__ */ createIcon("SlidersVertical", {
	linear: nodes,
	bold: nodes,
});
