/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4 5H10M13 5H20M16 9V15M10 2V8M12 16V22M16 12H20M4 12H13M12 19H20M4 19H9", stroke: "currentColor" }],
];

export const SlidersHorizontal = /* @__PURE__ */ createIcon("SlidersHorizontal", {
	linear: nodes,
	bold: nodes,
});
