/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4 7H9M12 7H20M9 4V10M4 17H12M15 17H20M15 14V20", stroke: "currentColor" }],
];

export const SlidersHorizontalAlt = /* @__PURE__ */ createIcon("SlidersHorizontalAlt", {
	linear: nodes,
	bold: nodes,
});
