/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Snowflake = /* @__PURE__ */ createIcon("Snowflake", {
	linear: [
		["path", { d: "M12 12L12 21 M12 17.6L10.02 19.58 M12 17.6L13.98 19.58 M12 12L4.206 16.5 M7.15 14.8L4.446 14.075 M7.15 14.8L6.426 17.505 M12 12L4.206 7.5 M7.15 9.2L6.426 6.495 M7.15 9.2L4.446 9.925 M12 12L12 3 M12 6.4L13.98 4.42 M12 6.4L10.02 4.42 M12 12L19.794 7.5 M16.85 9.2L19.554 9.925 M16.85 9.2L17.574 6.495 M12 12L19.794 16.5 M16.85 14.8L17.574 17.505 M16.85 14.8L19.554 14.075", stroke: "currentColor" }],
	],
});
