/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M12 12L12 21.9M12 18.16L9.822 20.338M12 18.16L14.178 20.338M12 12L3.4266 16.95M6.665 15.08L3.6906 14.2825M6.665 15.08L5.8686 18.0555M12 12L3.4266 7.05M6.665 8.92L5.8686 5.9445M6.665 8.92L3.6906 9.7175M12 12L12 2.1M12 5.84L14.178 3.662M12 5.84L9.822 3.662M12 12L20.5734 7.05M17.335 8.92L20.3094 9.7175M17.335 8.92L18.1314 5.9445M12 12L20.5734 16.95M17.335 15.08L18.1314 18.0555M17.335 15.08L20.3094 14.2825", stroke: "currentColor" }],
];

export const Snowflake = /* @__PURE__ */ createIcon("Snowflake", {
	linear: nodes,
	bold: nodes,
});
