/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SortAscending = /* @__PURE__ */ createIcon("SortAscending", {
	linear: [
		["path", { d: "M7 19.5V5 M10.5 8C10.5 8 7.922 4.5 7 4.5C6.078 4.5 3.5 8 3.5 8 M12.5 7H15.5 M12.5 12H18.5 M12.5 17H21", stroke: "currentColor" }],
	],
});
