/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SortDescending = /* @__PURE__ */ createIcon("SortDescending", {
	linear: [
		["path", { d: "M7 4.5V19 M3.5 16C3.5 16 6.078 19.5 7 19.5C7.922 19.5 10.5 16 10.5 16 M12.5 7H21 M12.5 12H18.5 M12.5 17H15.5", stroke: "currentColor" }],
	],
});
