/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SortDescending = /* @__PURE__ */ createIcon("SortDescending", {
	linear: [
		["path", { d: "M6.5 3.75V19.7M2.65 16.4C2.65 16.4 5.4858 20.25 6.5 20.25C7.5142 20.25 10.35 16.4 10.35 16.4M12.55 6.5H21.9M12.55 12H19.15M12.55 17.5H15.85", stroke: "currentColor" }],
	],
});
