/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M6.5 20.25V4.3M10.35 7.6C10.35 7.6 7.5142 3.75 6.5 3.75C5.4858 3.75 2.65 7.6 2.65 7.6M12.55 6.5H15.85M12.55 12H19.15M12.55 17.5H21.9", stroke: "currentColor" }],
];

export const SortAscending = /* @__PURE__ */ createIcon("SortAscending", {
	linear: nodes,
	bold: nodes,
});
