/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Soundwave = /* @__PURE__ */ createIcon("Soundwave", {
	linear: [
		["path", { d: "M4 11v2M8 7v10M12 4v16M16 7v10M20 11v2", stroke: "currentColor" }],
	],
});
