/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Soundwave = /* @__PURE__ */ createIcon("Soundwave", {
	linear: [
		["path", { d: "M3.2 10.9v2.2M7.6 6.5v11M12 3.2v17.6M16.4 6.5v11M20.8 10.9v2.2", stroke: "currentColor" }],
	],
});
