/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const SpinnerLarge = createIcon("SpinnerLarge", {
	linear: [
		["style", { children: "@keyframes honeyicons-spinner-large-rotate { to { transform: rotate(360deg); } }\n    [data-honeyicons-spinner-large] { transform-origin: 12px 12px; animation: honeyicons-spinner-large-rotate 0.8s linear infinite; }\n    @media (prefers-reduced-motion: reduce) { [data-honeyicons-spinner-large] { animation: none; } }" }],
		["circle", { cx: "12", cy: "12", r: "8.125", stroke: "currentColor", strokeWidth: "1.75", opacity: "0.15" }],
		["path", { d: "M20.125 12a8.125 8.125 0 1 1-8.125-8.125", stroke: "currentColor", strokeWidth: "1.75", "data-honeyicons-spinner-large": "" }],
	],
});
