/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SquarePen = /* @__PURE__ */ createIcon("SquarePen", {
	linear: [
		["path", { d: "M11.6918 2.7165H6.363a4.263 4.263 0 0 0 -4.263 4.263v10.6575a4.263 4.263 0 0 0 4.263 4.263h10.6575a4.263 4.263 0 0 0 4.263 -4.263v-5.3288", stroke: "currentColor" }],
		["path", { d: "M15.4219 4.3151l1.3322 -1.3322a3.0144 3.0144 0 0 1 4.263 4.263L12.2246 16.0384l-5.3288 1.0657 1.0657 -5.3288 7.4603 -7.4603Zm0 0l4.263 4.263", stroke: "currentColor" }],
	],
});
