/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Stop = /* @__PURE__ */ createIcon("Stop", {
	linear: [
		["path", { d: "M3 12C3 7.75735 3 5.63604 4.31802 4.31802C5.63604 3 7.75735 3 12 3C16.2426 3 18.36399 3 19.68195 4.31802C21 5.63604 21 7.75735 21 12C21 16.2426 21 18.36399 19.68195 19.68195C18.36399 21 16.2426 21 12 21C7.75735 21 5.63604 21 4.31802 19.68195C3 18.36399 3 16.2426 3 12Z", stroke: "currentColor" }],
	],
});
