/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Stopwatch = /* @__PURE__ */ createIcon("Stopwatch", {
	linear: [
		["path", { d: "M3.5 13.5A8.5 8.5 0 1 0 20.5 13.5A8.5 8.5 0 1 0 3.5 13.5Z M18.0104 7.4896L19.5 6M14.5 2H9.5M12 13.5L15.5 10", stroke: "currentColor" }],
	],
});
