/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Stopwatch = /* @__PURE__ */ createIcon("Stopwatch", {
	linear: [
		["circle", { cx: "12", cy: "13.5", r: "8.5", stroke: "currentColor" }],
		["path", { d: "M18.0104 7.4896L19.5 6M14.5 2H9.5M12 13.5L15.5 10", stroke: "currentColor" }],
	],
});
