/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.1914 12H20.7914M18.0414 7.2333C18.0414 4.3983 15.3328 2.1 11.9914 2.1C8.6501 2.1 5.9414 4.3983 5.9414 7.2333C5.9414 7.7681 6.0001 8.2576 6.1249 8.7M5.3914 16.7666C5.3914 19.6018 8.3463 21.9 11.9914 21.9C15.6365 21.9 18.5914 20.4334 18.5914 16.7666C18.5914 14.1344 17.4577 12.636 15.1901 12", stroke: "currentColor" }],
];

export const Strikethrough = /* @__PURE__ */ createIcon("Strikethrough", {
	linear: nodes,
	bold: nodes,
});
