/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const SunMoon = /* @__PURE__ */ createIcon("SunMoon", {
	linear: [
		["path", { d: "M10.435 5.02A8 8 0 1 0 18.98 13.565A6.4 6.4 0 0 1 10.435 5.02Z M17.2 3.8V2.3M19.32 4.68L20.38 3.62M20.2 6.8H21.7", stroke: "currentColor" }],
	],
});
