/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Supabase = /* @__PURE__ */ createIcon("Supabase", {
	bold: [
		["path", { d: "M13.6849 21.9296C13.1601 22.5905 12.096 22.2284 12.0833 21.3845L11.987 14.9574L3.7998 14.9574C2.2965 14.9574 1.4582 13.2212 2.3929 12.044L10.3124 2.0698C10.8372 1.4089 11.9013 1.771 11.914 2.6149L11.9562 9.042L20.1975 9.042C21.7007 9.042 22.5391 10.7782 21.6044 11.9554Z", fill: "currentColor" }],
	],
});
