/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Superscript = /* @__PURE__ */ createIcon("Superscript", {
	linear: [
		["path", { d: "M3.5 8.5L12.5 19.5M12.5 8.5L3.5 19.5 M16.3 5.1C16.5 4.4 17.2 3.9 18 3.9C19 3.9 19.8 4.6 19.8 5.6C19.8 7.1 16.3 8.2 16.3 9.9H19.8", stroke: "currentColor" }],
	],
});
