/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Tag = /* @__PURE__ */ createIcon("Tag", {
	linear: [
		["path", { d: "M5.9 3.5L9.4 3.5C10.84 3.5 12.479 4.179 13.497 5.197L18.803 10.503C19.821 11.521 19.821 12.879 18.803 13.897L13.897 18.803C12.879 19.821 11.521 19.821 10.503 18.803L5.197 13.497C4.179 12.479 3.5 10.84 3.5 9.4L3.5 5.9C3.5 4.46 4.46 3.5 5.9 3.5Z", stroke: "currentColor" }],
		["circle", { cx: "8", cy: "8", r: "1.4", fill: "currentColor", stroke: "none" }],
	],
});
