/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Tag = /* @__PURE__ */ createIcon("Tag", {
	linear: [
		["path", { d: "M5.29 2.65L9.14 2.65C10.724 2.65 12.5269 3.3969 13.6467 4.5167L19.4833 10.3533C20.6031 11.4731 20.6031 12.9669 19.4833 14.0867L14.0867 19.4833C12.9669 20.6031 11.4731 20.6031 10.3533 19.4833L4.5167 13.6467C3.3969 12.5269 2.65 10.724 2.65 9.14L2.65 5.29C2.65 3.706 3.706 2.65 5.29 2.65Z", stroke: "currentColor" }],
		["circle", { cx: "7.6", cy: "7.6", r: "1.54", fill: "currentColor", stroke: "none" }],
	],
});
