/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Target = /* @__PURE__ */ createIcon("Target", {
	linear: [
		["path", { d: "M3 12A9 9 0 1 0 21 12A9 9 0 1 0 3 12Z M7 12A5 5 0 1 0 17 12A5 5 0 1 0 7 12Z", stroke: "currentColor" }],
		["circle", { cx: "12", cy: "12", r: "1.6", fill: "currentColor", stroke: "none" }],
	],
});
