/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.75 5.95C3.75 5.95 9.8 10.405 9.8 12C9.8 13.595 3.75 18.05 3.75 18.05", stroke: "currentColor" }],
	["path", { d: "M13.1 18.05H20.25", stroke: "currentColor" }],
];

export const Terminal = /* @__PURE__ */ createIcon("Terminal", {
	linear: nodes,
	bold: nodes,
});
