/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Terminal = /* @__PURE__ */ createIcon("Terminal", {
	linear: [
		["path", { d: "M4.5 6.5C4.5 6.5 10 10.55 10 12C10 13.45 4.5 17.5 4.5 17.5", stroke: "currentColor" }],
		["path", { d: "M13 17.5H19.5", stroke: "currentColor" }],
	],
});
