/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignJustifyLeft = /* @__PURE__ */ createIcon("TextAlignJustifyLeft", {
	linear: [
		["path", { d: "M3 3H11M3 9H11M3 15H21M3 21H21", stroke: "currentColor" }],
	],
});
