/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextUnderline = /* @__PURE__ */ createIcon("TextUnderline", {
	linear: [
		["path", { d: "M5.5 3V11.5C5.5 15.0899 8.41015 18 12 18C15.5899 18 18.5 15.0899 18.5 11.5V3", stroke: "currentColor" }],
		["path", { d: "M3 21H21", stroke: "currentColor" }],
	],
});
