/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextSize = /* @__PURE__ */ createIcon("TextSize", {
	linear: [
		["path", { d: "M2.8 19L7.3 7.4C7.6 6.7 8.1 6.3 8.75 6.3C9.4 6.3 9.9 6.7 10.2 7.4L14.7 19 M4.6 14.8H12.9 M14.6 19L17.1 12.6C17.3 12.1 17.6 11.8 18.05 11.8C18.5 11.8 18.8 12.1 19 12.6L21.5 19 M15.6 16.7H20.5", stroke: "currentColor" }],
	],
});
