/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextSize = /* @__PURE__ */ createIcon("TextSize", {
	linear: [
		["path", { d: "M2.4044 19.301L7.0979 7.2022C7.4108 6.4721 7.9323 6.0549 8.6103 6.0549C9.2882 6.0549 9.8097 6.4721 10.1226 7.2022L14.8161 19.301M4.2818 14.9204H12.9387M14.7118 19.301L17.3193 12.6258C17.5279 12.1043 17.8408 11.7914 18.3102 11.7914C18.7795 11.7914 19.0924 12.1043 19.301 12.6258L21.9085 19.301M15.7548 16.9021H20.8655", stroke: "currentColor" }],
	],
});
