/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignJustifyLeft = /* @__PURE__ */ createIcon("TextAlignJustifyLeft", {
	linear: [
		["path", { d: "M2.1 2.1H10.9M2.1 8.7H10.9M2.1 15.3H21.9M2.1 21.9H21.9", stroke: "currentColor" }],
	],
});
