/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignJustifyRight = /* @__PURE__ */ createIcon("TextAlignJustifyRight", {
	linear: [
		["path", { d: "M13 3H21M13 9H21M3 15H21M3 21H21", stroke: "currentColor" }],
	],
});
