/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignLeft = /* @__PURE__ */ createIcon("TextAlignLeft", {
	linear: [
		["path", { d: "M3 3H21M3 9H11M3 15H21M3 21H11", stroke: "currentColor" }],
	],
});
