/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.1 2.1H21.9M7.6 8.7H16.4M2.1 15.3H21.9M7.6 21.9H16.4", stroke: "currentColor" }],
];

export const TextAlignCenter = /* @__PURE__ */ createIcon("TextAlignCenter", {
	linear: nodes,
	bold: nodes,
});
