/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextUnderline = /* @__PURE__ */ createIcon("TextUnderline", {
	linear: [
		["path", { d: "M4.85 2.1V11.45C4.85 15.3989 8.0512 18.6 12 18.6C15.9489 18.6 19.15 15.3989 19.15 11.45V2.1", stroke: "currentColor" }],
		["path", { d: "M2.1 21.9H21.9", stroke: "currentColor" }],
	],
});
