/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignRight = /* @__PURE__ */ createIcon("TextAlignRight", {
	linear: [
		["path", { d: "M3 3H21M13 9H21M3 15H21M13 21H21", stroke: "currentColor" }],
	],
});
