/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TextAlignCenter = /* @__PURE__ */ createIcon("TextAlignCenter", {
	linear: [
		["path", { d: "M3 3H21M8 9H16M3 15H21M8 21H16", stroke: "currentColor" }],
	],
});
