/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Toggle = /* @__PURE__ */ createIcon("Toggle", {
	linear: [
		["path", { d: "M8 6.5H16C19.04 6.5 21.5 8.96 21.5 12C21.5 15.04 19.04 17.5 16 17.5H8C4.96 17.5 2.5 15.04 2.5 12C2.5 8.96 4.96 6.5 8 6.5Z", stroke: "currentColor" }],
		["circle", { cx: "16", cy: "12", r: "2.6", fill: "currentColor", stroke: "none" }],
	],
});
