/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M16.95 3.75V20.8M7.05 20.25V3.2M21.35 7.6C21.35 7.6 18.1095 3.2 16.95 3.2C15.7905 3.2 12.55 7.6 12.55 7.6M11.45 16.4C11.45 16.4 8.2095 20.8 7.05 20.8C5.8905 20.8 2.65 16.4 2.65 16.4", stroke: "currentColor" }],
];

export const TransferVertical = /* @__PURE__ */ createIcon("TransferVertical", {
	linear: nodes,
	bold: nodes,
});
