/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.75 7.05H20.8M20.25 16.95H3.2M7.6 2.65C7.6 2.65 3.2 5.8905 3.2 7.05C3.2 8.2095 7.6 11.45 7.6 11.45M16.4 12.55C16.4 12.55 20.8 15.7905 20.8 16.95C20.8 18.1095 16.4 21.35 16.4 21.35", stroke: "currentColor" }],
];

export const TransferHorizontal = /* @__PURE__ */ createIcon("TransferHorizontal", {
	linear: nodes,
	bold: nodes,
});
