/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TransferHorizontal = /* @__PURE__ */ createIcon("TransferHorizontal", {
	linear: [
		["path", { d: "M4.5 7.5H20M19.5 16.5H4 M8 3.5C8 3.5 4 6.4459 4 7.5C4 8.5541 8 11.5 8 11.5 M16 12.5C16 12.5 20 15.4459 20 16.5C20 17.5541 16 20.5 16 20.5", stroke: "currentColor" }],
	],
});
