/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Trash = createIcon("Trash", {
	linear: [
		["path", { d: "M9 6V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v1M3.5 6h17", stroke: "currentColor" }],
		["path", { d: "m5 9 .8 9.3C5.95 20.1 6.9 21 8.7 21h6.6c1.8 0 2.75-.9 2.9-2.7L19 9M9.5 10.5l.5 6M14.5 10.5l-.5 6", stroke: "currentColor" }],
	],
});
