/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TrendingDown = /* @__PURE__ */ createIcon("TrendingDown", {
	linear: [
		["path", { d: "M3 6.5L7.369 10.869C8.047 11.547 8.953 11.547 9.631 10.869L11.369 9.131C12.047 8.453 12.953 8.453 13.631 9.131L20.4 15.9 M21 11.55C21 11.55 21.652 15.848 21 16.5C20.348 17.152 16.05 16.5 16.05 16.5", stroke: "currentColor" }],
	],
});
