/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.406 6.137L7.0634 10.7944C7.7861 11.5171 8.7519 11.5171 9.4746 10.7944L11.3274 8.9416C12.0501 8.2189 13.0159 8.2189 13.7386 8.9416L20.9544 16.1574M21.594 11.5203C21.594 11.5203 22.289 16.102 21.594 16.797C20.899 17.492 16.3173 16.797 16.3173 16.797", stroke: "currentColor" }],
];

export const TrendingDown = /* @__PURE__ */ createIcon("TrendingDown", {
	linear: nodes,
	bold: nodes,
});
