/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TrendingUp = /* @__PURE__ */ createIcon("TrendingUp", {
	linear: [
		["path", { d: "M3 17.5L7.369 13.131C8.047 12.453 8.953 12.453 9.631 13.131L11.369 14.869C12.047 15.547 12.953 15.547 13.631 14.869L20.4 8.1 M21 12.45C21 12.45 21.652 8.152 21 7.5C20.348 6.848 16.05 7.5 16.05 7.5", stroke: "currentColor" }],
	],
});
