/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const TrendingUp = /* @__PURE__ */ createIcon("TrendingUp", {
	linear: [
		["path", { d: "M2.406 17.863L7.0634 13.2056C7.7861 12.4829 8.7519 12.4829 9.4746 13.2056L11.3274 15.0584C12.0501 15.7811 13.0159 15.7811 13.7386 15.0584L20.9544 7.8426M21.594 12.4797C21.594 12.4797 22.289 7.898 21.594 7.203C20.899 6.508 16.3173 7.203 16.3173 7.203", stroke: "currentColor" }],
	],
});
