/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Trophy = /* @__PURE__ */ createIcon("Trophy", {
	linear: [
		["path", { d: "M6.5 3.75H17.5V9.8C17.5 12.836 15.036 15.3 12 15.3C8.964 15.3 6.5 12.836 6.5 9.8V3.75ZM6.5 5.95H5.18C3.783 5.95 2.65 7.083 2.65 8.48C2.65 10.504 4.19 12.22 6.28 12.44M17.5 5.95H18.82C20.217 5.95 21.35 7.083 21.35 8.48C21.35 10.504 19.81 12.22 17.72 12.44M12 15.3V19.7M7.6 21.35H16.4", stroke: "currentColor" }],
	],
});
