/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Trophy = /* @__PURE__ */ createIcon("Trophy", {
	linear: [
		["path", { d: "M7 4.5H17V10C17 12.76 14.76 15 12 15C9.24 15 7 12.76 7 10V4.5Z M7 6.5H5.8C4.53 6.5 3.5 7.53 3.5 8.8C3.5 10.64 4.9 12.2 6.8 12.4 M17 6.5H18.2C19.47 6.5 20.5 7.53 20.5 8.8C20.5 10.64 19.1 12.2 17.2 12.4 M12 15V19 M8 20.5H16", stroke: "currentColor" }],
	],
});
