/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Tv = /* @__PURE__ */ createIcon("Tv", {
	linear: [
		["path", { d: "M6.7 6.8H17.3C19.28 6.8 20.27 6.8 20.885 7.415C21.5 8.03 21.5 9.02 21.5 11V16.3C21.5 18.28 21.5 19.27 20.885 19.885C20.27 20.5 19.28 20.5 17.3 20.5H6.7C4.72 20.5 3.73 20.5 3.115 19.885C2.5 19.27 2.5 18.28 2.5 16.3V11C2.5 9.02 2.5 8.03 3.115 7.415C3.73 6.8 4.72 6.8 6.7 6.8Z M8.5 2.8L11.3 5.6C11.7 6 12.3 6 12.7 5.6L15.5 2.8", stroke: "currentColor" }],
	],
});
