/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M4.3 6.5V5.4C4.3 4.19 5.29 3.2 6.5 3.2H17.5C18.71 3.2 19.7 4.19 19.7 5.4V6.5M12 3.2V20.8M9.25 20.8H14.75", stroke: "currentColor" }],
];

export const Type = /* @__PURE__ */ createIcon("Type", {
	linear: nodes,
	bold: nodes,
});
