/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Type = /* @__PURE__ */ createIcon("Type", {
	linear: [
		["path", { d: "M5 7V6C5 4.9 5.9 4 7 4H17C18.1 4 19 4.9 19 6V7 M12 4V20 M9.5 20H14.5", stroke: "currentColor" }],
	],
});
