/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M3.75 8.7H14.75C18.0914 8.7 20.8 11.4086 20.8 14.75C20.8 18.0914 18.0914 20.8 14.75 20.8H10.9M7.6 4.3C7.6 4.3 3.2 7.5405 3.2 8.7C3.2 9.8595 7.6 13.1 7.6 13.1", stroke: "currentColor" }],
];

export const Undo = /* @__PURE__ */ createIcon("Undo", {
	linear: nodes,
	bold: nodes,
});
