/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const Undo = createIcon("Undo", {
	linear: [
		["path", { d: "M4.5 9H14.5C17.5376 9 20 11.4624 20 14.5C20 17.5376 17.5376 20 14.5 20H11", stroke: "currentColor" }],
		["path", { d: "M8 5C8 5 4 7.94593 4 9C4 10.05413 8 13 8 13", stroke: "currentColor" }],
	],
});
