/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M18.6 19.7C18.6 19.7 13.7392 14.2 12 14.2C10.2607 14.2 5.4 19.7 5.4 19.7", stroke: "currentColor" }],
	["path", { d: "M18.6 4.3C18.6 4.3 13.7392 9.8 12 9.8C10.2607 9.8 5.4 4.3 5.4 4.3", stroke: "currentColor" }],
];

export const UnfoldLess = /* @__PURE__ */ createIcon("UnfoldLess", {
	linear: nodes,
	bold: nodes,
});
