/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M18.6 14.2C18.6 14.2 13.7392 19.7 12 19.7C10.2607 19.7 5.4 14.2 5.4 14.2", stroke: "currentColor" }],
	["path", { d: "M18.6 9.8C18.6 9.8 13.7392 4.3 12 4.3C10.2607 4.3 5.4 9.8 5.4 9.8", stroke: "currentColor" }],
];

export const UnfoldMore = /* @__PURE__ */ createIcon("UnfoldMore", {
	linear: nodes,
	bold: nodes,
});
