/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const UnfoldMore = createIcon("UnfoldMore", {
	linear: [
		["path", { d: "M18 14C18 14 13.5811 19 12 19C10.4188 19 6 14 6 14", stroke: "currentColor" }],
		["path", { d: "M18 9.99996C18 9.99996 13.5811 5.00001 12 5C10.4188 4.99999 6 10 6 10", stroke: "currentColor" }],
	],
});
