/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Usb = /* @__PURE__ */ createIcon("Usb", {
	linear: [
		["path", { d: "M12 21V3.6 M14.8 5.9C14.8 5.9 12.737 3.1 12 3.1C11.263 3.1 9.2 5.9 9.2 5.9 M12 17L8.4 14.75C7.6 14.25 7.2 13.5 7.2 12.65V11.4 M12 13.8L15.6 11.55C16.4 11.05 16.9 10.3 16.9 9.45V9.1 M7.2 9.7A0.9 0.9 0 1 1 7.2 11.5A0.9 0.9 0 1 1 7.2 9.7Z M16 7.3H17.8V9.1H16Z", stroke: "currentColor" }],
	],
});
