/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const User = /* @__PURE__ */ createIcon("User", {
	linear: [
		["path", { d: "M7.9 6.4A4.1 4.1 0 0 1 16.1 6.4A4.1 4.1 0 0 1 7.9 6.4ZM9.7 6.4A2.3 2.3 0 0 0 14.3 6.4A2.3 2.3 0 0 0 9.7 6.4Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M6.717 13.209A10 10 0 0 1 17.283 13.209A4.7 4.7 0 0 1 14.8 21.9H9.2A4.7 4.7 0 0 1 6.717 13.209ZM7.668 14.738A2.9 2.9 0 0 0 9.2 20.1H14.8A2.9 2.9 0 0 0 16.332 14.738A8.2 8.2 0 0 0 7.668 14.738Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
	],
});
