/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const UserRemove = /* @__PURE__ */ createIcon("UserRemove", {
	linear: [
		["path", { d: "M4.9 6.4A4.1 4.1 0 0 1 13.1 6.4A4.1 4.1 0 0 1 4.9 6.4ZM6.7 6.4A2.3 2.3 0 0 0 11.3 6.4A2.3 2.3 0 0 0 6.7 6.4Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M12.9 21.9L6.2 21.9A4.7 4.7 0 0 1 3.717 13.209A10 10 0 0 1 13.286 12.665A0.9 0.9 0 0 1 12.514 14.291A8.2 8.2 0 0 0 4.668 14.738A2.9 2.9 0 0 0 6.2 20.1L12.9 20.1A0.9 0.9 0 0 1 12.9 21.9Z", fill: "currentColor" }],
		["path", { d: "M16.5 19.4L21.5 19.4A0.9 0.9 0 0 0 21.5 17.6L16.5 17.6A0.9 0.9 0 0 0 16.5 19.4Z", fill: "currentColor" }],
	],
	bold: [
		["path", { d: "M4.9 6.4A4.1 4.1 0 0 1 13.1 6.4A4.1 4.1 0 0 1 4.9 6.4ZM12.9 21.9H6.2A4.7 4.7 0 0 1 3.717 13.209A10 10 0 0 1 13.286 12.665A0.9 0.9 0 0 1 13.8 13.478V21A0.9 0.9 0 0 1 12.9 21.9ZM16.5 19.4L21.5 19.4A0.9 0.9 0 0 0 21.5 17.6L16.5 17.6A0.9 0.9 0 0 0 16.5 19.4Z", fill: "currentColor" }],
	],
});
