/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const UserRemove = /* @__PURE__ */ createIcon("UserRemove", {
	linear: [
		["path", { d: "M5.1,6c0,2.7062 2.1938,4.9 4.9,4.9c2.7062,0 4.9,-2.1938 4.9,-4.9c0,-2.7062 -2.1938,-4.9 -4.9,-4.9c-2.7062,0 -4.9,2.1938 -4.9,4.9zM6.9,6c0,-1.71208 1.38792,-3.1 3.1,-3.1c1.71208,0 3.1,1.38792 3.1,3.1c0,1.71208 -1.38792,3.1 -3.1,3.1c-1.71208,0 -3.1,-1.38792 -3.1,-3.1z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M10,12.1c-4.9,0 -8.9,2.28 -8.9,5.4c0,2.92 0.55,5.4 8.9,5.4c8.35,0 8.9,-2.48 8.9,-5.4c0,-3.12 -4,-5.4 -8.9,-5.4zM10,13.9c4.13,0 7.1,1.78 7.1,3.6c0,2.26 0,3.6 -7.1,3.6c-7.1,0 -7.1,-1.34 -7.1,-3.6c0,-1.82 2.97,-3.6 7.1,-3.6z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M17 9.9L22 9.9A0.9 0.9 0 0 0 22 8.1L17 8.1A0.9 0.9 0 0 0 17 9.9Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
	],
});
