/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const UserRemove = /* @__PURE__ */ createIcon("UserRemove", {
	linear: [
		["path", { d: "M5.9 6.4A4.1 4.1 0 0 1 14.1 6.4A4.1 4.1 0 0 1 5.9 6.4ZM7.7 6.4A2.3 2.3 0 0 0 12.3 6.4A2.3 2.3 0 0 0 7.7 6.4Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M4.717 13.209A10 10 0 0 1 15.283 13.209A4.7 4.7 0 0 1 12.8 21.9H7.2A4.7 4.7 0 0 1 4.717 13.209ZM5.668 14.738A2.9 2.9 0 0 0 7.2 20.1H12.8A2.9 2.9 0 0 0 14.332 14.738A8.2 8.2 0 0 0 5.668 14.738Z", fill: "currentColor", fillRule: "evenodd", clipRule: "evenodd" }],
		["path", { d: "M16.5 9.9L21.5 9.9A0.9 0.9 0 0 0 21.5 8.1L16.5 8.1A0.9 0.9 0 0 0 16.5 9.9Z", fill: "currentColor" }],
	],
});
