/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M7.05 3.2C4.52 5.73 3.53 8.7 3.53 12C3.53 15.3 4.52 18.27 7.05 20.8M16.95 3.2C19.48 5.73 20.47 8.7 20.47 12C20.47 15.3 19.48 18.27 16.95 20.8M9.25 8.7L14.75 15.3M14.75 8.7L9.25 15.3", stroke: "currentColor" }],
];

export const Variable = /* @__PURE__ */ createIcon("Variable", {
	linear: nodes,
	bold: nodes,
});
