/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M11.8632 2.17999L22.7264 20.9958H1L11.8632 2.17999Z", fill: "currentColor" }],
];

export const Vercel = /* @__PURE__ */ createIcon("Vercel", {
	linear: nodes,
	bold: nodes,
});
