/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const VideoCamera = createIcon("VideoCamera", {
	linear: [
		["path", { d: "M9 5H8C5.17157 5 3.75736 5 2.87868 5.87868C2 6.75736 2 8.17157 2 11V13C2 15.8284 2 17.2426 2.87868 18.1213C3.75736 19 5.17157 19 8 19H9C11.8284 19 13.2426 19 14.1213 18.1213C15 17.2426 15 15.8284 15 13V11C15 8.17157 15 6.75736 14.1213 5.87868C13.2426 5 11.8284 5 9 5Z", stroke: "currentColor" }],
		["path", { d: "M15 9.5L18.8625 6.6031C20.4175 5.4369 21.195 4.8538 21.5975 5.0551C22 5.2563 22 6.2282 22 8.1719V15.8281C22 17.7718 22 18.7437 21.5975 18.9449C21.195 19.1462 20.4175 18.5631 18.8625 17.3969L15 14.5", stroke: "currentColor" }],
	],
});

/** @deprecated Use VideoCamera instead. */
export const Videocamera = VideoCamera;
