/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Webcam = /* @__PURE__ */ createIcon("Webcam", {
	linear: [
		["path", { d: "M4.8 10A7.2 7.2 0 1 0 19.2 10A7.2 7.2 0 1 0 4.8 10Z M9.5 10A2.5 2.5 0 1 0 14.5 10A2.5 2.5 0 1 0 9.5 10Z M12 17.2V20.8 M8.5 20.8H15.5", stroke: "currentColor" }],
	],
});
