/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Webcam = /* @__PURE__ */ createIcon("Webcam", {
	linear: [
		["path", { d: "M4.2528 9.848A7.7472 7.7472 0 1 0 19.7472 9.848A7.7472 7.7472 0 1 0 4.2528 9.848ZM9.31 9.848A2.69 2.69 0 1 0 14.69 9.848A2.69 2.69 0 1 0 9.31 9.848ZM12 17.5952V21.4688M8.234 21.4688H15.766", stroke: "currentColor" }],
	],
});
