/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M12 5.95L16.3923 13.5565A3.41 3.41 0 1 0 21.0497 14.805M18.0973 16.51L9.3127 16.51A3.41 3.41 0 1 0 5.9027 19.92M5.9027 16.51L10.295 8.9035A3.41 3.41 0 1 0 9.0465 4.245", stroke: "currentColor" }],
];

export const Webhook = /* @__PURE__ */ createIcon("Webhook", {
	linear: nodes,
	bold: nodes,
});
