/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const WidgetAdd = /* @__PURE__ */ createIcon("WidgetAdd", {
	linear: [
		["circle", { cx: "6.225", cy: "6.225", r: "3.74", stroke: "currentColor" }],
		["path", { d: "M17.775 2.925V9.525M14.475 6.225H21.075", stroke: "currentColor" }],
		["circle", { cx: "6.225", cy: "17.775", r: "3.74", stroke: "currentColor" }],
		["circle", { cx: "17.775", cy: "17.775", r: "3.74", stroke: "currentColor" }],
	],
});
