/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const WidgetAdd = /* @__PURE__ */ createIcon("WidgetAdd", {
	linear: [
		["circle", { cx: "6.75", cy: "6.75", r: "3.4", stroke: "currentColor" }],
		["path", { d: "M17.25 3.75V9.75M14.25 6.75H20.25", stroke: "currentColor" }],
		["circle", { cx: "6.75", cy: "17.25", r: "3.4", stroke: "currentColor" }],
		["circle", { cx: "17.25", cy: "17.25", r: "3.4", stroke: "currentColor" }],
	],
});
