/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Widget = /* @__PURE__ */ createIcon("Widget", {
	linear: [
		["circle", { cx: "6.225", cy: "6.225", r: "3.74", stroke: "currentColor" }],
		["circle", { cx: "17.775", cy: "6.225", r: "3.74", stroke: "currentColor" }],
		["circle", { cx: "6.225", cy: "17.775", r: "3.74", stroke: "currentColor" }],
		["circle", { cx: "17.775", cy: "17.775", r: "3.74", stroke: "currentColor" }],
	],
});
