/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";
import type { IconNode } from "../types.js";

const nodes: IconNode = [
	["path", { d: "M2.622 8.874H13.563C15.2927 8.874 16.689 7.4777 16.689 5.748C16.689 4.31 15.522 3.143 14.084 3.143C12.9378 3.143 12 3.8724 11.7395 4.9144M2.622 12.521H18.252C20.2631 12.521 21.899 14.1569 21.899 16.168C21.899 17.8977 20.5027 19.294 18.773 19.294C17.5226 19.294 16.4806 18.5646 16.2201 17.4184M2.622 16.168H11.479", stroke: "currentColor" }],
];

export const Wind = /* @__PURE__ */ createIcon("Wind", {
	linear: nodes,
	bold: nodes,
});
