/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const Wind = /* @__PURE__ */ createIcon("Wind", {
	linear: [
		["path", { d: "M3 9H13.5C15.16 9 16.5 7.66 16.5 6C16.5 4.62 15.38 3.5 14 3.5C12.9 3.5 12 4.2 11.75 5.2 M3 12.5H18C19.93 12.5 21.5 14.07 21.5 16C21.5 17.66 20.16 19 18.5 19C17.3 19 16.3 18.3 16.05 17.2 M3 16H11.5", stroke: "currentColor" }],
	],
});
