/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ZoomIn = /* @__PURE__ */ createIcon("ZoomIn", {
	linear: [
		["path", { d: "M3 11.55A8.55 8.55 0 1 0 20.1 11.55A8.55 8.55 0 1 0 3 11.55Z M17.5962 17.5962L21 21M9.3 11.55h4.5M11.55 9.3v4.5", stroke: "currentColor" }],
	],
});
