/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon.js";

export const ZoomOut = /* @__PURE__ */ createIcon("ZoomOut", {
	linear: [
		["path", { d: "M2.1 11.505A9.405 9.405 0 1 0 20.91 11.505A9.405 9.405 0 1 0 2.1 11.505ZM18.1558 18.1558L21.9 21.9M9.03 11.505h4.95", stroke: "currentColor" }],
	],
});
