/* Generated by scripts/build-icons.ts. Do not edit. */
import { createIcon } from "../create-icon";

export const ZoomIn = createIcon("ZoomIn", {
	linear: [
		["circle", { cx: "11.55", cy: "11.55", r: "8.55", stroke: "currentColor" }],
		["path", { d: "M17.5962 17.5962L21 21M9.3 11.55h4.5M11.55 9.3v4.5", stroke: "currentColor" }],
	],
});

/** @deprecated Use ZoomIn instead. */
export const SearchPlus = ZoomIn;
