/* Generated by scripts/build-icons.ts. Do not edit. */
import type { HoneyIcon } from "./create-icon.js";
import type { IconCategory } from "./categories.js";
import type { IconVariant } from "./types.js";
import { Add } from "./icons/add.js";
import { AlertTriangle } from "./icons/alert-triangle.js";
import { Anthropic } from "./icons/anthropic.js";
import { Antigravity } from "./icons/antigravity.js";
import { Archive } from "./icons/archive.js";
import { ArchiveAlt } from "./icons/archive-alt.js";
import { ArrowDown } from "./icons/arrow-down.js";
import { ArrowDownLeft } from "./icons/arrow-down-left.js";
import { ArrowDownRight } from "./icons/arrow-down-right.js";
import { ArrowLeft } from "./icons/arrow-left.js";
import { ArrowRight } from "./icons/arrow-right.js";
import { ArrowUp } from "./icons/arrow-up.js";
import { ArrowUpLeft } from "./icons/arrow-up-left.js";
import { ArrowUpRight } from "./icons/arrow-up-right.js";
import { Bell } from "./icons/bell.js";
import { Bolt } from "./icons/bolt.js";
import { Bookmark } from "./icons/bookmark.js";
import { Brain } from "./icons/brain.js";
import { Bun } from "./icons/bun.js";
import { Calendar } from "./icons/calendar.js";
import { CalendarAdd } from "./icons/calendar-add.js";
import { CalendarMark } from "./icons/calendar-mark.js";
import { Card } from "./icons/card.js";
import { Cart } from "./icons/cart.js";
import { CartBag } from "./icons/cart-bag.js";
import { CartLarge } from "./icons/cart-large.js";
import { Check } from "./icons/check.js";
import { CheckDouble } from "./icons/check-double.js";
import { ChevronDown } from "./icons/chevron-down.js";
import { ChevronLeft } from "./icons/chevron-left.js";
import { ChevronRight } from "./icons/chevron-right.js";
import { ChevronUp } from "./icons/chevron-up.js";
import { ChevronsDown } from "./icons/chevrons-down.js";
import { ChevronsLeft } from "./icons/chevrons-left.js";
import { ChevronsRight } from "./icons/chevrons-right.js";
import { ChevronsUp } from "./icons/chevrons-up.js";
import { Chrome } from "./icons/chrome.js";
import { Clapperboard } from "./icons/clapperboard.js";
import { ClapperboardText } from "./icons/clapperboard-text.js";
import { ClaudeAi } from "./icons/claude-ai.js";
import { ClaudeCode } from "./icons/claude-code.js";
import { Clock } from "./icons/clock.js";
import { Close } from "./icons/close.js";
import { Cloud } from "./icons/cloud.js";
import { Code } from "./icons/code.js";
import { Codex } from "./icons/codex.js";
import { Command } from "./icons/command.js";
import { Computer } from "./icons/computer.js";
import { Copy } from "./icons/copy.js";
import { Cursor } from "./icons/cursor.js";
import { Deepseek } from "./icons/deepseek.js";
import { Devin } from "./icons/devin.js";
import { Discord } from "./icons/discord.js";
import { Dislike } from "./icons/dislike.js";
import { DoorOpen } from "./icons/door-open.js";
import { Edit } from "./icons/edit.js";
import { EditOff } from "./icons/edit-off.js";
import { Email } from "./icons/email.js";
import { Facebook } from "./icons/facebook.js";
import { File } from "./icons/file.js";
import { FileAdd } from "./icons/file-add.js";
import { FileCode } from "./icons/file-code.js";
import { FileRemove } from "./icons/file-remove.js";
import { FileText } from "./icons/file-text.js";
import { Folder } from "./icons/folder.js";
import { FolderAdd } from "./icons/folder-add.js";
import { FolderOpen } from "./icons/folder-open.js";
import { FolderTree } from "./icons/folder-tree.js";
import { Gemini } from "./icons/gemini.js";
import { Git } from "./icons/git.js";
import { GitBranch } from "./icons/git-branch.js";
import { GitDiff } from "./icons/git-diff.js";
import { GitFork } from "./icons/git-fork.js";
import { GitGraph } from "./icons/git-graph.js";
import { GitPullRequest } from "./icons/git-pull-request.js";
import { Github } from "./icons/github.js";
import { GithubCopilot } from "./icons/github-copilot.js";
import { Google } from "./icons/google.js";
import { Grok } from "./icons/grok.js";
import { Hashtag } from "./icons/hashtag.js";
import { Headphones } from "./icons/headphones.js";
import { Home } from "./icons/home.js";
import { HomeAngle } from "./icons/home-angle.js";
import { Image } from "./icons/image.js";
import { ImageAdd } from "./icons/image-add.js";
import { ImageEdit } from "./icons/image-edit.js";
import { Instagram } from "./icons/instagram.js";
import { Integration } from "./icons/integration.js";
import { Key } from "./icons/key.js";
import { Kimi } from "./icons/kimi.js";
import { Layers } from "./icons/layers.js";
import { Lightning } from "./icons/lightning.js";
import { Like } from "./icons/like.js";
import { Linkedin } from "./icons/linkedin.js";
import { ListDown } from "./icons/list-down.js";
import { ListUp } from "./icons/list-up.js";
import { Lock } from "./icons/lock.js";
import { LockOpen } from "./icons/lock-open.js";
import { Logout } from "./icons/logout.js";
import { Maximize } from "./icons/maximize.js";
import { Menu } from "./icons/menu.js";
import { MetaAi } from "./icons/meta-ai.js";
import { Microphone } from "./icons/microphone.js";
import { MicrosoftCopilot } from "./icons/microsoft-copilot.js";
import { Minimize } from "./icons/minimize.js";
import { Minus } from "./icons/minus.js";
import { Mistral } from "./icons/mistral.js";
import { Moon } from "./icons/moon.js";
import { MoreHorizontal } from "./icons/more-horizontal.js";
import { MoreVertical } from "./icons/more-vertical.js";
import { MusicNote } from "./icons/music-note.js";
import { Npm } from "./icons/npm.js";
import { Nvidia } from "./icons/nvidia.js";
import { Openai } from "./icons/openai.js";
import { Openclaw } from "./icons/openclaw.js";
import { Opencode } from "./icons/opencode.js";
import { PaperPlane } from "./icons/paper-plane.js";
import { Paperclip } from "./icons/paperclip.js";
import { Pen } from "./icons/pen.js";
import { Perplexity } from "./icons/perplexity.js";
import { Pin } from "./icons/pin.js";
import { Pinterest } from "./icons/pinterest.js";
import { Pip } from "./icons/pip.js";
import { Play } from "./icons/play.js";
import { Quote } from "./icons/quote.js";
import { Qwen } from "./icons/qwen.js";
import { React } from "./icons/react.js";
import { Reddit } from "./icons/reddit.js";
import { Redo } from "./icons/redo.js";
import { Reorder } from "./icons/reorder.js";
import { Repeat } from "./icons/repeat.js";
import { Search } from "./icons/search.js";
import { Settings } from "./icons/settings.js";
import { Share } from "./icons/share.js";
import { SidebarLeft } from "./icons/sidebar-left.js";
import { SidebarRight } from "./icons/sidebar-right.js";
import { Slack } from "./icons/slack.js";
import { Smartphone } from "./icons/smartphone.js";
import { Snapchat } from "./icons/snapchat.js";
import { Soundwave } from "./icons/soundwave.js";
import { Spinner } from "./icons/spinner.js";
import { SpinnerArc } from "./icons/spinner-arc.js";
import { SpinnerDiagonal } from "./icons/spinner-diagonal.js";
import { SpinnerOrbit } from "./icons/spinner-orbit.js";
import { SpinnerWave } from "./icons/spinner-wave.js";
import { SquarePen } from "./icons/square-pen.js";
import { Star } from "./icons/star.js";
import { Sticker } from "./icons/sticker.js";
import { Stop } from "./icons/stop.js";
import { Sun } from "./icons/sun.js";
import { Supabase } from "./icons/supabase.js";
import { Tablet } from "./icons/tablet.js";
import { Telegram } from "./icons/telegram.js";
import { Terminal } from "./icons/terminal.js";
import { Threads } from "./icons/threads.js";
import { Ticket } from "./icons/ticket.js";
import { Tiktok } from "./icons/tiktok.js";
import { Trash } from "./icons/trash.js";
import { Twitter } from "./icons/twitter.js";
import { Typescript } from "./icons/typescript.js";
import { Undo } from "./icons/undo.js";
import { UnfoldLess } from "./icons/unfold-less.js";
import { UnfoldMore } from "./icons/unfold-more.js";
import { User } from "./icons/user.js";
import { UserAdd } from "./icons/user-add.js";
import { UserGroup } from "./icons/user-group.js";
import { Vercel } from "./icons/vercel.js";
import { VerifiedCheck } from "./icons/verified-check.js";
import { VideoCamera } from "./icons/video-camera.js";
import { VideoFrame } from "./icons/video-frame.js";
import { VolumeHigh } from "./icons/volume-high.js";
import { VolumeLow } from "./icons/volume-low.js";
import { VolumeOff } from "./icons/volume-off.js";
import { Wallet } from "./icons/wallet.js";
import { Widget } from "./icons/widget.js";
import { WidgetAdd } from "./icons/widget-add.js";
import { WidgetSquare } from "./icons/widget-square.js";
import { WidgetSquareAdd } from "./icons/widget-square-add.js";
import { Windsurf } from "./icons/windsurf.js";
import { X } from "./icons/x.js";
import { Xai } from "./icons/xai.js";
import { Youtube } from "./icons/youtube.js";
import { Zai } from "./icons/zai.js";
import { ZoomIn } from "./icons/zoom-in.js";
import { ZoomOut } from "./icons/zoom-out.js";

export type { IconCategory } from "./categories.js";
export { ICON_CATEGORIES } from "./categories.js";

export type CatalogItem = {
	name: string;
	pascalName: string;
	category: IconCategory;
	tags: string[];
	variants: IconVariant[];
	component: HoneyIcon;
};

export const catalog: CatalogItem[] = [
	{
		name: "add",
		pascalName: "Add",
		category: "actions",
		tags: ["plus","new","create","solar"],
		variants: ["linear"],
		component: Add,
	},
	{
		name: "alert-triangle",
		pascalName: "AlertTriangle",
		category: "status",
		tags: ["warning","alert","triangle","error","danger-triangle","solar","danger"],
		variants: ["linear"],
		component: AlertTriangle,
	},
	{
		name: "anthropic",
		pascalName: "Anthropic",
		category: "social",
		tags: ["claude","ai","brand"],
		variants: ["bold"],
		component: Anthropic,
	},
	{
		name: "antigravity",
		pascalName: "Antigravity",
		category: "social",
		tags: ["ai","code","editor","brand"],
		variants: ["bold"],
		component: Antigravity,
	},
	{
		name: "archive",
		pascalName: "Archive",
		category: "files",
		tags: ["library","collection","stack","archive","files","solar","pallet"],
		variants: ["linear"],
		component: Archive,
	},
	{
		name: "archive-alt",
		pascalName: "ArchiveAlt",
		category: "files",
		tags: ["archive","box","storage","done","check","archive-minimalistic","solar"],
		variants: ["linear"],
		component: ArchiveAlt,
	},
	{
		name: "arrow-down",
		pascalName: "ArrowDown",
		category: "arrows",
		tags: ["arrow","down","direction","navigation","arrow-down-02","hugeicons","ArrowDown02"],
		variants: ["linear"],
		component: ArrowDown,
	},
	{
		name: "arrow-down-left",
		pascalName: "ArrowDownLeft",
		category: "arrows",
		tags: ["arrow","down-left","direction","navigation","arrow-down-left-01","hugeicons"],
		variants: ["linear"],
		component: ArrowDownLeft,
	},
	{
		name: "arrow-down-right",
		pascalName: "ArrowDownRight",
		category: "arrows",
		tags: ["arrow","down-right","direction","navigation","arrow-down-right-01","hugeicons"],
		variants: ["linear"],
		component: ArrowDownRight,
	},
	{
		name: "arrow-left",
		pascalName: "ArrowLeft",
		category: "arrows",
		tags: ["arrow","left","direction","navigation","arrow-left-02","hugeicons","ArrowLeft02"],
		variants: ["linear"],
		component: ArrowLeft,
	},
	{
		name: "arrow-right",
		pascalName: "ArrowRight",
		category: "arrows",
		tags: ["arrow","right","direction","navigation","arrow-right-02","hugeicons","ArrowRight02"],
		variants: ["linear"],
		component: ArrowRight,
	},
	{
		name: "arrow-up",
		pascalName: "ArrowUp",
		category: "arrows",
		tags: ["arrow","up","direction","navigation","arrow-up-02","hugeicons","ArrowUp02"],
		variants: ["linear"],
		component: ArrowUp,
	},
	{
		name: "arrow-up-left",
		pascalName: "ArrowUpLeft",
		category: "arrows",
		tags: ["arrow","up-left","direction","navigation","arrow-up-left-01","hugeicons"],
		variants: ["linear"],
		component: ArrowUpLeft,
	},
	{
		name: "arrow-up-right",
		pascalName: "ArrowUpRight",
		category: "arrows",
		tags: ["arrow","up-right","direction","navigation","arrow-up-right-01","hugeicons"],
		variants: ["linear"],
		component: ArrowUpRight,
	},
	{
		name: "bell",
		pascalName: "Bell",
		category: "status",
		tags: ["notification","alert","reminder","alarm","solar"],
		variants: ["linear"],
		component: Bell,
	},
	{
		name: "bolt",
		pascalName: "Bolt",
		category: "status",
		tags: ["bolt","lightning","flash","energy","power","zap","solar"],
		variants: ["linear"],
		component: Bolt,
	},
	{
		name: "bookmark",
		pascalName: "Bookmark",
		category: "actions",
		tags: ["save","saved","favorite","reading","solar"],
		variants: ["linear"],
		component: Bookmark,
	},
	{
		name: "brain",
		pascalName: "Brain",
		category: "ai",
		tags: ["ai","brain","intelligence","neural","ai-brain-01","hugeicons","ai-brain"],
		variants: ["linear"],
		component: Brain,
	},
	{
		name: "bun",
		pascalName: "Bun",
		category: "social",
		tags: ["javascript","runtime","brand"],
		variants: ["bold"],
		component: Bun,
	},
	{
		name: "calendar",
		pascalName: "Calendar",
		category: "layout",
		tags: ["calendar","date","schedule","event","month","hugeicons","calendar-03","Calendar03"],
		variants: ["linear"],
		component: Calendar,
	},
	{
		name: "calendar-add",
		pascalName: "CalendarAdd",
		category: "layout",
		tags: ["calendar","date","event","add","new","schedule","solar"],
		variants: ["linear"],
		component: CalendarAdd,
	},
	{
		name: "calendar-mark",
		pascalName: "CalendarMark",
		category: "layout",
		tags: ["calendar","date","event","mark","selected","today","solar"],
		variants: ["linear"],
		component: CalendarMark,
	},
	{
		name: "card",
		pascalName: "Card",
		category: "actions",
		tags: ["credit-card","debit-card","payment","bank","finance","solar"],
		variants: ["linear"],
		component: Card,
	},
	{
		name: "cart",
		pascalName: "Cart",
		category: "actions",
		tags: ["basket","shopping","store","solar"],
		variants: ["linear"],
		component: Cart,
	},
	{
		name: "cart-bag",
		pascalName: "CartBag",
		category: "actions",
		tags: ["bag","shopping-bag","shopping","store","purchase","checkout","solar"],
		variants: ["linear"],
		component: CartBag,
	},
	{
		name: "cart-large",
		pascalName: "CartLarge",
		category: "actions",
		tags: ["cart","shopping-cart","trolley","checkout","store","shopping","solar"],
		variants: ["linear"],
		component: CartLarge,
	},
	{
		name: "check",
		pascalName: "Check",
		category: "status",
		tags: ["tick","done","success","confirm","complete","hugeicons"],
		variants: ["linear"],
		component: Check,
	},
	{
		name: "check-double",
		pascalName: "CheckDouble",
		category: "status",
		tags: ["double-check","tick","done","read","receipt","delivered","hugeicons","check-check","CheckCheck"],
		variants: ["linear"],
		component: CheckDouble,
	},
	{
		name: "chevron-down",
		pascalName: "ChevronDown",
		category: "arrows",
		tags: ["chevron","down","bottom","expand","arrow-down-01","hugeicons","arrow-down","ArrowDown"],
		variants: ["linear"],
		component: ChevronDown,
	},
	{
		name: "chevron-left",
		pascalName: "ChevronLeft",
		category: "arrows",
		tags: ["chevron","left","back","previous","arrow-left-01","hugeicons","arrow-left","ArrowLeft"],
		variants: ["linear"],
		component: ChevronLeft,
	},
	{
		name: "chevron-right",
		pascalName: "ChevronRight",
		category: "arrows",
		tags: ["chevron","right","forward","next","arrow-right-01","hugeicons","arrow-right","ArrowRight"],
		variants: ["linear"],
		component: ChevronRight,
	},
	{
		name: "chevron-up",
		pascalName: "ChevronUp",
		category: "arrows",
		tags: ["chevron","up","top","collapse","arrow-up-01","hugeicons","arrow-up","ArrowUp"],
		variants: ["linear"],
		component: ChevronUp,
	},
	{
		name: "chevrons-down",
		pascalName: "ChevronsDown",
		category: "arrows",
		tags: ["chevron","double","down","bottom","hugeicons","arrow-down-double","ArrowDownDouble"],
		variants: ["linear"],
		component: ChevronsDown,
	},
	{
		name: "chevrons-left",
		pascalName: "ChevronsLeft",
		category: "arrows",
		tags: ["chevron","double","left","first","hugeicons","arrow-left-double","ArrowLeftDouble"],
		variants: ["linear"],
		component: ChevronsLeft,
	},
	{
		name: "chevrons-right",
		pascalName: "ChevronsRight",
		category: "arrows",
		tags: ["chevron","double","right","last","hugeicons","arrow-right-double","ArrowRightDouble"],
		variants: ["linear"],
		component: ChevronsRight,
	},
	{
		name: "chevrons-up",
		pascalName: "ChevronsUp",
		category: "arrows",
		tags: ["chevron","double","up","top","hugeicons","arrow-up-double","ArrowUpDouble"],
		variants: ["linear"],
		component: ChevronsUp,
	},
	{
		name: "chrome",
		pascalName: "Chrome",
		category: "social",
		tags: ["brand","chrome","google","browser"],
		variants: ["bold"],
		component: Chrome,
	},
	{
		name: "clapperboard",
		pascalName: "Clapperboard",
		category: "media",
		tags: ["film","movie","video","play","clapperboard-play","solar"],
		variants: ["linear"],
		component: Clapperboard,
	},
	{
		name: "clapperboard-text",
		pascalName: "ClapperboardText",
		category: "media",
		tags: ["film","movie","video","script","clapperboard","solar"],
		variants: ["linear"],
		component: ClapperboardText,
	},
	{
		name: "claude-ai",
		pascalName: "ClaudeAi",
		category: "social",
		tags: ["claude","anthropic","ai","assistant","brand"],
		variants: ["bold"],
		component: ClaudeAi,
	},
	{
		name: "claude-code",
		pascalName: "ClaudeCode",
		category: "social",
		tags: ["claude","anthropic","ai","code","terminal","brand"],
		variants: ["bold"],
		component: ClaudeCode,
	},
	{
		name: "clock",
		pascalName: "Clock",
		category: "status",
		tags: ["time","hour","schedule","watch"],
		variants: ["linear"],
		component: Clock,
	},
	{
		name: "close",
		pascalName: "Close",
		category: "actions",
		tags: ["dismiss","cancel","cross","x","solar"],
		variants: ["linear"],
		component: Close,
	},
	{
		name: "cloud",
		pascalName: "Cloud",
		category: "files",
		tags: ["storage","weather","online","sync","solar"],
		variants: ["linear"],
		component: Cloud,
	},
	{
		name: "code",
		pascalName: "Code",
		category: "editor",
		tags: ["programming","developer","syntax","brackets","solar"],
		variants: ["linear"],
		component: Code,
	},
	{
		name: "codex",
		pascalName: "Codex",
		category: "social",
		tags: ["openai","ai","coding","brand"],
		variants: ["bold"],
		component: Codex,
	},
	{
		name: "command",
		pascalName: "Command",
		category: "editor",
		tags: ["keyboard","shortcut","cmd","mac","solar"],
		variants: ["linear"],
		component: Command,
	},
	{
		name: "computer",
		pascalName: "Computer",
		category: "layout",
		tags: ["monitor","desktop","screen","display","device","hugeicons"],
		variants: ["linear","bold"],
		component: Computer,
	},
	{
		name: "copy",
		pascalName: "Copy",
		category: "actions",
		tags: ["copy","duplicate","clipboard","copy-01","hugeicons"],
		variants: ["linear"],
		component: Copy,
	},
	{
		name: "cursor",
		pascalName: "Cursor",
		category: "social",
		tags: ["brand","cursor","ai","code","editor"],
		variants: ["bold"],
		component: Cursor,
	},
	{
		name: "deepseek",
		pascalName: "Deepseek",
		category: "social",
		tags: ["ai","whale","brand"],
		variants: ["bold"],
		component: Deepseek,
	},
	{
		name: "devin",
		pascalName: "Devin",
		category: "social",
		tags: ["ai","code","agent","brand"],
		variants: ["bold"],
		component: Devin,
	},
	{
		name: "discord",
		pascalName: "Discord",
		category: "social",
		tags: ["chat","community","brand"],
		variants: ["bold"],
		component: Discord,
	},
	{
		name: "dislike",
		pascalName: "Dislike",
		category: "actions",
		tags: ["thumbs-down","disapprove","feedback","hugeicons"],
		variants: ["linear"],
		component: Dislike,
	},
	{
		name: "door-open",
		pascalName: "DoorOpen",
		category: "actions",
		tags: ["door","leave","logout","sign-out","solar","exit"],
		variants: ["linear"],
		component: DoorOpen,
	},
	{
		name: "edit",
		pascalName: "Edit",
		category: "editor",
		tags: ["edit","pencil","write","draw","hugeicons","edit-01","Edit01"],
		variants: ["linear"],
		component: Edit,
	},
	{
		name: "edit-off",
		pascalName: "EditOff",
		category: "editor",
		tags: ["edit","disabled","read-only","pencil","hugeicons"],
		variants: ["linear"],
		component: EditOff,
	},
	{
		name: "email",
		pascalName: "Email",
		category: "chat",
		tags: ["mail","letter","envelope","message","solar"],
		variants: ["linear"],
		component: Email,
	},
	{
		name: "facebook",
		pascalName: "Facebook",
		category: "social",
		tags: ["meta","social","brand"],
		variants: ["bold"],
		component: Facebook,
	},
	{
		name: "file",
		pascalName: "File",
		category: "files",
		tags: ["document","page","paper","blank","solar"],
		variants: ["linear"],
		component: File,
	},
	{
		name: "file-add",
		pascalName: "FileAdd",
		category: "files",
		tags: ["document","file","solar","new","create","add","plus"],
		variants: ["linear"],
		component: FileAdd,
	},
	{
		name: "file-code",
		pascalName: "FileCode",
		category: "files",
		tags: ["document","code","source","programming","code-file","solar"],
		variants: ["linear"],
		component: FileCode,
	},
	{
		name: "file-remove",
		pascalName: "FileRemove",
		category: "files",
		tags: ["document","file","solar","remove","delete","minus"],
		variants: ["linear"],
		component: FileRemove,
	},
	{
		name: "file-text",
		pascalName: "FileText",
		category: "files",
		tags: ["document","page","paper","text","lines","notes","solar"],
		variants: ["linear"],
		component: FileText,
	},
	{
		name: "folder",
		pascalName: "Folder",
		category: "files",
		tags: ["folder","directory","files","storage","hugeicons","folder-01","Folder01"],
		variants: ["linear"],
		component: Folder,
	},
	{
		name: "folder-add",
		pascalName: "FolderAdd",
		category: "files",
		tags: ["folder","directory","create","new","plus","hugeicons"],
		variants: ["linear"],
		component: FolderAdd,
	},
	{
		name: "folder-open",
		pascalName: "FolderOpen",
		category: "files",
		tags: ["folder","open","directory","files","storage","hugeicons"],
		variants: ["linear"],
		component: FolderOpen,
	},
	{
		name: "folder-tree",
		pascalName: "FolderTree",
		category: "files",
		tags: ["folder","tree","directory","hierarchy","structure","files","solar"],
		variants: ["linear"],
		component: FolderTree,
	},
	{
		name: "gemini",
		pascalName: "Gemini",
		category: "social",
		tags: ["google","ai","brand"],
		variants: ["bold"],
		component: Gemini,
	},
	{
		name: "git",
		pascalName: "Git",
		category: "social",
		tags: ["version-control","repository","code","brand"],
		variants: ["bold"],
		component: Git,
	},
	{
		name: "git-branch",
		pascalName: "GitBranch",
		category: "editor",
		tags: ["git","branch","version-control","source-control","solar"],
		variants: ["linear"],
		component: GitBranch,
	},
	{
		name: "git-diff",
		pascalName: "GitDiff",
		category: "editor",
		tags: ["git","diff","compare","changes","version-control","solar"],
		variants: ["linear"],
		component: GitDiff,
	},
	{
		name: "git-fork",
		pascalName: "GitFork",
		category: "editor",
		tags: ["git","fork","split","version-control","repository","solar"],
		variants: ["linear"],
		component: GitFork,
	},
	{
		name: "git-graph",
		pascalName: "GitGraph",
		category: "editor",
		tags: ["git","graph","history","commits","version-control","solar"],
		variants: ["linear"],
		component: GitGraph,
	},
	{
		name: "git-pull-request",
		pascalName: "GitPullRequest",
		category: "editor",
		tags: ["git","pull-request","pr","merge","review","version-control","solar"],
		variants: ["linear"],
		component: GitPullRequest,
	},
	{
		name: "github",
		pascalName: "Github",
		category: "social",
		tags: ["git","code","repository","brand"],
		variants: ["bold"],
		component: Github,
	},
	{
		name: "github-copilot",
		pascalName: "GithubCopilot",
		category: "social",
		tags: ["brand","github","copilot","ai","code","assistant"],
		variants: ["bold"],
		component: GithubCopilot,
	},
	{
		name: "google",
		pascalName: "Google",
		category: "social",
		tags: ["search","alphabet","brand"],
		variants: ["bold"],
		component: Google,
	},
	{
		name: "grok",
		pascalName: "Grok",
		category: "social",
		tags: ["xai","ai","assistant","brand"],
		variants: ["linear"],
		component: Grok,
	},
	{
		name: "hashtag",
		pascalName: "Hashtag",
		category: "editor",
		tags: ["hash","tag","number","hastag","solar"],
		variants: ["linear"],
		component: Hashtag,
	},
	{
		name: "headphones",
		pascalName: "Headphones",
		category: "media",
		tags: ["headphones","audio","music","listen","headphones-round","solar","headphone"],
		variants: ["linear"],
		component: Headphones,
	},
	{
		name: "home",
		pascalName: "Home",
		category: "layout",
		tags: [],
		variants: ["linear"],
		component: Home,
	},
	{
		name: "home-angle",
		pascalName: "HomeAngle",
		category: "layout",
		tags: ["home","house","dashboard","main","solar"],
		variants: ["linear"],
		component: HomeAngle,
	},
	{
		name: "image",
		pascalName: "Image",
		category: "media",
		tags: ["image","gallery","photo","picture","media","images"],
		variants: ["linear"],
		component: Image,
	},
	{
		name: "image-add",
		pascalName: "ImageAdd",
		category: "media",
		tags: ["image","gallery","upload","photo","plus","gallery-add","solar","images-add","ImagesAdd"],
		variants: ["linear"],
		component: ImageAdd,
	},
	{
		name: "image-edit",
		pascalName: "ImageEdit",
		category: "media",
		tags: ["image","photo","gallery","edit","pencil","gallery-edit","solar"],
		variants: ["linear"],
		component: ImageEdit,
	},
	{
		name: "instagram",
		pascalName: "Instagram",
		category: "social",
		tags: ["instagram","social","photos","brand","insta"],
		variants: ["linear"],
		component: Instagram,
	},
	{
		name: "integration",
		pascalName: "Integration",
		category: "layout",
		tags: ["flow","workflow","connect","nodes","hugeicons"],
		variants: ["linear"],
		component: Integration,
	},
	{
		name: "key",
		pascalName: "Key",
		category: "settings",
		tags: ["security","access","password","lock","key-minimalistic","solar"],
		variants: ["linear"],
		component: Key,
	},
	{
		name: "kimi",
		pascalName: "Kimi",
		category: "social",
		tags: ["ai","assistant","moonshot","brand"],
		variants: ["bold"],
		component: Kimi,
	},
	{
		name: "layers",
		pascalName: "Layers",
		category: "layout",
		tags: ["stack","design","levels","layers-minimalistic","solar"],
		variants: ["linear"],
		component: Layers,
	},
	{
		name: "lightning",
		pascalName: "Lightning",
		category: "status",
		tags: ["bolt","flash","electricity","energy","power","zap"],
		variants: ["linear"],
		component: Lightning,
	},
	{
		name: "like",
		pascalName: "Like",
		category: "actions",
		tags: ["thumbs-up","approve","feedback","hugeicons"],
		variants: ["linear"],
		component: Like,
	},
	{
		name: "linkedin",
		pascalName: "Linkedin",
		category: "social",
		tags: ["brand","linkedin"],
		variants: ["bold"],
		component: Linkedin,
	},
	{
		name: "list-down",
		pascalName: "ListDown",
		category: "actions",
		tags: ["list","sort","descending","expand","list-down-minimalistic","solar"],
		variants: ["linear"],
		component: ListDown,
	},
	{
		name: "list-up",
		pascalName: "ListUp",
		category: "actions",
		tags: ["list","sort","ascending","collapse","list-up-minimalistic","solar"],
		variants: ["linear"],
		component: ListUp,
	},
	{
		name: "lock",
		pascalName: "Lock",
		category: "status",
		tags: ["locked","security","private","access","solar"],
		variants: ["linear"],
		component: Lock,
	},
	{
		name: "lock-open",
		pascalName: "LockOpen",
		category: "status",
		tags: ["lock-open","unlock","security","access","solar","lock-unlock","LockUnlock"],
		variants: ["linear"],
		component: LockOpen,
	},
	{
		name: "logout",
		pascalName: "Logout",
		category: "user",
		tags: ["sign-out","exit","account","logout-3","solar"],
		variants: ["linear"],
		component: Logout,
	},
	{
		name: "maximize",
		pascalName: "Maximize",
		category: "arrows",
		tags: ["expand","fullscreen","resize","arrows"],
		variants: ["linear"],
		component: Maximize,
	},
	{
		name: "menu",
		pascalName: "Menu",
		category: "actions",
		tags: ["menu","navigation","bars","hamburger-menu","solar","hamburger"],
		variants: ["linear"],
		component: Menu,
	},
	{
		name: "meta-ai",
		pascalName: "MetaAi",
		category: "social",
		tags: ["brand","meta","ai","assistant"],
		variants: ["bold"],
		component: MetaAi,
	},
	{
		name: "microphone",
		pascalName: "Microphone",
		category: "media",
		tags: ["mic","record","voice","audio","solar"],
		variants: ["linear"],
		component: Microphone,
	},
	{
		name: "microsoft-copilot",
		pascalName: "MicrosoftCopilot",
		category: "social",
		tags: ["microsoft","copilot","ai","assistant","brand","ms-copilot","MsCopilot"],
		variants: ["bold"],
		component: MicrosoftCopilot,
	},
	{
		name: "minimize",
		pascalName: "Minimize",
		category: "arrows",
		tags: ["collapse","shrink","restore","resize","arrows"],
		variants: ["linear"],
		component: Minimize,
	},
	{
		name: "minus",
		pascalName: "Minus",
		category: "actions",
		tags: ["subtract","remove","decrease","solar"],
		variants: ["linear"],
		component: Minus,
	},
	{
		name: "mistral",
		pascalName: "Mistral",
		category: "social",
		tags: ["ai","brand"],
		variants: ["bold"],
		component: Mistral,
	},
	{
		name: "moon",
		pascalName: "Moon",
		category: "settings",
		tags: ["moon","night","dark","theme","crescent","solar"],
		variants: ["linear","bold"],
		component: Moon,
	},
	{
		name: "more-horizontal",
		pascalName: "MoreHorizontal",
		category: "actions",
		tags: ["ellipsis","menu","options","dots","horizontal","hugeicons"],
		variants: ["linear"],
		component: MoreHorizontal,
	},
	{
		name: "more-vertical",
		pascalName: "MoreVertical",
		category: "actions",
		tags: ["ellipsis","menu","options","dots","vertical","hugeicons"],
		variants: ["linear"],
		component: MoreVertical,
	},
	{
		name: "music-note",
		pascalName: "MusicNote",
		category: "media",
		tags: ["music","note","song","audio","sound","melody","solar"],
		variants: ["linear"],
		component: MusicNote,
	},
	{
		name: "npm",
		pascalName: "Npm",
		category: "social",
		tags: ["package","registry","javascript","brand"],
		variants: ["bold"],
		component: Npm,
	},
	{
		name: "nvidia",
		pascalName: "Nvidia",
		category: "social",
		tags: ["brand","nvidia","gpu","hardware"],
		variants: ["bold"],
		component: Nvidia,
	},
	{
		name: "openai",
		pascalName: "Openai",
		category: "social",
		tags: ["chatgpt","ai","brand"],
		variants: ["linear"],
		component: Openai,
	},
	{
		name: "openclaw",
		pascalName: "Openclaw",
		category: "social",
		tags: ["open-claw","ai","mascot","brand"],
		variants: ["bold"],
		component: Openclaw,
	},
	{
		name: "opencode",
		pascalName: "Opencode",
		category: "social",
		tags: ["open-code","code","terminal","brand"],
		variants: ["bold"],
		component: Opencode,
	},
	{
		name: "paper-plane",
		pascalName: "PaperPlane",
		category: "actions",
		tags: ["send","message","submit","plane","plane-3","plain-3","solar"],
		variants: ["linear"],
		component: PaperPlane,
	},
	{
		name: "paperclip",
		pascalName: "Paperclip",
		category: "actions",
		tags: ["attachment","attach","clip","file","paperclip-2","solar"],
		variants: ["linear"],
		component: Paperclip,
	},
	{
		name: "pen",
		pascalName: "Pen",
		category: "editor",
		tags: ["edit","pencil","write","draw","compose"],
		variants: ["linear"],
		component: Pen,
	},
	{
		name: "perplexity",
		pascalName: "Perplexity",
		category: "social",
		tags: ["brand","perplexity","ai","search"],
		variants: ["linear"],
		component: Perplexity,
	},
	{
		name: "pin",
		pascalName: "Pin",
		category: "actions",
		tags: ["pushpin","pinned","save","solar"],
		variants: ["linear"],
		component: Pin,
	},
	{
		name: "pinterest",
		pascalName: "Pinterest",
		category: "social",
		tags: ["social","pins","brand"],
		variants: ["bold"],
		component: Pinterest,
	},
	{
		name: "pip",
		pascalName: "Pip",
		category: "layout",
		tags: ["picture-in-picture","pip","window","video","overlay","solar"],
		variants: ["linear"],
		component: Pip,
	},
	{
		name: "play",
		pascalName: "Play",
		category: "media",
		tags: ["start","resume","playback","video","audio","solar"],
		variants: ["linear"],
		component: Play,
	},
	{
		name: "quote",
		pascalName: "Quote",
		category: "editor",
		tags: ["quote","quotation","blockquote","citation","testimonial","solar"],
		variants: ["linear"],
		component: Quote,
	},
	{
		name: "qwen",
		pascalName: "Qwen",
		category: "social",
		tags: ["ai","alibaba","brand"],
		variants: ["bold"],
		component: Qwen,
	},
	{
		name: "react",
		pascalName: "React",
		category: "social",
		tags: ["javascript","framework","frontend","brand"],
		variants: ["linear"],
		component: React,
	},
	{
		name: "reddit",
		pascalName: "Reddit",
		category: "social",
		tags: ["community","social","brand"],
		variants: ["bold"],
		component: Reddit,
	},
	{
		name: "redo",
		pascalName: "Redo",
		category: "arrows",
		tags: ["history","forward","repeat","arrow"],
		variants: ["linear"],
		component: Redo,
	},
	{
		name: "reorder",
		pascalName: "Reorder",
		category: "actions",
		tags: ["sort","arrange","drag","list","menu","solar"],
		variants: ["linear"],
		component: Reorder,
	},
	{
		name: "repeat",
		pascalName: "Repeat",
		category: "arrows",
		tags: ["loop","cycle","refresh","solar"],
		variants: ["linear"],
		component: Repeat,
	},
	{
		name: "search",
		pascalName: "Search",
		category: "actions",
		tags: [],
		variants: ["linear"],
		component: Search,
	},
	{
		name: "settings",
		pascalName: "Settings",
		category: "settings",
		tags: ["gear","cog","preferences","configuration","options","solar"],
		variants: ["linear"],
		component: Settings,
	},
	{
		name: "share",
		pascalName: "Share",
		category: "actions",
		tags: ["send","social","link","solar"],
		variants: ["linear"],
		component: Share,
	},
	{
		name: "sidebar-left",
		pascalName: "SidebarLeft",
		category: "layout",
		tags: ["panel","layout","navigation","sidebar","left","sidebar-minimalistic","solar"],
		variants: ["linear"],
		component: SidebarLeft,
	},
	{
		name: "sidebar-right",
		pascalName: "SidebarRight",
		category: "layout",
		tags: ["panel","layout","navigation","sidebar","right","sidebar-minimalistic","solar"],
		variants: ["linear"],
		component: SidebarRight,
	},
	{
		name: "slack",
		pascalName: "Slack",
		category: "social",
		tags: ["messaging","chat","team","workplace","brand"],
		variants: ["bold"],
		component: Slack,
	},
	{
		name: "smartphone",
		pascalName: "Smartphone",
		category: "layout",
		tags: ["phone","mobile","device","screen","solar"],
		variants: ["linear"],
		component: Smartphone,
	},
	{
		name: "snapchat",
		pascalName: "Snapchat",
		category: "social",
		tags: [],
		variants: ["linear","bold"],
		component: Snapchat,
	},
	{
		name: "soundwave",
		pascalName: "Soundwave",
		category: "media",
		tags: ["waveform","audio","sound","voice","equalizer","solar"],
		variants: ["linear"],
		component: Soundwave,
	},
	{
		name: "spinner",
		pascalName: "Spinner",
		category: "spinner",
		tags: ["loader","loading","progress","wait","busy","rotate"],
		variants: ["linear"],
		component: Spinner,
	},
	{
		name: "spinner-arc",
		pascalName: "SpinnerArc",
		category: "spinner",
		tags: ["loader","loading","progress","wait","rotate","arc","long","spinner-large","SpinnerLarge"],
		variants: ["linear"],
		component: SpinnerArc,
	},
	{
		name: "spinner-diagonal",
		pascalName: "SpinnerDiagonal",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","diagonal","wave"],
		variants: ["linear"],
		component: SpinnerDiagonal,
	},
	{
		name: "spinner-orbit",
		pascalName: "SpinnerOrbit",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","comet"],
		variants: ["linear"],
		component: SpinnerOrbit,
	},
	{
		name: "spinner-wave",
		pascalName: "SpinnerWave",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","chevron","wave","spinner-tinker","SpinnerTinker"],
		variants: ["linear"],
		component: SpinnerWave,
	},
	{
		name: "square-pen",
		pascalName: "SquarePen",
		category: "actions",
		tags: ["send-message","SendMessage","compose","edit","write","pencil"],
		variants: ["linear"],
		component: SquarePen,
	},
	{
		name: "star",
		pascalName: "Star",
		category: "actions",
		tags: ["favorite","rating","saved","solar"],
		variants: ["linear"],
		component: Star,
	},
	{
		name: "sticker",
		pascalName: "Sticker",
		category: "editor",
		tags: ["label","peel","fold","square","solar"],
		variants: ["linear"],
		component: Sticker,
	},
	{
		name: "stop",
		pascalName: "Stop",
		category: "media",
		tags: ["end","halt","playback","recording","square","solar"],
		variants: ["linear"],
		component: Stop,
	},
	{
		name: "sun",
		pascalName: "Sun",
		category: "settings",
		tags: ["sun","light","day","brightness","theme","sun-01","hugeicons"],
		variants: ["linear","bold"],
		component: Sun,
	},
	{
		name: "supabase",
		pascalName: "Supabase",
		category: "social",
		tags: ["database","backend","brand"],
		variants: ["bold"],
		component: Supabase,
	},
	{
		name: "tablet",
		pascalName: "Tablet",
		category: "layout",
		tags: ["ipad","device","screen","landscape","solar"],
		variants: ["linear"],
		component: Tablet,
	},
	{
		name: "telegram",
		pascalName: "Telegram",
		category: "social",
		tags: ["messaging","chat","social","brand","paper-plane"],
		variants: ["bold"],
		component: Telegram,
	},
	{
		name: "terminal",
		pascalName: "Terminal",
		category: "editor",
		tags: ["code","console","command","shell","prompt","cli"],
		variants: ["linear"],
		component: Terminal,
	},
	{
		name: "threads",
		pascalName: "Threads",
		category: "social",
		tags: ["brand","threads"],
		variants: ["linear"],
		component: Threads,
	},
	{
		name: "ticket",
		pascalName: "Ticket",
		category: "actions",
		tags: ["ticket","pass","event","admission","coupon","solar"],
		variants: ["linear"],
		component: Ticket,
	},
	{
		name: "tiktok",
		pascalName: "Tiktok",
		category: "social",
		tags: ["brand","tiktok"],
		variants: ["bold"],
		component: Tiktok,
	},
	{
		name: "trash",
		pascalName: "Trash",
		category: "actions",
		tags: [],
		variants: ["linear"],
		component: Trash,
	},
	{
		name: "twitter",
		pascalName: "Twitter",
		category: "social",
		tags: ["bird","social","brand"],
		variants: ["bold"],
		component: Twitter,
	},
	{
		name: "typescript",
		pascalName: "Typescript",
		category: "social",
		tags: ["typescript","javascript","language","brand","ts"],
		variants: ["bold"],
		component: Typescript,
	},
	{
		name: "undo",
		pascalName: "Undo",
		category: "arrows",
		tags: ["history","back","revert","arrow"],
		variants: ["linear"],
		component: Undo,
	},
	{
		name: "unfold-less",
		pascalName: "UnfoldLess",
		category: "arrows",
		tags: ["collapse","fold","chevrons","hugeicons"],
		variants: ["linear"],
		component: UnfoldLess,
	},
	{
		name: "unfold-more",
		pascalName: "UnfoldMore",
		category: "arrows",
		tags: ["expand","unfold","chevrons","hugeicons"],
		variants: ["linear"],
		component: UnfoldMore,
	},
	{
		name: "user",
		pascalName: "User",
		category: "user",
		tags: ["profile","person","account","avatar","solar"],
		variants: ["linear"],
		component: User,
	},
	{
		name: "user-add",
		pascalName: "UserAdd",
		category: "user",
		tags: ["user","add","plus","invite","account","user-plus","solar"],
		variants: ["linear"],
		component: UserAdd,
	},
	{
		name: "user-group",
		pascalName: "UserGroup",
		category: "user",
		tags: ["users","team","people","members","users-group-two-rounded","solar"],
		variants: ["linear"],
		component: UserGroup,
	},
	{
		name: "vercel",
		pascalName: "Vercel",
		category: "social",
		tags: ["brand","vercel","hosting","deployment"],
		variants: ["bold"],
		component: Vercel,
	},
	{
		name: "verified-check",
		pascalName: "VerifiedCheck",
		category: "status",
		tags: ["verified","badge","check","approved","solar"],
		variants: ["linear"],
		component: VerifiedCheck,
	},
	{
		name: "video-camera",
		pascalName: "VideoCamera",
		category: "media",
		tags: ["video","camera","record","call","videocamera","solar"],
		variants: ["linear"],
		component: VideoCamera,
	},
	{
		name: "video-frame",
		pascalName: "VideoFrame",
		category: "media",
		tags: ["video","film","frame","filmstrip","movie","solar"],
		variants: ["linear"],
		component: VideoFrame,
	},
	{
		name: "volume-high",
		pascalName: "VolumeHigh",
		category: "media",
		tags: ["volume","sound","speaker","audio","unmute","solar","volume-loud","VolumeLoud"],
		variants: ["linear"],
		component: VolumeHigh,
	},
	{
		name: "volume-low",
		pascalName: "VolumeLow",
		category: "media",
		tags: ["speaker","sound","audio","volume-low","solar","volume"],
		variants: ["linear"],
		component: VolumeLow,
	},
	{
		name: "volume-off",
		pascalName: "VolumeOff",
		category: "media",
		tags: ["mute","volume-off","silent","speaker","audio","solar","muted"],
		variants: ["linear"],
		component: VolumeOff,
	},
	{
		name: "wallet",
		pascalName: "Wallet",
		category: "actions",
		tags: ["money","payment","finance","cash","solar"],
		variants: ["linear"],
		component: Wallet,
	},
	{
		name: "widget",
		pascalName: "Widget",
		category: "layout",
		tags: ["grid","dashboard","layout","apps","solar"],
		variants: ["linear"],
		component: Widget,
	},
	{
		name: "widget-add",
		pascalName: "WidgetAdd",
		category: "layout",
		tags: ["widget","add","plus","grid","dashboard","layout","solar"],
		variants: ["linear"],
		component: WidgetAdd,
	},
	{
		name: "widget-square",
		pascalName: "WidgetSquare",
		category: "layout",
		tags: ["widget","grid","dashboard","layout","apps","square","solar"],
		variants: ["linear"],
		component: WidgetSquare,
	},
	{
		name: "widget-square-add",
		pascalName: "WidgetSquareAdd",
		category: "layout",
		tags: ["widget","add","plus","grid","dashboard","layout","square","solar"],
		variants: ["linear"],
		component: WidgetSquareAdd,
	},
	{
		name: "windsurf",
		pascalName: "Windsurf",
		category: "social",
		tags: ["ai","code","editor","brand"],
		variants: ["linear"],
		component: Windsurf,
	},
	{
		name: "x",
		pascalName: "X",
		category: "social",
		tags: [],
		variants: ["linear"],
		component: X,
	},
	{
		name: "xai",
		pascalName: "Xai",
		category: "social",
		tags: ["ai","brand"],
		variants: ["linear"],
		component: Xai,
	},
	{
		name: "youtube",
		pascalName: "Youtube",
		category: "social",
		tags: ["brand","youtube","video","google"],
		variants: ["bold"],
		component: Youtube,
	},
	{
		name: "zai",
		pascalName: "Zai",
		category: "social",
		tags: ["z.ai","ai","brand"],
		variants: ["bold"],
		component: Zai,
	},
	{
		name: "zoom-in",
		pascalName: "ZoomIn",
		category: "actions",
		tags: ["magnifier","magnifier-zoom-in","zoom-in","search","enlarge","plus","solar","search-plus","SearchPlus"],
		variants: ["linear"],
		component: ZoomIn,
	},
	{
		name: "zoom-out",
		pascalName: "ZoomOut",
		category: "actions",
		tags: ["magnifier","minimalistic-magnifier-zoom-out","zoom-out","search","shrink","minus","solar","search-minus","SearchMinus"],
		variants: ["linear"],
		component: ZoomOut,
	},
];
