/* Generated by scripts/build-icons.ts. Do not edit. */
import type { HoneyIcon } from "./create-icon";

export type CatalogItem = {
	name: string;
	pascalName: string;
	category: string;
	tags: string[];
	component: HoneyIcon;
};

export const catalog: CatalogItem[] = [];
