/* Generated by scripts/build-icons.ts. Do not edit. */
import type { HoneyIcon } from "./create-icon.js";
import type { IconCategory } from "./categories.js";
import type { IconVariant } from "./types.js";
import { Activity } from "./icons/activity.js";
import { Add } from "./icons/add.js";
import { Alarm } from "./icons/alarm.js";
import { Album } from "./icons/album.js";
import { AlertTriangle } from "./icons/alert-triangle.js";
import { Analytics } from "./icons/analytics.js";
import { Anthropic } from "./icons/anthropic.js";
import { Antigravity } from "./icons/antigravity.js";
import { Archive } from "./icons/archive.js";
import { ArchiveAlt } from "./icons/archive-alt.js";
import { ArchiveUp } from "./icons/archive-up.js";
import { ArrowDown } from "./icons/arrow-down.js";
import { ArrowDownLeft } from "./icons/arrow-down-left.js";
import { ArrowDownRight } from "./icons/arrow-down-right.js";
import { ArrowLeft } from "./icons/arrow-left.js";
import { ArrowRight } from "./icons/arrow-right.js";
import { ArrowUp } from "./icons/arrow-up.js";
import { ArrowUpLeft } from "./icons/arrow-up-left.js";
import { ArrowUpRight } from "./icons/arrow-up-right.js";
import { AtSign } from "./icons/at-sign.js";
import { Battery } from "./icons/battery.js";
import { Bell } from "./icons/bell.js";
import { BellOff } from "./icons/bell-off.js";
import { Bluetooth } from "./icons/bluetooth.js";
import { Bold } from "./icons/bold.js";
import { Bolt } from "./icons/bolt.js";
import { BookOpen } from "./icons/book-open.js";
import { Bookmark } from "./icons/bookmark.js";
import { Bookmarks } from "./icons/bookmarks.js";
import { Brain } from "./icons/brain.js";
import { Briefcase } from "./icons/briefcase.js";
import { Broadcast } from "./icons/broadcast.js";
import { Bug } from "./icons/bug.js";
import { Building } from "./icons/building.js";
import { Bun } from "./icons/bun.js";
import { Calculator } from "./icons/calculator.js";
import { Calendar } from "./icons/calendar.js";
import { CalendarAdd } from "./icons/calendar-add.js";
import { CalendarMark } from "./icons/calendar-mark.js";
import { CalendarRemove } from "./icons/calendar-remove.js";
import { CalendarSearch } from "./icons/calendar-search.js";
import { CalendarX } from "./icons/calendar-x.js";
import { Camera } from "./icons/camera.js";
import { Card } from "./icons/card.js";
import { Cart } from "./icons/cart.js";
import { CartBag } from "./icons/cart-bag.js";
import { CartLarge } from "./icons/cart-large.js";
import { Chair } from "./icons/chair.js";
import { ChartAnalysis } from "./icons/chart-analysis.js";
import { Chat } from "./icons/chat.js";
import { Check } from "./icons/check.js";
import { CheckDouble } from "./icons/check-double.js";
import { ChevronDown } from "./icons/chevron-down.js";
import { ChevronLeft } from "./icons/chevron-left.js";
import { ChevronRight } from "./icons/chevron-right.js";
import { ChevronUp } from "./icons/chevron-up.js";
import { ChevronsDown } from "./icons/chevrons-down.js";
import { ChevronsLeft } from "./icons/chevrons-left.js";
import { ChevronsRight } from "./icons/chevrons-right.js";
import { ChevronsUp } from "./icons/chevrons-up.js";
import { Chrome } from "./icons/chrome.js";
import { Clapperboard } from "./icons/clapperboard.js";
import { ClapperboardText } from "./icons/clapperboard-text.js";
import { ClaudeAi } from "./icons/claude-ai.js";
import { ClaudeCode } from "./icons/claude-code.js";
import { Clipboard } from "./icons/clipboard.js";
import { ClipboardAdd } from "./icons/clipboard-add.js";
import { ClipboardCheck } from "./icons/clipboard-check.js";
import { ClipboardRemove } from "./icons/clipboard-remove.js";
import { Clock } from "./icons/clock.js";
import { Close } from "./icons/close.js";
import { Cloud } from "./icons/cloud.js";
import { CloudDownload } from "./icons/cloud-download.js";
import { CloudUpload } from "./icons/cloud-upload.js";
import { Code } from "./icons/code.js";
import { Codex } from "./icons/codex.js";
import { Command } from "./icons/command.js";
import { Computer } from "./icons/computer.js";
import { Connect } from "./icons/connect.js";
import { Copy } from "./icons/copy.js";
import { Crop } from "./icons/crop.js";
import { Cursor } from "./icons/cursor.js";
import { Database } from "./icons/database.js";
import { Deepseek } from "./icons/deepseek.js";
import { Devin } from "./icons/devin.js";
import { Diamond } from "./icons/diamond.js";
import { Discord } from "./icons/discord.js";
import { Dislike } from "./icons/dislike.js";
import { Document } from "./icons/document.js";
import { DoorOpen } from "./icons/door-open.js";
import { Download } from "./icons/download.js";
import { Edit } from "./icons/edit.js";
import { EditOff } from "./icons/edit-off.js";
import { Email } from "./icons/email.js";
import { ExternalLink } from "./icons/external-link.js";
import { Eye } from "./icons/eye.js";
import { EyeClosed } from "./icons/eye-closed.js";
import { EyeOff } from "./icons/eye-off.js";
import { Facebook } from "./icons/facebook.js";
import { Figma } from "./icons/figma.js";
import { File } from "./icons/file.js";
import { FileAdd } from "./icons/file-add.js";
import { FileCode } from "./icons/file-code.js";
import { FileRemove } from "./icons/file-remove.js";
import { FileText } from "./icons/file-text.js";
import { Filter } from "./icons/filter.js";
import { Fingerprint } from "./icons/fingerprint.js";
import { Flag } from "./icons/flag.js";
import { Folder } from "./icons/folder.js";
import { FolderAdd } from "./icons/folder-add.js";
import { FolderOpen } from "./icons/folder-open.js";
import { FolderTree } from "./icons/folder-tree.js";
import { FolderWithFiles } from "./icons/folder-with-files.js";
import { Folders } from "./icons/folders.js";
import { Forward } from "./icons/forward.js";
import { Gamepad } from "./icons/gamepad.js";
import { Gemini } from "./icons/gemini.js";
import { Gift } from "./icons/gift.js";
import { Git } from "./icons/git.js";
import { GitBranch } from "./icons/git-branch.js";
import { GitDiff } from "./icons/git-diff.js";
import { GitFork } from "./icons/git-fork.js";
import { GitGraph } from "./icons/git-graph.js";
import { GitPullRequest } from "./icons/git-pull-request.js";
import { Github } from "./icons/github.js";
import { GithubCopilot } from "./icons/github-copilot.js";
import { Globe } from "./icons/globe.js";
import { Google } from "./icons/google.js";
import { GripHorizontal } from "./icons/grip-horizontal.js";
import { GripVertical } from "./icons/grip-vertical.js";
import { Grok } from "./icons/grok.js";
import { Hand } from "./icons/hand.js";
import { HandWave } from "./icons/hand-wave.js";
import { Hashtag } from "./icons/hashtag.js";
import { Heading } from "./icons/heading.js";
import { Headphones } from "./icons/headphones.js";
import { Heart } from "./icons/heart.js";
import { History } from "./icons/history.js";
import { Home } from "./icons/home.js";
import { HomeAngle } from "./icons/home-angle.js";
import { Image } from "./icons/image.js";
import { ImageAdd } from "./icons/image-add.js";
import { ImageEdit } from "./icons/image-edit.js";
import { Import } from "./icons/import.js";
import { Inbox } from "./icons/inbox.js";
import { IncomingCall } from "./icons/incoming-call.js";
import { InfoSquare } from "./icons/info-square.js";
import { Instagram } from "./icons/instagram.js";
import { Integration } from "./icons/integration.js";
import { Italic } from "./icons/italic.js";
import { Kanban } from "./icons/kanban.js";
import { Key } from "./icons/key.js";
import { Keyboard } from "./icons/keyboard.js";
import { Kimi } from "./icons/kimi.js";
import { Layers } from "./icons/layers.js";
import { LayoutAlignBottom } from "./icons/layout-align-bottom.js";
import { LayoutAlignLeft } from "./icons/layout-align-left.js";
import { LayoutAlignRight } from "./icons/layout-align-right.js";
import { LayoutAlignTop } from "./icons/layout-align-top.js";
import { LifeBuoy } from "./icons/life-buoy.js";
import { Lightbulb } from "./icons/lightbulb.js";
import { Lightning } from "./icons/lightning.js";
import { Like } from "./icons/like.js";
import { Link } from "./icons/link.js";
import { Linkedin } from "./icons/linkedin.js";
import { List } from "./icons/list.js";
import { ListChecks } from "./icons/list-checks.js";
import { ListDash } from "./icons/list-dash.js";
import { ListDown } from "./icons/list-down.js";
import { ListFilter } from "./icons/list-filter.js";
import { ListUp } from "./icons/list-up.js";
import { Lock } from "./icons/lock.js";
import { LockOpen } from "./icons/lock-open.js";
import { Login } from "./icons/login.js";
import { Logout } from "./icons/logout.js";
import { Map } from "./icons/map.js";
import { MapArrowDown } from "./icons/map-arrow-down.js";
import { MapArrowLeft } from "./icons/map-arrow-left.js";
import { MapArrowRight } from "./icons/map-arrow-right.js";
import { MapArrowUp } from "./icons/map-arrow-up.js";
import { MapFolded } from "./icons/map-folded.js";
import { MapPin } from "./icons/map-pin.js";
import { MarketAnalysis } from "./icons/market-analysis.js";
import { Maximize } from "./icons/maximize.js";
import { Menu } from "./icons/menu.js";
import { MetaAi } from "./icons/meta-ai.js";
import { Microphone } from "./icons/microphone.js";
import { MicrophoneOff } from "./icons/microphone-off.js";
import { MicrosoftCopilot } from "./icons/microsoft-copilot.js";
import { Minimize } from "./icons/minimize.js";
import { Minus } from "./icons/minus.js";
import { Mistral } from "./icons/mistral.js";
import { Moon } from "./icons/moon.js";
import { MoreHorizontal } from "./icons/more-horizontal.js";
import { MoreVertical } from "./icons/more-vertical.js";
import { Move } from "./icons/move.js";
import { MusicNote } from "./icons/music-note.js";
import { Navigation } from "./icons/navigation.js";
import { Notebook } from "./icons/notebook.js";
import { Npm } from "./icons/npm.js";
import { Nvidia } from "./icons/nvidia.js";
import { OctagonX } from "./icons/octagon-x.js";
import { Openai } from "./icons/openai.js";
import { Openclaw } from "./icons/openclaw.js";
import { Opencode } from "./icons/opencode.js";
import { OutgoingCall } from "./icons/outgoing-call.js";
import { Package } from "./icons/package.js";
import { Palette } from "./icons/palette.js";
import { PaperPlane } from "./icons/paper-plane.js";
import { Paperclip } from "./icons/paperclip.js";
import { Pause } from "./icons/pause.js";
import { Pen } from "./icons/pen.js";
import { Perplexity } from "./icons/perplexity.js";
import { Phone } from "./icons/phone.js";
import { Pin } from "./icons/pin.js";
import { Pinterest } from "./icons/pinterest.js";
import { Pip } from "./icons/pip.js";
import { Play } from "./icons/play.js";
import { PlayMini } from "./icons/play-mini.js";
import { Power } from "./icons/power.js";
import { Printer } from "./icons/printer.js";
import { Puzzle } from "./icons/puzzle.js";
import { QrCode } from "./icons/qr-code.js";
import { Quote } from "./icons/quote.js";
import { Qwen } from "./icons/qwen.js";
import { React } from "./icons/react.js";
import { Reddit } from "./icons/reddit.js";
import { Redo } from "./icons/redo.js";
import { Reorder } from "./icons/reorder.js";
import { Repeat } from "./icons/repeat.js";
import { Reply } from "./icons/reply.js";
import { ResourcesAdd } from "./icons/resources-add.js";
import { Rhombus } from "./icons/rhombus.js";
import { Rocket } from "./icons/rocket.js";
import { Sad } from "./icons/sad.js";
import { Search } from "./icons/search.js";
import { Send } from "./icons/send.js";
import { Server } from "./icons/server.js";
import { Settings } from "./icons/settings.js";
import { Share } from "./icons/share.js";
import { ShieldAdd } from "./icons/shield-add.js";
import { SidebarBottom } from "./icons/sidebar-bottom.js";
import { SidebarLeft } from "./icons/sidebar-left.js";
import { SidebarRight } from "./icons/sidebar-right.js";
import { SidebarTop } from "./icons/sidebar-top.js";
import { SimCard } from "./icons/sim-card.js";
import { Slack } from "./icons/slack.js";
import { Slash } from "./icons/slash.js";
import { SlidersHorizontal } from "./icons/sliders-horizontal.js";
import { SlidersHorizontalAlt } from "./icons/sliders-horizontal-alt.js";
import { SlidersVertical } from "./icons/sliders-vertical.js";
import { SlidersVerticalAlt } from "./icons/sliders-vertical-alt.js";
import { Smartphone } from "./icons/smartphone.js";
import { Smile } from "./icons/smile.js";
import { Snapchat } from "./icons/snapchat.js";
import { Soundwave } from "./icons/soundwave.js";
import { Sparkles } from "./icons/sparkles.js";
import { Spinner } from "./icons/spinner.js";
import { SpinnerArc } from "./icons/spinner-arc.js";
import { SpinnerDiagonal } from "./icons/spinner-diagonal.js";
import { SpinnerOrbit } from "./icons/spinner-orbit.js";
import { SpinnerWave } from "./icons/spinner-wave.js";
import { SquarePen } from "./icons/square-pen.js";
import { Star } from "./icons/star.js";
import { StarOff } from "./icons/star-off.js";
import { Sticker } from "./icons/sticker.js";
import { Stop } from "./icons/stop.js";
import { Stopwatch } from "./icons/stopwatch.js";
import { Strikethrough } from "./icons/strikethrough.js";
import { Suitcase } from "./icons/suitcase.js";
import { Sun } from "./icons/sun.js";
import { Supabase } from "./icons/supabase.js";
import { Table } from "./icons/table.js";
import { Tablet } from "./icons/tablet.js";
import { Telegram } from "./icons/telegram.js";
import { Terminal } from "./icons/terminal.js";
import { TextAlignCenter } from "./icons/text-align-center.js";
import { TextAlignJustifyLeft } from "./icons/text-align-justify-left.js";
import { TextAlignJustifyRight } from "./icons/text-align-justify-right.js";
import { TextAlignLeft } from "./icons/text-align-left.js";
import { TextAlignRight } from "./icons/text-align-right.js";
import { TextUnderline } from "./icons/text-underline.js";
import { Threads } from "./icons/threads.js";
import { ThreeSquares } from "./icons/three-squares.js";
import { Ticket } from "./icons/ticket.js";
import { TicketDiscount } from "./icons/ticket-discount.js";
import { Tiktok } from "./icons/tiktok.js";
import { TransferHorizontal } from "./icons/transfer-horizontal.js";
import { TransferVertical } from "./icons/transfer-vertical.js";
import { Trash } from "./icons/trash.js";
import { Truck } from "./icons/truck.js";
import { Twitter } from "./icons/twitter.js";
import { Typescript } from "./icons/typescript.js";
import { Undo } from "./icons/undo.js";
import { UnfoldLess } from "./icons/unfold-less.js";
import { UnfoldMore } from "./icons/unfold-more.js";
import { Upload } from "./icons/upload.js";
import { User } from "./icons/user.js";
import { UserAdd } from "./icons/user-add.js";
import { UserCheck } from "./icons/user-check.js";
import { UserGroup } from "./icons/user-group.js";
import { UserRemove } from "./icons/user-remove.js";
import { UserX } from "./icons/user-x.js";
import { Vercel } from "./icons/vercel.js";
import { VerifiedCheck } from "./icons/verified-check.js";
import { VideoCamera } from "./icons/video-camera.js";
import { VideoFrame } from "./icons/video-frame.js";
import { VolumeHigh } from "./icons/volume-high.js";
import { VolumeLow } from "./icons/volume-low.js";
import { VolumeOff } from "./icons/volume-off.js";
import { Wallet } from "./icons/wallet.js";
import { Waves } from "./icons/waves.js";
import { Widget } from "./icons/widget.js";
import { WidgetAdd } from "./icons/widget-add.js";
import { WidgetSquare } from "./icons/widget-square.js";
import { WidgetSquareAdd } from "./icons/widget-square-add.js";
import { Wifi } from "./icons/wifi.js";
import { Windsurf } from "./icons/windsurf.js";
import { X } from "./icons/x.js";
import { Xai } from "./icons/xai.js";
import { Youtube } from "./icons/youtube.js";
import { Zai } from "./icons/zai.js";
import { ZoomIn } from "./icons/zoom-in.js";
import { ZoomOut } from "./icons/zoom-out.js";

export type { IconCategory } from "./categories.js";
export { ICON_CATEGORIES } from "./categories.js";

export type CatalogItem = {
	name: string;
	pascalName: string;
	category: IconCategory;
	tags: string[];
	variants: IconVariant[];
	component: HoneyIcon;
};

export const catalog: CatalogItem[] = [
	{
		name: "activity",
		pascalName: "Activity",
		category: "charts",
		tags: ["activity","pulse","wave","monitor","heartbeat"],
		variants: ["linear"],
		component: Activity,
	},
	{
		name: "add",
		pascalName: "Add",
		category: "actions",
		tags: ["plus","new","create","solar"],
		variants: ["linear"],
		component: Add,
	},
	{
		name: "alarm",
		pascalName: "Alarm",
		category: "time",
		tags: ["alarm","clock","reminder","time"],
		variants: ["linear"],
		component: Alarm,
	},
	{
		name: "album",
		pascalName: "Album",
		category: "media",
		tags: ["album","photos","gallery","images"],
		variants: ["linear"],
		component: Album,
	},
	{
		name: "alert-triangle",
		pascalName: "AlertTriangle",
		category: "status",
		tags: ["warning","alert","triangle","error","danger-triangle","solar","danger"],
		variants: ["linear"],
		component: AlertTriangle,
	},
	{
		name: "analytics",
		pascalName: "Analytics",
		category: "charts",
		tags: ["analytics","analytics-03","chart","bars","statistics","data","hugeicons"],
		variants: ["linear"],
		component: Analytics,
	},
	{
		name: "anthropic",
		pascalName: "Anthropic",
		category: "brands",
		tags: ["claude","ai","brand"],
		variants: ["bold"],
		component: Anthropic,
	},
	{
		name: "antigravity",
		pascalName: "Antigravity",
		category: "brands",
		tags: ["ai","code","editor","brand"],
		variants: ["bold"],
		component: Antigravity,
	},
	{
		name: "archive",
		pascalName: "Archive",
		category: "files",
		tags: ["library","collection","stack","archive","files","solar","pallet"],
		variants: ["linear"],
		component: Archive,
	},
	{
		name: "archive-alt",
		pascalName: "ArchiveAlt",
		category: "files",
		tags: ["archive","box","storage","done","check","archive-minimalistic","solar"],
		variants: ["linear"],
		component: ArchiveAlt,
	},
	{
		name: "archive-up",
		pascalName: "ArchiveUp",
		category: "files",
		tags: ["archive","archive-up-minimalistic","unarchive","restore","box","up","solar"],
		variants: ["linear"],
		component: ArchiveUp,
	},
	{
		name: "arrow-down",
		pascalName: "ArrowDown",
		category: "arrows",
		tags: ["arrow","down","direction","navigation","arrow-down-02","hugeicons","ArrowDown02"],
		variants: ["linear"],
		component: ArrowDown,
	},
	{
		name: "arrow-down-left",
		pascalName: "ArrowDownLeft",
		category: "arrows",
		tags: ["arrow","down-left","direction","navigation","arrow-down-left-01","hugeicons"],
		variants: ["linear"],
		component: ArrowDownLeft,
	},
	{
		name: "arrow-down-right",
		pascalName: "ArrowDownRight",
		category: "arrows",
		tags: ["arrow","down-right","direction","navigation","arrow-down-right-01","hugeicons"],
		variants: ["linear"],
		component: ArrowDownRight,
	},
	{
		name: "arrow-left",
		pascalName: "ArrowLeft",
		category: "arrows",
		tags: ["arrow","left","direction","navigation","arrow-left-02","hugeicons","ArrowLeft02"],
		variants: ["linear"],
		component: ArrowLeft,
	},
	{
		name: "arrow-right",
		pascalName: "ArrowRight",
		category: "arrows",
		tags: ["arrow","right","direction","navigation","arrow-right-02","hugeicons","ArrowRight02"],
		variants: ["linear"],
		component: ArrowRight,
	},
	{
		name: "arrow-up",
		pascalName: "ArrowUp",
		category: "arrows",
		tags: ["arrow","up","direction","navigation","arrow-up-02","hugeicons","ArrowUp02"],
		variants: ["linear"],
		component: ArrowUp,
	},
	{
		name: "arrow-up-left",
		pascalName: "ArrowUpLeft",
		category: "arrows",
		tags: ["arrow","up-left","direction","navigation","arrow-up-left-01","hugeicons"],
		variants: ["linear"],
		component: ArrowUpLeft,
	},
	{
		name: "arrow-up-right",
		pascalName: "ArrowUpRight",
		category: "arrows",
		tags: ["arrow","up-right","direction","navigation","arrow-up-right-01","hugeicons"],
		variants: ["linear"],
		component: ArrowUpRight,
	},
	{
		name: "at-sign",
		pascalName: "AtSign",
		category: "chat",
		tags: ["at-sign","at","mention","email","contact"],
		variants: ["linear"],
		component: AtSign,
	},
	{
		name: "battery",
		pascalName: "Battery",
		category: "devices",
		tags: ["battery","power","charge","half","solar"],
		variants: ["linear"],
		component: Battery,
	},
	{
		name: "bell",
		pascalName: "Bell",
		category: "status",
		tags: ["bell","notification","alert","solar"],
		variants: ["linear"],
		component: Bell,
	},
	{
		name: "bell-off",
		pascalName: "BellOff",
		category: "status",
		tags: ["bell","notifications","off","mute","silent"],
		variants: ["linear"],
		component: BellOff,
	},
	{
		name: "bluetooth",
		pascalName: "Bluetooth",
		category: "devices",
		tags: ["bluetooth","wireless","connection","solar"],
		variants: ["linear"],
		component: Bluetooth,
	},
	{
		name: "bold",
		pascalName: "Bold",
		category: "editor",
		tags: ["bold","text","format","editor","hugeicons"],
		variants: ["linear"],
		component: Bold,
	},
	{
		name: "bolt",
		pascalName: "Bolt",
		category: "status",
		tags: ["bolt","lightning","flash","energy","power","zap","solar"],
		variants: ["linear"],
		component: Bolt,
	},
	{
		name: "book-open",
		pascalName: "BookOpen",
		category: "files",
		tags: ["book","open","read","pages","education"],
		variants: ["linear"],
		component: BookOpen,
	},
	{
		name: "bookmark",
		pascalName: "Bookmark",
		category: "actions",
		tags: ["save","saved","favorite","reading","solar"],
		variants: ["linear"],
		component: Bookmark,
	},
	{
		name: "bookmarks",
		pascalName: "Bookmarks",
		category: "actions",
		tags: ["bookmarks","save","saved","collection"],
		variants: ["linear"],
		component: Bookmarks,
	},
	{
		name: "brain",
		pascalName: "Brain",
		category: "ai",
		tags: ["ai","brain","intelligence","neural","ai-brain-01","hugeicons","ai-brain"],
		variants: ["linear"],
		component: Brain,
	},
	{
		name: "briefcase",
		pascalName: "Briefcase",
		category: "objects",
		tags: ["briefcase","case","work","business","bag"],
		variants: ["linear"],
		component: Briefcase,
	},
	{
		name: "broadcast",
		pascalName: "Broadcast",
		category: "status",
		tags: ["broadcast","radar","signal","wireless","radio","transmission"],
		variants: ["linear"],
		component: Broadcast,
	},
	{
		name: "bug",
		pascalName: "Bug",
		category: "development",
		tags: ["bug","insect","debug","issue"],
		variants: ["linear"],
		component: Bug,
	},
	{
		name: "building",
		pascalName: "Building",
		category: "maps",
		tags: ["building","office","business","company","city","architecture","hugeicons"],
		variants: ["linear"],
		component: Building,
	},
	{
		name: "bun",
		pascalName: "Bun",
		category: "brands",
		tags: ["javascript","runtime","brand"],
		variants: ["bold"],
		component: Bun,
	},
	{
		name: "calculator",
		pascalName: "Calculator",
		category: "commerce",
		tags: ["calculator","math","arithmetic","calculate","solar"],
		variants: ["linear"],
		component: Calculator,
	},
	{
		name: "calendar",
		pascalName: "Calendar",
		category: "time",
		tags: ["calendar","date","schedule","event","month","hugeicons","calendar-03","Calendar03"],
		variants: ["linear"],
		component: Calendar,
	},
	{
		name: "calendar-add",
		pascalName: "CalendarAdd",
		category: "time",
		tags: ["calendar","date","event","add","plus","calendar-plus","new","schedule","solar"],
		variants: ["linear"],
		component: CalendarAdd,
	},
	{
		name: "calendar-mark",
		pascalName: "CalendarMark",
		category: "time",
		tags: ["calendar","date","event","mark","selected","today","solar"],
		variants: ["linear"],
		component: CalendarMark,
	},
	{
		name: "calendar-remove",
		pascalName: "CalendarRemove",
		category: "time",
		tags: ["calendar","date","event","remove","minus","calendar-minus","schedule","solar"],
		variants: ["linear"],
		component: CalendarRemove,
	},
	{
		name: "calendar-search",
		pascalName: "CalendarSearch",
		category: "time",
		tags: ["calendar","search","date","schedule","solar"],
		variants: ["linear"],
		component: CalendarSearch,
	},
	{
		name: "calendar-x",
		pascalName: "CalendarX",
		category: "time",
		tags: ["calendar","date","event","x","close","cancel","schedule","solar"],
		variants: ["linear"],
		component: CalendarX,
	},
	{
		name: "camera",
		pascalName: "Camera",
		category: "media",
		tags: ["camera","photo","picture","capture","snapshot"],
		variants: ["linear"],
		component: Camera,
	},
	{
		name: "card",
		pascalName: "Card",
		category: "commerce",
		tags: ["credit-card","debit-card","payment","bank","finance","solar"],
		variants: ["linear"],
		component: Card,
	},
	{
		name: "cart",
		pascalName: "Cart",
		category: "commerce",
		tags: ["basket","shopping","store","solar"],
		variants: ["linear"],
		component: Cart,
	},
	{
		name: "cart-bag",
		pascalName: "CartBag",
		category: "commerce",
		tags: ["bag","shopping-bag","shopping","store","purchase","checkout","solar"],
		variants: ["linear"],
		component: CartBag,
	},
	{
		name: "cart-large",
		pascalName: "CartLarge",
		category: "commerce",
		tags: ["cart","shopping-cart","trolley","checkout","store","shopping","solar"],
		variants: ["linear"],
		component: CartLarge,
	},
	{
		name: "chair",
		pascalName: "Chair",
		category: "objects",
		tags: ["chair","seat","furniture"],
		variants: ["linear"],
		component: Chair,
	},
	{
		name: "chart-analysis",
		pascalName: "ChartAnalysis",
		category: "charts",
		tags: ["chart","analysis","trend","growth","statistics","hugeicons"],
		variants: ["linear"],
		component: ChartAnalysis,
	},
	{
		name: "chat",
		pascalName: "Chat",
		category: "chat",
		tags: ["chat","chat-01","message","conversation","bubble","hugeicons"],
		variants: ["linear"],
		component: Chat,
	},
	{
		name: "check",
		pascalName: "Check",
		category: "status",
		tags: ["tick","done","success","confirm","complete","hugeicons"],
		variants: ["linear"],
		component: Check,
	},
	{
		name: "check-double",
		pascalName: "CheckDouble",
		category: "status",
		tags: ["double-check","tick","done","read","receipt","delivered","hugeicons","check-check","CheckCheck"],
		variants: ["linear"],
		component: CheckDouble,
	},
	{
		name: "chevron-down",
		pascalName: "ChevronDown",
		category: "arrows",
		tags: ["chevron","down","bottom","expand","arrow-down-01","hugeicons","arrow-down","ArrowDown"],
		variants: ["linear"],
		component: ChevronDown,
	},
	{
		name: "chevron-left",
		pascalName: "ChevronLeft",
		category: "arrows",
		tags: ["chevron","left","back","previous","arrow-left-01","hugeicons","arrow-left","ArrowLeft"],
		variants: ["linear"],
		component: ChevronLeft,
	},
	{
		name: "chevron-right",
		pascalName: "ChevronRight",
		category: "arrows",
		tags: ["chevron","right","forward","next","arrow-right-01","hugeicons","arrow-right","ArrowRight"],
		variants: ["linear"],
		component: ChevronRight,
	},
	{
		name: "chevron-up",
		pascalName: "ChevronUp",
		category: "arrows",
		tags: ["chevron","up","top","collapse","arrow-up-01","hugeicons","arrow-up","ArrowUp"],
		variants: ["linear"],
		component: ChevronUp,
	},
	{
		name: "chevrons-down",
		pascalName: "ChevronsDown",
		category: "arrows",
		tags: ["chevron","double","down","bottom","hugeicons","arrow-down-double","ArrowDownDouble"],
		variants: ["linear"],
		component: ChevronsDown,
	},
	{
		name: "chevrons-left",
		pascalName: "ChevronsLeft",
		category: "arrows",
		tags: ["chevron","double","left","first","hugeicons","arrow-left-double","ArrowLeftDouble"],
		variants: ["linear"],
		component: ChevronsLeft,
	},
	{
		name: "chevrons-right",
		pascalName: "ChevronsRight",
		category: "arrows",
		tags: ["chevron","double","right","last","hugeicons","arrow-right-double","ArrowRightDouble"],
		variants: ["linear"],
		component: ChevronsRight,
	},
	{
		name: "chevrons-up",
		pascalName: "ChevronsUp",
		category: "arrows",
		tags: ["chevron","double","up","top","hugeicons","arrow-up-double","ArrowUpDouble"],
		variants: ["linear"],
		component: ChevronsUp,
	},
	{
		name: "chrome",
		pascalName: "Chrome",
		category: "brands",
		tags: ["brand","chrome","google","browser"],
		variants: ["bold"],
		component: Chrome,
	},
	{
		name: "clapperboard",
		pascalName: "Clapperboard",
		category: "media",
		tags: ["film","movie","video","play","clapperboard-play","solar"],
		variants: ["linear"],
		component: Clapperboard,
	},
	{
		name: "clapperboard-text",
		pascalName: "ClapperboardText",
		category: "media",
		tags: ["film","movie","video","script","clapperboard","solar"],
		variants: ["linear"],
		component: ClapperboardText,
	},
	{
		name: "claude-ai",
		pascalName: "ClaudeAi",
		category: "brands",
		tags: ["claude","anthropic","ai","assistant","brand"],
		variants: ["bold"],
		component: ClaudeAi,
	},
	{
		name: "claude-code",
		pascalName: "ClaudeCode",
		category: "brands",
		tags: ["claude","anthropic","ai","code","terminal","brand"],
		variants: ["bold"],
		component: ClaudeCode,
	},
	{
		name: "clipboard",
		pascalName: "Clipboard",
		category: "files",
		tags: ["clipboard","copy","paste","board","solar"],
		variants: ["linear"],
		component: Clipboard,
	},
	{
		name: "clipboard-add",
		pascalName: "ClipboardAdd",
		category: "files",
		tags: ["clipboard","add","plus","new","solar"],
		variants: ["linear"],
		component: ClipboardAdd,
	},
	{
		name: "clipboard-check",
		pascalName: "ClipboardCheck",
		category: "files",
		tags: ["clipboard","check","done","complete","tasks","solar"],
		variants: ["linear"],
		component: ClipboardCheck,
	},
	{
		name: "clipboard-remove",
		pascalName: "ClipboardRemove",
		category: "files",
		tags: ["clipboard","minus","remove","delete","clipboard-minus","solar"],
		variants: ["linear"],
		component: ClipboardRemove,
	},
	{
		name: "clock",
		pascalName: "Clock",
		category: "time",
		tags: ["time","hour","schedule","watch"],
		variants: ["linear"],
		component: Clock,
	},
	{
		name: "close",
		pascalName: "Close",
		category: "actions",
		tags: ["dismiss","cancel","cross","x","solar"],
		variants: ["linear"],
		component: Close,
	},
	{
		name: "cloud",
		pascalName: "Cloud",
		category: "files",
		tags: ["storage","weather","online","sync","solar"],
		variants: ["linear"],
		component: Cloud,
	},
	{
		name: "cloud-download",
		pascalName: "CloudDownload",
		category: "files",
		tags: ["cloud","download","storage","save","hugeicons"],
		variants: ["linear"],
		component: CloudDownload,
	},
	{
		name: "cloud-upload",
		pascalName: "CloudUpload",
		category: "files",
		tags: ["cloud","upload","storage","sync","hugeicons"],
		variants: ["linear"],
		component: CloudUpload,
	},
	{
		name: "code",
		pascalName: "Code",
		category: "development",
		tags: ["programming","developer","syntax","brackets","solar"],
		variants: ["linear"],
		component: Code,
	},
	{
		name: "codex",
		pascalName: "Codex",
		category: "brands",
		tags: ["openai","ai","coding","brand"],
		variants: ["bold"],
		component: Codex,
	},
	{
		name: "command",
		pascalName: "Command",
		category: "development",
		tags: ["keyboard","shortcut","cmd","mac","solar"],
		variants: ["linear"],
		component: Command,
	},
	{
		name: "computer",
		pascalName: "Computer",
		category: "devices",
		tags: ["monitor","desktop","screen","display","device","hugeicons"],
		variants: ["linear","bold"],
		component: Computer,
	},
	{
		name: "connect",
		pascalName: "Connect",
		category: "actions",
		tags: ["connect","connection","plug","cable","link","hugeicons"],
		variants: ["linear"],
		component: Connect,
	},
	{
		name: "copy",
		pascalName: "Copy",
		category: "actions",
		tags: ["copy","duplicate","clipboard","copy-01","hugeicons"],
		variants: ["linear"],
		component: Copy,
	},
	{
		name: "crop",
		pascalName: "Crop",
		category: "editor",
		tags: ["crop","image","resize","trim","hugeicons"],
		variants: ["linear"],
		component: Crop,
	},
	{
		name: "cursor",
		pascalName: "Cursor",
		category: "brands",
		tags: ["brand","cursor","ai","code","editor"],
		variants: ["bold"],
		component: Cursor,
	},
	{
		name: "database",
		pascalName: "Database",
		category: "development",
		tags: ["database","storage","data","server","solar"],
		variants: ["linear"],
		component: Database,
	},
	{
		name: "deepseek",
		pascalName: "Deepseek",
		category: "brands",
		tags: ["ai","whale","brand"],
		variants: ["bold"],
		component: Deepseek,
	},
	{
		name: "devin",
		pascalName: "Devin",
		category: "brands",
		tags: ["ai","code","agent","brand"],
		variants: ["bold"],
		component: Devin,
	},
	{
		name: "diamond",
		pascalName: "Diamond",
		category: "shapes",
		tags: ["diamond","shape","geometry","rhombus","hugeicons"],
		variants: ["linear"],
		component: Diamond,
	},
	{
		name: "discord",
		pascalName: "Discord",
		category: "brands",
		tags: ["chat","community","brand"],
		variants: ["bold"],
		component: Discord,
	},
	{
		name: "dislike",
		pascalName: "Dislike",
		category: "actions",
		tags: ["thumbs-down","disapprove","feedback","hugeicons"],
		variants: ["linear"],
		component: Dislike,
	},
	{
		name: "document",
		pascalName: "Document",
		category: "files",
		tags: ["document","document-text","text","paper","notes","solar"],
		variants: ["linear"],
		component: Document,
	},
	{
		name: "door-open",
		pascalName: "DoorOpen",
		category: "actions",
		tags: ["door","leave","logout","sign-out","solar","exit"],
		variants: ["linear"],
		component: DoorOpen,
	},
	{
		name: "download",
		pascalName: "Download",
		category: "actions",
		tags: ["download","tray","import","incoming","arrow"],
		variants: ["linear"],
		component: Download,
	},
	{
		name: "edit",
		pascalName: "Edit",
		category: "editor",
		tags: ["edit","pencil","write","draw","hugeicons","edit-01","Edit01"],
		variants: ["linear"],
		component: Edit,
	},
	{
		name: "edit-off",
		pascalName: "EditOff",
		category: "editor",
		tags: ["edit","disabled","read-only","pencil","hugeicons"],
		variants: ["linear"],
		component: EditOff,
	},
	{
		name: "email",
		pascalName: "Email",
		category: "chat",
		tags: ["mail","letter","envelope","message","solar"],
		variants: ["linear"],
		component: Email,
	},
	{
		name: "external-link",
		pascalName: "ExternalLink",
		category: "actions",
		tags: ["external-link","open","new-tab","link","arrow","solar"],
		variants: ["linear"],
		component: ExternalLink,
	},
	{
		name: "eye",
		pascalName: "Eye",
		category: "actions",
		tags: ["eye","view","visible","show","visibility","solar"],
		variants: ["linear"],
		component: Eye,
	},
	{
		name: "eye-closed",
		pascalName: "EyeClosed",
		category: "actions",
		tags: ["eye-closed","eye","closed","hide","visibility","lashes","solar","eye-off-alt","eyelashes","sleep"],
		variants: ["linear"],
		component: EyeClosed,
	},
	{
		name: "eye-off",
		pascalName: "EyeOff",
		category: "actions",
		tags: ["eye","off","hide","visibility","slash"],
		variants: ["linear"],
		component: EyeOff,
	},
	{
		name: "facebook",
		pascalName: "Facebook",
		category: "brands",
		tags: ["meta","social","brand"],
		variants: ["bold"],
		component: Facebook,
	},
	{
		name: "figma",
		pascalName: "Figma",
		category: "brands",
		tags: ["figma","design","brand","solar"],
		variants: ["linear"],
		component: Figma,
	},
	{
		name: "file",
		pascalName: "File",
		category: "files",
		tags: ["document","page","paper","blank","solar"],
		variants: ["linear"],
		component: File,
	},
	{
		name: "file-add",
		pascalName: "FileAdd",
		category: "files",
		tags: ["document","file","solar","new","create","add","plus"],
		variants: ["linear"],
		component: FileAdd,
	},
	{
		name: "file-code",
		pascalName: "FileCode",
		category: "files",
		tags: ["document","code","source","programming","code-file","solar"],
		variants: ["linear"],
		component: FileCode,
	},
	{
		name: "file-remove",
		pascalName: "FileRemove",
		category: "files",
		tags: ["document","file","solar","remove","delete","minus"],
		variants: ["linear"],
		component: FileRemove,
	},
	{
		name: "file-text",
		pascalName: "FileText",
		category: "files",
		tags: ["document","page","paper","text","lines","notes","solar"],
		variants: ["linear"],
		component: FileText,
	},
	{
		name: "filter",
		pascalName: "Filter",
		category: "actions",
		tags: ["filter","funnel","refine","sort","solar"],
		variants: ["linear"],
		component: Filter,
	},
	{
		name: "fingerprint",
		pascalName: "Fingerprint",
		category: "security",
		tags: ["fingerprint","biometric","touch-id","identity","security","auth"],
		variants: ["linear"],
		component: Fingerprint,
	},
	{
		name: "flag",
		pascalName: "Flag",
		category: "status",
		tags: ["flag","mark","report","milestone","solar"],
		variants: ["linear"],
		component: Flag,
	},
	{
		name: "folder",
		pascalName: "Folder",
		category: "files",
		tags: ["folder","directory","files","storage","folder-01","Folder01","solar"],
		variants: ["linear"],
		component: Folder,
	},
	{
		name: "folder-add",
		pascalName: "FolderAdd",
		category: "files",
		tags: ["folder","directory","create","new","plus","solar"],
		variants: ["linear"],
		component: FolderAdd,
	},
	{
		name: "folder-open",
		pascalName: "FolderOpen",
		category: "files",
		tags: ["folder","open","directory","files","storage","solar"],
		variants: ["linear"],
		component: FolderOpen,
	},
	{
		name: "folder-tree",
		pascalName: "FolderTree",
		category: "files",
		tags: ["folder","tree","directory","hierarchy","structure","files","solar"],
		variants: ["linear"],
		component: FolderTree,
	},
	{
		name: "folder-with-files",
		pascalName: "FolderWithFiles",
		category: "files",
		tags: ["folder","files","documents","directory","storage","solar"],
		variants: ["linear"],
		component: FolderWithFiles,
	},
	{
		name: "folders",
		pascalName: "Folders",
		category: "files",
		tags: ["folders","folder","files","directory","collection","stack","solar"],
		variants: ["linear"],
		component: Folders,
	},
	{
		name: "forward",
		pascalName: "Forward",
		category: "arrows",
		tags: ["forward","send","message","arrow","right"],
		variants: ["linear"],
		component: Forward,
	},
	{
		name: "gamepad",
		pascalName: "Gamepad",
		category: "media",
		tags: ["gamepad","game","gaming","controller","console","solar"],
		variants: ["linear"],
		component: Gamepad,
	},
	{
		name: "gemini",
		pascalName: "Gemini",
		category: "brands",
		tags: ["google","ai","brand"],
		variants: ["bold"],
		component: Gemini,
	},
	{
		name: "gift",
		pascalName: "Gift",
		category: "commerce",
		tags: ["gift","present","reward","surprise","box","ribbon"],
		variants: ["linear"],
		component: Gift,
	},
	{
		name: "git",
		pascalName: "Git",
		category: "brands",
		tags: ["version-control","repository","code","brand"],
		variants: ["bold"],
		component: Git,
	},
	{
		name: "git-branch",
		pascalName: "GitBranch",
		category: "development",
		tags: ["git","branch","version-control","source-control","solar"],
		variants: ["linear"],
		component: GitBranch,
	},
	{
		name: "git-diff",
		pascalName: "GitDiff",
		category: "development",
		tags: ["git","diff","compare","changes","version-control","solar"],
		variants: ["linear"],
		component: GitDiff,
	},
	{
		name: "git-fork",
		pascalName: "GitFork",
		category: "development",
		tags: ["git","fork","split","version-control","repository","solar"],
		variants: ["linear"],
		component: GitFork,
	},
	{
		name: "git-graph",
		pascalName: "GitGraph",
		category: "development",
		tags: ["git","graph","history","commits","version-control","solar"],
		variants: ["linear"],
		component: GitGraph,
	},
	{
		name: "git-pull-request",
		pascalName: "GitPullRequest",
		category: "development",
		tags: ["git","pull-request","pr","merge","review","version-control","solar"],
		variants: ["linear"],
		component: GitPullRequest,
	},
	{
		name: "github",
		pascalName: "Github",
		category: "brands",
		tags: ["git","code","repository","brand"],
		variants: ["bold"],
		component: Github,
	},
	{
		name: "github-copilot",
		pascalName: "GithubCopilot",
		category: "brands",
		tags: ["brand","github","copilot","ai","code","assistant"],
		variants: ["bold"],
		component: GithubCopilot,
	},
	{
		name: "globe",
		pascalName: "Globe",
		category: "maps",
		tags: ["globe","world","earth","geography","travel","solar"],
		variants: ["linear"],
		component: Globe,
	},
	{
		name: "google",
		pascalName: "Google",
		category: "brands",
		tags: ["search","alphabet","brand"],
		variants: ["bold"],
		component: Google,
	},
	{
		name: "grip-horizontal",
		pascalName: "GripHorizontal",
		category: "editor",
		tags: ["grip","handle","drag","reorder","horizontal","hugeicons"],
		variants: ["linear"],
		component: GripHorizontal,
	},
	{
		name: "grip-vertical",
		pascalName: "GripVertical",
		category: "editor",
		tags: ["grip","handle","drag","reorder","vertical","hugeicons"],
		variants: ["linear"],
		component: GripVertical,
	},
	{
		name: "grok",
		pascalName: "Grok",
		category: "brands",
		tags: ["xai","ai","assistant","brand"],
		variants: ["linear"],
		component: Grok,
	},
	{
		name: "hand",
		pascalName: "Hand",
		category: "actions",
		tags: ["hand","palm","grab","pan","stop","wave"],
		variants: ["linear"],
		component: Hand,
	},
	{
		name: "hand-wave",
		pascalName: "HandWave",
		category: "user",
		tags: ["hand-wave","hand","shake","wave","hello","greeting","hand-shake","waving"],
		variants: ["linear"],
		component: HandWave,
	},
	{
		name: "hashtag",
		pascalName: "Hashtag",
		category: "editor",
		tags: ["hash","tag","number","hastag","solar"],
		variants: ["linear"],
		component: Hashtag,
	},
	{
		name: "heading",
		pascalName: "Heading",
		category: "editor",
		tags: ["heading","title","header","text","editor","hugeicons"],
		variants: ["linear"],
		component: Heading,
	},
	{
		name: "headphones",
		pascalName: "Headphones",
		category: "media",
		tags: ["headphones","audio","music","listen","headphones-round","solar","headphone"],
		variants: ["linear"],
		component: Headphones,
	},
	{
		name: "heart",
		pascalName: "Heart",
		category: "actions",
		tags: ["heart","love","favorite","like","solar"],
		variants: ["linear"],
		component: Heart,
	},
	{
		name: "history",
		pascalName: "History",
		category: "time",
		tags: ["history","recent","clock","time","hugeicons"],
		variants: ["linear"],
		component: History,
	},
	{
		name: "home",
		pascalName: "Home",
		category: "maps",
		tags: [],
		variants: ["linear"],
		component: Home,
	},
	{
		name: "home-angle",
		pascalName: "HomeAngle",
		category: "maps",
		tags: ["home","house","dashboard","main","solar"],
		variants: ["linear"],
		component: HomeAngle,
	},
	{
		name: "image",
		pascalName: "Image",
		category: "media",
		tags: ["image","gallery","photo","picture","media","images"],
		variants: ["linear"],
		component: Image,
	},
	{
		name: "image-add",
		pascalName: "ImageAdd",
		category: "media",
		tags: ["image","gallery","upload","photo","plus","gallery-add","solar","images-add","ImagesAdd"],
		variants: ["linear"],
		component: ImageAdd,
	},
	{
		name: "image-edit",
		pascalName: "ImageEdit",
		category: "media",
		tags: ["image","photo","gallery","edit","pencil","gallery-edit","solar"],
		variants: ["linear"],
		component: ImageEdit,
	},
	{
		name: "import",
		pascalName: "Import",
		category: "actions",
		tags: ["import","inward","arrow","receive","square"],
		variants: ["linear"],
		component: Import,
	},
	{
		name: "inbox",
		pascalName: "Inbox",
		category: "files",
		tags: ["inbox","tray","mail","receive","solar"],
		variants: ["linear"],
		component: Inbox,
	},
	{
		name: "incoming-call",
		pascalName: "IncomingCall",
		category: "chat",
		tags: ["phone","call","incoming","receive","solar"],
		variants: ["linear"],
		component: IncomingCall,
	},
	{
		name: "info-square",
		pascalName: "InfoSquare",
		category: "status",
		tags: ["info","information","help","square","solar"],
		variants: ["linear"],
		component: InfoSquare,
	},
	{
		name: "instagram",
		pascalName: "Instagram",
		category: "brands",
		tags: ["instagram","social","photos","brand","insta"],
		variants: ["linear"],
		component: Instagram,
	},
	{
		name: "integration",
		pascalName: "Integration",
		category: "development",
		tags: ["flow","workflow","connect","nodes","hugeicons"],
		variants: ["linear"],
		component: Integration,
	},
	{
		name: "italic",
		pascalName: "Italic",
		category: "editor",
		tags: ["italic","text","format","editor","hugeicons"],
		variants: ["linear"],
		component: Italic,
	},
	{
		name: "kanban",
		pascalName: "Kanban",
		category: "layout",
		tags: ["kanban","board","columns","tasks","workflow"],
		variants: ["linear"],
		component: Kanban,
	},
	{
		name: "key",
		pascalName: "Key",
		category: "security",
		tags: ["security","access","password","lock","key-minimalistic","solar"],
		variants: ["linear"],
		component: Key,
	},
	{
		name: "keyboard",
		pascalName: "Keyboard",
		category: "devices",
		tags: ["keyboard","keys","type","input","solar"],
		variants: ["linear"],
		component: Keyboard,
	},
	{
		name: "kimi",
		pascalName: "Kimi",
		category: "brands",
		tags: ["ai","assistant","moonshot","brand"],
		variants: ["bold"],
		component: Kimi,
	},
	{
		name: "layers",
		pascalName: "Layers",
		category: "layout",
		tags: ["stack","design","levels","layers-minimalistic","solar"],
		variants: ["linear"],
		component: Layers,
	},
	{
		name: "layout-align-bottom",
		pascalName: "LayoutAlignBottom",
		category: "layout",
		tags: ["layout","align","bottom","position","panel","hugeicons"],
		variants: ["linear"],
		component: LayoutAlignBottom,
	},
	{
		name: "layout-align-left",
		pascalName: "LayoutAlignLeft",
		category: "layout",
		tags: ["layout","align","left","position","panel","hugeicons"],
		variants: ["linear"],
		component: LayoutAlignLeft,
	},
	{
		name: "layout-align-right",
		pascalName: "LayoutAlignRight",
		category: "layout",
		tags: ["layout","align","right","position","panel","hugeicons"],
		variants: ["linear"],
		component: LayoutAlignRight,
	},
	{
		name: "layout-align-top",
		pascalName: "LayoutAlignTop",
		category: "layout",
		tags: ["layout","align","top","position","panel","hugeicons"],
		variants: ["linear"],
		component: LayoutAlignTop,
	},
	{
		name: "life-buoy",
		pascalName: "LifeBuoy",
		category: "objects",
		tags: ["life-buoy","lifebuoy","help","support","rescue","lifesaver"],
		variants: ["linear"],
		component: LifeBuoy,
	},
	{
		name: "lightbulb",
		pascalName: "Lightbulb",
		category: "objects",
		tags: ["lightbulb","light","bulb","idea","inspiration"],
		variants: ["linear"],
		component: Lightbulb,
	},
	{
		name: "lightning",
		pascalName: "Lightning",
		category: "status",
		tags: ["bolt","flash","electricity","energy","power","zap"],
		variants: ["linear"],
		component: Lightning,
	},
	{
		name: "like",
		pascalName: "Like",
		category: "actions",
		tags: ["thumbs-up","approve","feedback","hugeicons"],
		variants: ["linear"],
		component: Like,
	},
	{
		name: "link",
		pascalName: "Link",
		category: "actions",
		tags: ["link","chain","url","connect","diagonal","solar"],
		variants: ["linear"],
		component: Link,
	},
	{
		name: "linkedin",
		pascalName: "Linkedin",
		category: "brands",
		tags: ["brand","linkedin"],
		variants: ["bold"],
		component: Linkedin,
	},
	{
		name: "list",
		pascalName: "List",
		category: "editor",
		tags: ["list","bullets","items","editor","hugeicons"],
		variants: ["linear"],
		component: List,
	},
	{
		name: "list-checks",
		pascalName: "ListChecks",
		category: "editor",
		tags: ["list","checks","checklist","tasks","todo","done"],
		variants: ["linear"],
		component: ListChecks,
	},
	{
		name: "list-dash",
		pascalName: "ListDash",
		category: "editor",
		tags: ["list","dash","left-to-right-list-dash","editor","hugeicons"],
		variants: ["linear"],
		component: ListDash,
	},
	{
		name: "list-down",
		pascalName: "ListDown",
		category: "actions",
		tags: ["list","sort","descending","expand","list-down-minimalistic","solar"],
		variants: ["linear"],
		component: ListDown,
	},
	{
		name: "list-filter",
		pascalName: "ListFilter",
		category: "editor",
		tags: ["list","filter","sort","refine","hugeicons"],
		variants: ["linear"],
		component: ListFilter,
	},
	{
		name: "list-up",
		pascalName: "ListUp",
		category: "actions",
		tags: ["list","sort","ascending","collapse","list-up-minimalistic","solar"],
		variants: ["linear"],
		component: ListUp,
	},
	{
		name: "lock",
		pascalName: "Lock",
		category: "security",
		tags: ["locked","security","private","access","solar"],
		variants: ["linear"],
		component: Lock,
	},
	{
		name: "lock-open",
		pascalName: "LockOpen",
		category: "security",
		tags: ["lock-open","unlock","security","access","solar","lock-unlock","LockUnlock"],
		variants: ["linear"],
		component: LockOpen,
	},
	{
		name: "login",
		pascalName: "Login",
		category: "user",
		tags: ["login","log-in","sign-in","enter","account","arrow"],
		variants: ["linear"],
		component: Login,
	},
	{
		name: "logout",
		pascalName: "Logout",
		category: "user",
		tags: ["sign-out","exit","account","logout-3","solar"],
		variants: ["linear"],
		component: Logout,
	},
	{
		name: "map",
		pascalName: "Map",
		category: "maps",
		tags: ["map","navigation","location","travel","hugeicons"],
		variants: ["linear"],
		component: Map,
	},
	{
		name: "map-arrow-down",
		pascalName: "MapArrowDown",
		category: "arrows",
		tags: ["map","arrow","down","navigation","direction","location","solar"],
		variants: ["linear"],
		component: MapArrowDown,
	},
	{
		name: "map-arrow-left",
		pascalName: "MapArrowLeft",
		category: "arrows",
		tags: ["map","arrow","left","navigation","direction","location","solar"],
		variants: ["linear"],
		component: MapArrowLeft,
	},
	{
		name: "map-arrow-right",
		pascalName: "MapArrowRight",
		category: "arrows",
		tags: ["map","arrow","right","navigation","direction","location","solar"],
		variants: ["linear"],
		component: MapArrowRight,
	},
	{
		name: "map-arrow-up",
		pascalName: "MapArrowUp",
		category: "arrows",
		tags: ["map","arrow","up","navigation","direction","location","solar"],
		variants: ["linear"],
		component: MapArrowUp,
	},
	{
		name: "map-folded",
		pascalName: "MapFolded",
		category: "maps",
		tags: ["map","folded","navigation","travel"],
		variants: ["linear"],
		component: MapFolded,
	},
	{
		name: "map-pin",
		pascalName: "MapPin",
		category: "maps",
		tags: ["map-pin","map","location","pin","point-on-map","solar","map-alt"],
		variants: ["linear"],
		component: MapPin,
	},
	{
		name: "market-analysis",
		pascalName: "MarketAnalysis",
		category: "charts",
		tags: ["market","analysis","chart","candlestick","trading","finance","hugeicons"],
		variants: ["linear"],
		component: MarketAnalysis,
	},
	{
		name: "maximize",
		pascalName: "Maximize",
		category: "arrows",
		tags: ["expand","fullscreen","resize","arrows"],
		variants: ["linear"],
		component: Maximize,
	},
	{
		name: "menu",
		pascalName: "Menu",
		category: "actions",
		tags: ["menu","navigation","bars","hamburger-menu","solar","hamburger"],
		variants: ["linear"],
		component: Menu,
	},
	{
		name: "meta-ai",
		pascalName: "MetaAi",
		category: "brands",
		tags: ["brand","meta","ai","assistant"],
		variants: ["bold"],
		component: MetaAi,
	},
	{
		name: "microphone",
		pascalName: "Microphone",
		category: "media",
		tags: ["mic","record","voice","audio","solar"],
		variants: ["linear"],
		component: Microphone,
	},
	{
		name: "microphone-off",
		pascalName: "MicrophoneOff",
		category: "media",
		tags: ["microphone","mic","off","mute","muted","audio"],
		variants: ["linear"],
		component: MicrophoneOff,
	},
	{
		name: "microsoft-copilot",
		pascalName: "MicrosoftCopilot",
		category: "brands",
		tags: ["microsoft","copilot","ai","assistant","brand","ms-copilot","MsCopilot"],
		variants: ["bold"],
		component: MicrosoftCopilot,
	},
	{
		name: "minimize",
		pascalName: "Minimize",
		category: "arrows",
		tags: ["collapse","shrink","restore","resize","arrows"],
		variants: ["linear"],
		component: Minimize,
	},
	{
		name: "minus",
		pascalName: "Minus",
		category: "actions",
		tags: ["subtract","remove","decrease","solar"],
		variants: ["linear"],
		component: Minus,
	},
	{
		name: "mistral",
		pascalName: "Mistral",
		category: "brands",
		tags: ["ai","brand"],
		variants: ["bold"],
		component: Mistral,
	},
	{
		name: "moon",
		pascalName: "Moon",
		category: "settings",
		tags: ["moon","night","dark","theme","crescent","solar"],
		variants: ["linear","bold"],
		component: Moon,
	},
	{
		name: "more-horizontal",
		pascalName: "MoreHorizontal",
		category: "actions",
		tags: ["ellipsis","menu","options","dots","horizontal","hugeicons"],
		variants: ["linear"],
		component: MoreHorizontal,
	},
	{
		name: "more-vertical",
		pascalName: "MoreVertical",
		category: "actions",
		tags: ["ellipsis","menu","options","dots","vertical","hugeicons"],
		variants: ["linear"],
		component: MoreVertical,
	},
	{
		name: "move",
		pascalName: "Move",
		category: "arrows",
		tags: ["move","drag","arrows","position","hugeicons"],
		variants: ["linear"],
		component: Move,
	},
	{
		name: "music-note",
		pascalName: "MusicNote",
		category: "media",
		tags: ["music","note","song","audio","sound","melody","solar"],
		variants: ["linear"],
		component: MusicNote,
	},
	{
		name: "navigation",
		pascalName: "Navigation",
		category: "maps",
		tags: ["navigation","navigation-03","location","direction","map","pointer","hugeicons"],
		variants: ["linear"],
		component: Navigation,
	},
	{
		name: "notebook",
		pascalName: "Notebook",
		category: "files",
		tags: ["notebook","notebook-minimalistic","book","read","pages","solar"],
		variants: ["linear"],
		component: Notebook,
	},
	{
		name: "npm",
		pascalName: "Npm",
		category: "brands",
		tags: ["package","registry","javascript","brand"],
		variants: ["bold"],
		component: Npm,
	},
	{
		name: "nvidia",
		pascalName: "Nvidia",
		category: "brands",
		tags: ["brand","nvidia","gpu","hardware"],
		variants: ["bold"],
		component: Nvidia,
	},
	{
		name: "octagon-x",
		pascalName: "OctagonX",
		category: "status",
		tags: ["octagon","x","error","stop","close","cancel","danger"],
		variants: ["linear"],
		component: OctagonX,
	},
	{
		name: "openai",
		pascalName: "Openai",
		category: "brands",
		tags: ["chatgpt","ai","brand"],
		variants: ["linear"],
		component: Openai,
	},
	{
		name: "openclaw",
		pascalName: "Openclaw",
		category: "brands",
		tags: ["open-claw","ai","mascot","brand"],
		variants: ["bold"],
		component: Openclaw,
	},
	{
		name: "opencode",
		pascalName: "Opencode",
		category: "brands",
		tags: ["open-code","code","terminal","brand"],
		variants: ["bold"],
		component: Opencode,
	},
	{
		name: "outgoing-call",
		pascalName: "OutgoingCall",
		category: "chat",
		tags: ["phone","call","outgoing","dial","solar"],
		variants: ["linear"],
		component: OutgoingCall,
	},
	{
		name: "package",
		pascalName: "Package",
		category: "files",
		tags: ["package","box","parcel","shipping","delivery","hugeicons"],
		variants: ["linear"],
		component: Package,
	},
	{
		name: "palette",
		pascalName: "Palette",
		category: "editor",
		tags: ["palette","swatches","color","design","solar"],
		variants: ["linear"],
		component: Palette,
	},
	{
		name: "paper-plane",
		pascalName: "PaperPlane",
		category: "actions",
		tags: ["send","message","submit","plane","plane-3","plain-3","solar"],
		variants: ["linear"],
		component: PaperPlane,
	},
	{
		name: "paperclip",
		pascalName: "Paperclip",
		category: "actions",
		tags: ["attachment","attach","clip","file","paperclip-2","solar"],
		variants: ["linear"],
		component: Paperclip,
	},
	{
		name: "pause",
		pascalName: "Pause",
		category: "media",
		tags: ["pause","media","playback","video","audio"],
		variants: ["linear"],
		component: Pause,
	},
	{
		name: "pen",
		pascalName: "Pen",
		category: "editor",
		tags: ["edit","pencil","write","draw","compose"],
		variants: ["linear"],
		component: Pen,
	},
	{
		name: "perplexity",
		pascalName: "Perplexity",
		category: "brands",
		tags: ["brand","perplexity","ai","search"],
		variants: ["linear"],
		component: Perplexity,
	},
	{
		name: "phone",
		pascalName: "Phone",
		category: "chat",
		tags: ["phone","call","telephone","contact","solar"],
		variants: ["linear"],
		component: Phone,
	},
	{
		name: "pin",
		pascalName: "Pin",
		category: "actions",
		tags: ["pushpin","pinned","save","solar"],
		variants: ["linear"],
		component: Pin,
	},
	{
		name: "pinterest",
		pascalName: "Pinterest",
		category: "brands",
		tags: ["social","pins","brand"],
		variants: ["bold"],
		component: Pinterest,
	},
	{
		name: "pip",
		pascalName: "Pip",
		category: "layout",
		tags: ["picture-in-picture","pip","window","video","overlay","solar"],
		variants: ["linear"],
		component: Pip,
	},
	{
		name: "play",
		pascalName: "Play",
		category: "media",
		tags: ["start","resume","playback","video","audio","solar"],
		variants: ["linear"],
		component: Play,
	},
	{
		name: "play-mini",
		pascalName: "PlayMini",
		category: "media",
		tags: ["play","mini","media","start","triangle"],
		variants: ["linear"],
		component: PlayMini,
	},
	{
		name: "power",
		pascalName: "Power",
		category: "settings",
		tags: ["power","on","off","shutdown","hugeicons"],
		variants: ["linear"],
		component: Power,
	},
	{
		name: "printer",
		pascalName: "Printer",
		category: "devices",
		tags: ["printer","print","paper","document","solar"],
		variants: ["linear"],
		component: Printer,
	},
	{
		name: "puzzle",
		pascalName: "Puzzle",
		category: "development",
		tags: ["puzzle","piece","extension","plugin","hugeicons"],
		variants: ["linear"],
		component: Puzzle,
	},
	{
		name: "qr-code",
		pascalName: "QrCode",
		category: "actions",
		tags: ["qr-code","qr","scan","barcode","hugeicons"],
		variants: ["linear"],
		component: QrCode,
	},
	{
		name: "quote",
		pascalName: "Quote",
		category: "editor",
		tags: ["quote","quotation","blockquote","citation","testimonial","solar"],
		variants: ["linear"],
		component: Quote,
	},
	{
		name: "qwen",
		pascalName: "Qwen",
		category: "brands",
		tags: ["ai","alibaba","brand"],
		variants: ["bold"],
		component: Qwen,
	},
	{
		name: "react",
		pascalName: "React",
		category: "brands",
		tags: ["javascript","framework","frontend","brand"],
		variants: ["linear"],
		component: React,
	},
	{
		name: "reddit",
		pascalName: "Reddit",
		category: "brands",
		tags: ["community","social","brand"],
		variants: ["bold"],
		component: Reddit,
	},
	{
		name: "redo",
		pascalName: "Redo",
		category: "arrows",
		tags: ["history","forward","repeat","arrow"],
		variants: ["linear"],
		component: Redo,
	},
	{
		name: "reorder",
		pascalName: "Reorder",
		category: "actions",
		tags: ["sort","arrange","drag","list","menu","solar"],
		variants: ["linear"],
		component: Reorder,
	},
	{
		name: "repeat",
		pascalName: "Repeat",
		category: "arrows",
		tags: ["loop","cycle","refresh","solar"],
		variants: ["linear"],
		component: Repeat,
	},
	{
		name: "reply",
		pascalName: "Reply",
		category: "arrows",
		tags: ["reply","respond","message","arrow","left"],
		variants: ["linear"],
		component: Reply,
	},
	{
		name: "resources-add",
		pascalName: "ResourcesAdd",
		category: "layout",
		tags: ["resources","add","plus","assets","library","shapes"],
		variants: ["linear"],
		component: ResourcesAdd,
	},
	{
		name: "rhombus",
		pascalName: "Rhombus",
		category: "shapes",
		tags: ["rhombus","shape","geometry","diamond","hugeicons"],
		variants: ["linear"],
		component: Rhombus,
	},
	{
		name: "rocket",
		pascalName: "Rocket",
		category: "objects",
		tags: ["rocket","rocket-02","launch","space","45-degrees","hugeicons","fire","flame"],
		variants: ["linear"],
		component: Rocket,
	},
	{
		name: "sad",
		pascalName: "Sad",
		category: "status",
		tags: ["sad","face","unhappy","frown","emoji"],
		variants: ["linear"],
		component: Sad,
	},
	{
		name: "search",
		pascalName: "Search",
		category: "actions",
		tags: [],
		variants: ["linear"],
		component: Search,
	},
	{
		name: "send",
		pascalName: "Send",
		category: "actions",
		tags: ["send","sent","message","paper-plane","delivery","hugeicons"],
		variants: ["linear"],
		component: Send,
	},
	{
		name: "server",
		pascalName: "Server",
		category: "development",
		tags: ["server","rack","hardware","storage","solar"],
		variants: ["linear"],
		component: Server,
	},
	{
		name: "settings",
		pascalName: "Settings",
		category: "settings",
		tags: ["gear","cog","preferences","configuration","options","solar"],
		variants: ["linear"],
		component: Settings,
	},
	{
		name: "share",
		pascalName: "Share",
		category: "actions",
		tags: ["send","social","link","solar"],
		variants: ["linear"],
		component: Share,
	},
	{
		name: "shield-add",
		pascalName: "ShieldAdd",
		category: "security",
		tags: ["shield","plus","add","protect","security","shield-plus","solar"],
		variants: ["linear"],
		component: ShieldAdd,
	},
	{
		name: "sidebar-bottom",
		pascalName: "SidebarBottom",
		category: "layout",
		tags: ["sidebar","panel","bottom","layout","split"],
		variants: ["linear"],
		component: SidebarBottom,
	},
	{
		name: "sidebar-left",
		pascalName: "SidebarLeft",
		category: "layout",
		tags: ["panel","layout","navigation","sidebar","left","sidebar-minimalistic","solar"],
		variants: ["linear"],
		component: SidebarLeft,
	},
	{
		name: "sidebar-right",
		pascalName: "SidebarRight",
		category: "layout",
		tags: ["panel","layout","navigation","sidebar","right","sidebar-minimalistic","solar"],
		variants: ["linear"],
		component: SidebarRight,
	},
	{
		name: "sidebar-top",
		pascalName: "SidebarTop",
		category: "layout",
		tags: ["sidebar","panel","top","layout","split"],
		variants: ["linear"],
		component: SidebarTop,
	},
	{
		name: "sim-card",
		pascalName: "SimCard",
		category: "devices",
		tags: ["sim-card","sim","mobile","network"],
		variants: ["linear"],
		component: SimCard,
	},
	{
		name: "slack",
		pascalName: "Slack",
		category: "brands",
		tags: ["messaging","chat","team","workplace","brand"],
		variants: ["bold"],
		component: Slack,
	},
	{
		name: "slash",
		pascalName: "Slash",
		category: "editor",
		tags: ["slash","divide","diagonal","separator"],
		variants: ["linear"],
		component: Slash,
	},
	{
		name: "sliders-horizontal",
		pascalName: "SlidersHorizontal",
		category: "settings",
		tags: ["sliders","horizontal","settings","adjustments","controls","tune","hugeicons"],
		variants: ["linear"],
		component: SlidersHorizontal,
	},
	{
		name: "sliders-horizontal-alt",
		pascalName: "SlidersHorizontalAlt",
		category: "settings",
		tags: ["sliders","settings","tuning","adjust","circular","horizontal","solar"],
		variants: ["linear"],
		component: SlidersHorizontalAlt,
	},
	{
		name: "sliders-vertical",
		pascalName: "SlidersVertical",
		category: "settings",
		tags: ["sliders","vertical","settings","adjustments","controls","tune","hugeicons"],
		variants: ["linear"],
		component: SlidersVertical,
	},
	{
		name: "sliders-vertical-alt",
		pascalName: "SlidersVerticalAlt",
		category: "settings",
		tags: ["sliders","settings","tuning","adjust","circular","vertical","solar"],
		variants: ["linear"],
		component: SlidersVerticalAlt,
	},
	{
		name: "smartphone",
		pascalName: "Smartphone",
		category: "devices",
		tags: ["phone","mobile","device","screen","solar"],
		variants: ["linear"],
		component: Smartphone,
	},
	{
		name: "smile",
		pascalName: "Smile",
		category: "status",
		tags: ["smile","happy","face","emoji"],
		variants: ["linear"],
		component: Smile,
	},
	{
		name: "snapchat",
		pascalName: "Snapchat",
		category: "brands",
		tags: [],
		variants: ["linear","bold"],
		component: Snapchat,
	},
	{
		name: "soundwave",
		pascalName: "Soundwave",
		category: "media",
		tags: ["waveform","audio","sound","voice","equalizer","solar"],
		variants: ["linear"],
		component: Soundwave,
	},
	{
		name: "sparkles",
		pascalName: "Sparkles",
		category: "ai",
		tags: ["sparkles","sparkle","magic","ai","shine","stars"],
		variants: ["linear"],
		component: Sparkles,
	},
	{
		name: "spinner",
		pascalName: "Spinner",
		category: "spinner",
		tags: ["loader","loading","progress","wait","busy","rotate"],
		variants: ["linear"],
		component: Spinner,
	},
	{
		name: "spinner-arc",
		pascalName: "SpinnerArc",
		category: "spinner",
		tags: ["loader","loading","progress","wait","rotate","arc","long","spinner-large","SpinnerLarge"],
		variants: ["linear"],
		component: SpinnerArc,
	},
	{
		name: "spinner-diagonal",
		pascalName: "SpinnerDiagonal",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","diagonal","wave"],
		variants: ["linear"],
		component: SpinnerDiagonal,
	},
	{
		name: "spinner-orbit",
		pascalName: "SpinnerOrbit",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","comet"],
		variants: ["linear"],
		component: SpinnerOrbit,
	},
	{
		name: "spinner-wave",
		pascalName: "SpinnerWave",
		category: "spinner",
		tags: ["loader","loading","progress","wait","grid","pixel","chevron","wave","spinner-tinker","SpinnerTinker"],
		variants: ["linear"],
		component: SpinnerWave,
	},
	{
		name: "square-pen",
		pascalName: "SquarePen",
		category: "actions",
		tags: ["send-message","SendMessage","compose","edit","write","pencil"],
		variants: ["linear"],
		component: SquarePen,
	},
	{
		name: "star",
		pascalName: "Star",
		category: "actions",
		tags: ["favorite","rating","saved","solar"],
		variants: ["linear"],
		component: Star,
	},
	{
		name: "star-off",
		pascalName: "StarOff",
		category: "actions",
		tags: ["star","off","unfavorite","unstar","disabled"],
		variants: ["linear"],
		component: StarOff,
	},
	{
		name: "sticker",
		pascalName: "Sticker",
		category: "editor",
		tags: ["label","peel","fold","square","solar"],
		variants: ["linear"],
		component: Sticker,
	},
	{
		name: "stop",
		pascalName: "Stop",
		category: "media",
		tags: ["end","halt","playback","recording","square","solar"],
		variants: ["linear"],
		component: Stop,
	},
	{
		name: "stopwatch",
		pascalName: "Stopwatch",
		category: "time",
		tags: ["stopwatch","stop-watch","timer","time","hugeicons"],
		variants: ["linear"],
		component: Stopwatch,
	},
	{
		name: "strikethrough",
		pascalName: "Strikethrough",
		category: "editor",
		tags: ["text","strikethrough","strike","format","editor"],
		variants: ["linear"],
		component: Strikethrough,
	},
	{
		name: "suitcase",
		pascalName: "Suitcase",
		category: "objects",
		tags: ["suitcase","travel","luggage","bag"],
		variants: ["linear"],
		component: Suitcase,
	},
	{
		name: "sun",
		pascalName: "Sun",
		category: "settings",
		tags: ["sun","light","day","brightness","theme","sun-01","hugeicons"],
		variants: ["linear","bold"],
		component: Sun,
	},
	{
		name: "supabase",
		pascalName: "Supabase",
		category: "brands",
		tags: ["database","backend","brand"],
		variants: ["bold"],
		component: Supabase,
	},
	{
		name: "table",
		pascalName: "Table",
		category: "editor",
		tags: ["table","grid","rows","columns","spreadsheet","solar"],
		variants: ["linear"],
		component: Table,
	},
	{
		name: "tablet",
		pascalName: "Tablet",
		category: "devices",
		tags: ["ipad","device","screen","landscape","solar"],
		variants: ["linear"],
		component: Tablet,
	},
	{
		name: "telegram",
		pascalName: "Telegram",
		category: "brands",
		tags: ["messaging","chat","social","brand","paper-plane"],
		variants: ["bold"],
		component: Telegram,
	},
	{
		name: "terminal",
		pascalName: "Terminal",
		category: "development",
		tags: ["code","console","command","shell","prompt","cli"],
		variants: ["linear"],
		component: Terminal,
	},
	{
		name: "text-align-center",
		pascalName: "TextAlignCenter",
		category: "editor",
		tags: ["text","align","center","paragraph","format","hugeicons"],
		variants: ["linear"],
		component: TextAlignCenter,
	},
	{
		name: "text-align-justify-left",
		pascalName: "TextAlignJustifyLeft",
		category: "editor",
		tags: ["text","align","justify","left","paragraph","format","hugeicons"],
		variants: ["linear"],
		component: TextAlignJustifyLeft,
	},
	{
		name: "text-align-justify-right",
		pascalName: "TextAlignJustifyRight",
		category: "editor",
		tags: ["text","align","justify","right","paragraph","format","hugeicons"],
		variants: ["linear"],
		component: TextAlignJustifyRight,
	},
	{
		name: "text-align-left",
		pascalName: "TextAlignLeft",
		category: "editor",
		tags: ["text","align","left","paragraph","format","hugeicons"],
		variants: ["linear"],
		component: TextAlignLeft,
	},
	{
		name: "text-align-right",
		pascalName: "TextAlignRight",
		category: "editor",
		tags: ["text","align","right","paragraph","format","hugeicons"],
		variants: ["linear"],
		component: TextAlignRight,
	},
	{
		name: "text-underline",
		pascalName: "TextUnderline",
		category: "editor",
		tags: ["underline","text","format","editor","hugeicons"],
		variants: ["linear"],
		component: TextUnderline,
	},
	{
		name: "threads",
		pascalName: "Threads",
		category: "brands",
		tags: ["brand","threads"],
		variants: ["linear"],
		component: Threads,
	},
	{
		name: "three-squares",
		pascalName: "ThreeSquares",
		category: "shapes",
		tags: ["three-squares","squares","stack","layers","solar"],
		variants: ["linear"],
		component: ThreeSquares,
	},
	{
		name: "ticket",
		pascalName: "Ticket",
		category: "commerce",
		tags: ["ticket","pass","event","admission","coupon","solar"],
		variants: ["linear"],
		component: Ticket,
	},
	{
		name: "ticket-discount",
		pascalName: "TicketDiscount",
		category: "commerce",
		tags: ["ticket","discount","coupon","voucher","sale","percent"],
		variants: ["linear"],
		component: TicketDiscount,
	},
	{
		name: "tiktok",
		pascalName: "Tiktok",
		category: "brands",
		tags: ["brand","tiktok"],
		variants: ["bold"],
		component: Tiktok,
	},
	{
		name: "transfer-horizontal",
		pascalName: "TransferHorizontal",
		category: "arrows",
		tags: ["transfer","swap","exchange","arrows","horizontal","solar"],
		variants: ["linear"],
		component: TransferHorizontal,
	},
	{
		name: "transfer-vertical",
		pascalName: "TransferVertical",
		category: "arrows",
		tags: ["transfer","swap","exchange","arrows","vertical","solar"],
		variants: ["linear"],
		component: TransferVertical,
	},
	{
		name: "trash",
		pascalName: "Trash",
		category: "actions",
		tags: [],
		variants: ["linear"],
		component: Trash,
	},
	{
		name: "truck",
		pascalName: "Truck",
		category: "maps",
		tags: ["truck","delivery","shipping","transport"],
		variants: ["linear"],
		component: Truck,
	},
	{
		name: "twitter",
		pascalName: "Twitter",
		category: "brands",
		tags: ["bird","social","brand"],
		variants: ["bold"],
		component: Twitter,
	},
	{
		name: "typescript",
		pascalName: "Typescript",
		category: "brands",
		tags: ["typescript","javascript","language","brand","ts"],
		variants: ["bold"],
		component: Typescript,
	},
	{
		name: "undo",
		pascalName: "Undo",
		category: "arrows",
		tags: ["history","back","revert","arrow"],
		variants: ["linear"],
		component: Undo,
	},
	{
		name: "unfold-less",
		pascalName: "UnfoldLess",
		category: "arrows",
		tags: ["collapse","fold","chevrons","hugeicons"],
		variants: ["linear"],
		component: UnfoldLess,
	},
	{
		name: "unfold-more",
		pascalName: "UnfoldMore",
		category: "arrows",
		tags: ["expand","unfold","chevrons","hugeicons"],
		variants: ["linear"],
		component: UnfoldMore,
	},
	{
		name: "upload",
		pascalName: "Upload",
		category: "actions",
		tags: ["upload","tray","export","outgoing","arrow"],
		variants: ["linear"],
		component: Upload,
	},
	{
		name: "user",
		pascalName: "User",
		category: "user",
		tags: ["profile","person","account","avatar","solar"],
		variants: ["linear"],
		component: User,
	},
	{
		name: "user-add",
		pascalName: "UserAdd",
		category: "user",
		tags: ["user","add","plus","invite","account","user-plus","solar"],
		variants: ["linear"],
		component: UserAdd,
	},
	{
		name: "user-check",
		pascalName: "UserCheck",
		category: "user",
		tags: ["user","check","verified","approved","account"],
		variants: ["linear"],
		component: UserCheck,
	},
	{
		name: "user-group",
		pascalName: "UserGroup",
		category: "user",
		tags: ["users","team","people","members","users-group-two-rounded","solar"],
		variants: ["linear"],
		component: UserGroup,
	},
	{
		name: "user-remove",
		pascalName: "UserRemove",
		category: "user",
		tags: ["user","minus","remove","account","user-minus"],
		variants: ["linear"],
		component: UserRemove,
	},
	{
		name: "user-x",
		pascalName: "UserX",
		category: "user",
		tags: ["user","x","close","cancel","account"],
		variants: ["linear"],
		component: UserX,
	},
	{
		name: "vercel",
		pascalName: "Vercel",
		category: "brands",
		tags: ["brand","vercel","hosting","deployment"],
		variants: ["bold"],
		component: Vercel,
	},
	{
		name: "verified-check",
		pascalName: "VerifiedCheck",
		category: "status",
		tags: ["verified","badge","check","approved","solar"],
		variants: ["linear"],
		component: VerifiedCheck,
	},
	{
		name: "video-camera",
		pascalName: "VideoCamera",
		category: "media",
		tags: ["video","camera","record","call","videocamera","solar"],
		variants: ["linear"],
		component: VideoCamera,
	},
	{
		name: "video-frame",
		pascalName: "VideoFrame",
		category: "media",
		tags: ["video","film","frame","filmstrip","movie","solar"],
		variants: ["linear"],
		component: VideoFrame,
	},
	{
		name: "volume-high",
		pascalName: "VolumeHigh",
		category: "media",
		tags: ["volume","sound","speaker","audio","unmute","solar","volume-loud","VolumeLoud"],
		variants: ["linear"],
		component: VolumeHigh,
	},
	{
		name: "volume-low",
		pascalName: "VolumeLow",
		category: "media",
		tags: ["speaker","sound","audio","volume-low","solar","volume"],
		variants: ["linear"],
		component: VolumeLow,
	},
	{
		name: "volume-off",
		pascalName: "VolumeOff",
		category: "media",
		tags: ["mute","volume-off","silent","speaker","audio","solar","muted"],
		variants: ["linear"],
		component: VolumeOff,
	},
	{
		name: "wallet",
		pascalName: "Wallet",
		category: "commerce",
		tags: ["money","payment","finance","cash","solar"],
		variants: ["linear"],
		component: Wallet,
	},
	{
		name: "waves",
		pascalName: "Waves",
		category: "shapes",
		tags: ["waves","water","sea","ocean"],
		variants: ["linear"],
		component: Waves,
	},
	{
		name: "widget",
		pascalName: "Widget",
		category: "layout",
		tags: ["grid","dashboard","layout","apps","solar"],
		variants: ["linear"],
		component: Widget,
	},
	{
		name: "widget-add",
		pascalName: "WidgetAdd",
		category: "layout",
		tags: ["widget","add","plus","grid","dashboard","layout","solar"],
		variants: ["linear"],
		component: WidgetAdd,
	},
	{
		name: "widget-square",
		pascalName: "WidgetSquare",
		category: "layout",
		tags: ["widget","grid","dashboard","layout","apps","square","solar"],
		variants: ["linear"],
		component: WidgetSquare,
	},
	{
		name: "widget-square-add",
		pascalName: "WidgetSquareAdd",
		category: "layout",
		tags: ["widget","add","plus","grid","dashboard","layout","square","solar"],
		variants: ["linear"],
		component: WidgetSquareAdd,
	},
	{
		name: "wifi",
		pascalName: "Wifi",
		category: "devices",
		tags: ["wifi","wi-fi","wireless","network","connection","internet","solar"],
		variants: ["linear"],
		component: Wifi,
	},
	{
		name: "windsurf",
		pascalName: "Windsurf",
		category: "brands",
		tags: ["ai","code","editor","brand"],
		variants: ["linear"],
		component: Windsurf,
	},
	{
		name: "x",
		pascalName: "X",
		category: "brands",
		tags: [],
		variants: ["linear"],
		component: X,
	},
	{
		name: "xai",
		pascalName: "Xai",
		category: "brands",
		tags: ["ai","brand"],
		variants: ["linear"],
		component: Xai,
	},
	{
		name: "youtube",
		pascalName: "Youtube",
		category: "brands",
		tags: ["brand","youtube","video","google"],
		variants: ["bold"],
		component: Youtube,
	},
	{
		name: "zai",
		pascalName: "Zai",
		category: "brands",
		tags: ["z.ai","ai","brand"],
		variants: ["bold"],
		component: Zai,
	},
	{
		name: "zoom-in",
		pascalName: "ZoomIn",
		category: "actions",
		tags: ["magnifier","magnifier-zoom-in","zoom-in","search","enlarge","plus","solar","search-plus","SearchPlus"],
		variants: ["linear"],
		component: ZoomIn,
	},
	{
		name: "zoom-out",
		pascalName: "ZoomOut",
		category: "actions",
		tags: ["magnifier","minimalistic-magnifier-zoom-out","zoom-out","search","shrink","minus","solar","search-minus","SearchMinus"],
		variants: ["linear"],
		component: ZoomOut,
	},
];
