/* Generated by scripts/build-icons.ts. Do not edit. */
export const ICON_CATEGORIES = [
	"actions",
	"ai",
	"arrows",
	"brands",
	"charts",
	"chat",
	"commerce",
	"development",
	"devices",
	"editor",
	"files",
	"layout",
	"maps",
	"media",
	"objects",
	"security",
	"settings",
	"shapes",
	"spinner",
	"status",
	"time",
	"user",
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];
