/* Generated by scripts/build-icons.ts. Do not edit. */
export const ICON_CATEGORIES = [
	"actions",
	"ai",
	"arrows",
	"chat",
	"editor",
	"files",
	"git",
	"layout",
	"media",
	"settings",
	"spinner",
	"status",
	"user",
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];
