/* Generated by scripts/build-icons.ts. Do not edit. */
import type { HoneyIcon } from "./create-icon.js";
import { Activity } from "./icons/activity.js";
import { Add } from "./icons/add.js";
import { Alarm } from "./icons/alarm.js";
import { Album } from "./icons/album.js";
import { AlertTriangle } from "./icons/alert-triangle.js";
import { Analytics } from "./icons/analytics.js";
import { Anthropic } from "./icons/anthropic.js";
import { Antigravity } from "./icons/antigravity.js";
import { Archive } from "./icons/archive.js";
import { ArchiveAlt } from "./icons/archive-alt.js";
import { ArchiveUp } from "./icons/archive-up.js";
import { ArrowDown } from "./icons/arrow-down.js";
import { ArrowDownLeft } from "./icons/arrow-down-left.js";
import { ArrowDownRight } from "./icons/arrow-down-right.js";
import { ArrowLeft } from "./icons/arrow-left.js";
import { ArrowRight } from "./icons/arrow-right.js";
import { ArrowUp } from "./icons/arrow-up.js";
import { ArrowUpLeft } from "./icons/arrow-up-left.js";
import { ArrowUpRight } from "./icons/arrow-up-right.js";
import { AtSign } from "./icons/at-sign.js";
import { Battery } from "./icons/battery.js";
import { Bell } from "./icons/bell.js";
import { BellOff } from "./icons/bell-off.js";
import { Bluetooth } from "./icons/bluetooth.js";
import { Bold } from "./icons/bold.js";
import { Bolt } from "./icons/bolt.js";
import { BookOpen } from "./icons/book-open.js";
import { Bookmark } from "./icons/bookmark.js";
import { Bookmarks } from "./icons/bookmarks.js";
import { Brain } from "./icons/brain.js";
import { Briefcase } from "./icons/briefcase.js";
import { Broadcast } from "./icons/broadcast.js";
import { Bug } from "./icons/bug.js";
import { Building } from "./icons/building.js";
import { Bun } from "./icons/bun.js";
import { Calculator } from "./icons/calculator.js";
import { Calendar } from "./icons/calendar.js";
import { CalendarAdd } from "./icons/calendar-add.js";
import { CalendarMark } from "./icons/calendar-mark.js";
import { CalendarRemove } from "./icons/calendar-remove.js";
import { CalendarSearch } from "./icons/calendar-search.js";
import { CalendarX } from "./icons/calendar-x.js";
import { Camera } from "./icons/camera.js";
import { Card } from "./icons/card.js";
import { Cart } from "./icons/cart.js";
import { CartBag } from "./icons/cart-bag.js";
import { CartLarge } from "./icons/cart-large.js";
import { Chair } from "./icons/chair.js";
import { ChartAnalysis } from "./icons/chart-analysis.js";
import { Chat } from "./icons/chat.js";
import { Check } from "./icons/check.js";
import { CheckDouble } from "./icons/check-double.js";
import { ChevronDown } from "./icons/chevron-down.js";
import { ChevronLeft } from "./icons/chevron-left.js";
import { ChevronRight } from "./icons/chevron-right.js";
import { ChevronUp } from "./icons/chevron-up.js";
import { ChevronsDown } from "./icons/chevrons-down.js";
import { ChevronsLeft } from "./icons/chevrons-left.js";
import { ChevronsRight } from "./icons/chevrons-right.js";
import { ChevronsUp } from "./icons/chevrons-up.js";
import { Chrome } from "./icons/chrome.js";
import { Clapperboard } from "./icons/clapperboard.js";
import { ClapperboardText } from "./icons/clapperboard-text.js";
import { ClaudeAi } from "./icons/claude-ai.js";
import { ClaudeCode } from "./icons/claude-code.js";
import { Clipboard } from "./icons/clipboard.js";
import { ClipboardAdd } from "./icons/clipboard-add.js";
import { ClipboardCheck } from "./icons/clipboard-check.js";
import { ClipboardRemove } from "./icons/clipboard-remove.js";
import { Clock } from "./icons/clock.js";
import { Close } from "./icons/close.js";
import { Cloud } from "./icons/cloud.js";
import { CloudDownload } from "./icons/cloud-download.js";
import { CloudRain } from "./icons/cloud-rain.js";
import { CloudUpload } from "./icons/cloud-upload.js";
import { Code } from "./icons/code.js";
import { Codex } from "./icons/codex.js";
import { Command } from "./icons/command.js";
import { Computer } from "./icons/computer.js";
import { Connect } from "./icons/connect.js";
import { Copy } from "./icons/copy.js";
import { Crop } from "./icons/crop.js";
import { Cursor } from "./icons/cursor.js";
import { Database } from "./icons/database.js";
import { Deepseek } from "./icons/deepseek.js";
import { Devin } from "./icons/devin.js";
import { Diamond } from "./icons/diamond.js";
import { Discord } from "./icons/discord.js";
import { Dislike } from "./icons/dislike.js";
import { Document } from "./icons/document.js";
import { DoorOpen } from "./icons/door-open.js";
import { Download } from "./icons/download.js";
import { Droplet } from "./icons/droplet.js";
import { Edit } from "./icons/edit.js";
import { EditOff } from "./icons/edit-off.js";
import { Email } from "./icons/email.js";
import { ExternalLink } from "./icons/external-link.js";
import { Eye } from "./icons/eye.js";
import { EyeClosed } from "./icons/eye-closed.js";
import { EyeOff } from "./icons/eye-off.js";
import { Facebook } from "./icons/facebook.js";
import { Figma } from "./icons/figma.js";
import { File } from "./icons/file.js";
import { FileAdd } from "./icons/file-add.js";
import { FileCode } from "./icons/file-code.js";
import { FileRemove } from "./icons/file-remove.js";
import { FileText } from "./icons/file-text.js";
import { Filter } from "./icons/filter.js";
import { Fingerprint } from "./icons/fingerprint.js";
import { Flag } from "./icons/flag.js";
import { Folder } from "./icons/folder.js";
import { FolderAdd } from "./icons/folder-add.js";
import { FolderOpen } from "./icons/folder-open.js";
import { FolderTree } from "./icons/folder-tree.js";
import { FolderWithFiles } from "./icons/folder-with-files.js";
import { Folders } from "./icons/folders.js";
import { Forward } from "./icons/forward.js";
import { Gamepad } from "./icons/gamepad.js";
import { Gemini } from "./icons/gemini.js";
import { Gift } from "./icons/gift.js";
import { Git } from "./icons/git.js";
import { GitBranch } from "./icons/git-branch.js";
import { GitDiff } from "./icons/git-diff.js";
import { GitFork } from "./icons/git-fork.js";
import { GitGraph } from "./icons/git-graph.js";
import { GitPullRequest } from "./icons/git-pull-request.js";
import { Github } from "./icons/github.js";
import { GithubCopilot } from "./icons/github-copilot.js";
import { Globe } from "./icons/globe.js";
import { Google } from "./icons/google.js";
import { GripHorizontal } from "./icons/grip-horizontal.js";
import { GripVertical } from "./icons/grip-vertical.js";
import { Grok } from "./icons/grok.js";
import { Hand } from "./icons/hand.js";
import { HandWave } from "./icons/hand-wave.js";
import { Hashtag } from "./icons/hashtag.js";
import { Heading } from "./icons/heading.js";
import { Headphones } from "./icons/headphones.js";
import { Heart } from "./icons/heart.js";
import { History } from "./icons/history.js";
import { Home } from "./icons/home.js";
import { HomeAngle } from "./icons/home-angle.js";
import { Image } from "./icons/image.js";
import { ImageAdd } from "./icons/image-add.js";
import { ImageEdit } from "./icons/image-edit.js";
import { Import } from "./icons/import.js";
import { Inbox } from "./icons/inbox.js";
import { IncomingCall } from "./icons/incoming-call.js";
import { InfoSquare } from "./icons/info-square.js";
import { Instagram } from "./icons/instagram.js";
import { Integration } from "./icons/integration.js";
import { Italic } from "./icons/italic.js";
import { Kanban } from "./icons/kanban.js";
import { Key } from "./icons/key.js";
import { Keyboard } from "./icons/keyboard.js";
import { Kimi } from "./icons/kimi.js";
import { Layers } from "./icons/layers.js";
import { LayoutAlignBottom } from "./icons/layout-align-bottom.js";
import { LayoutAlignLeft } from "./icons/layout-align-left.js";
import { LayoutAlignRight } from "./icons/layout-align-right.js";
import { LayoutAlignTop } from "./icons/layout-align-top.js";
import { LifeBuoy } from "./icons/life-buoy.js";
import { Lightbulb } from "./icons/lightbulb.js";
import { Lightning } from "./icons/lightning.js";
import { Like } from "./icons/like.js";
import { Link } from "./icons/link.js";
import { Linkedin } from "./icons/linkedin.js";
import { List } from "./icons/list.js";
import { ListChecks } from "./icons/list-checks.js";
import { ListDash } from "./icons/list-dash.js";
import { ListDown } from "./icons/list-down.js";
import { ListFilter } from "./icons/list-filter.js";
import { ListUp } from "./icons/list-up.js";
import { Lock } from "./icons/lock.js";
import { LockOpen } from "./icons/lock-open.js";
import { Login } from "./icons/login.js";
import { Logout } from "./icons/logout.js";
import { Map } from "./icons/map.js";
import { MapArrowDown } from "./icons/map-arrow-down.js";
import { MapArrowLeft } from "./icons/map-arrow-left.js";
import { MapArrowRight } from "./icons/map-arrow-right.js";
import { MapArrowUp } from "./icons/map-arrow-up.js";
import { MapFolded } from "./icons/map-folded.js";
import { MapPin } from "./icons/map-pin.js";
import { MarketAnalysis } from "./icons/market-analysis.js";
import { Maximize } from "./icons/maximize.js";
import { Menu } from "./icons/menu.js";
import { MetaAi } from "./icons/meta-ai.js";
import { Microphone } from "./icons/microphone.js";
import { MicrophoneOff } from "./icons/microphone-off.js";
import { MicrosoftCopilot } from "./icons/microsoft-copilot.js";
import { Minimize } from "./icons/minimize.js";
import { Minus } from "./icons/minus.js";
import { Mistral } from "./icons/mistral.js";
import { Moon } from "./icons/moon.js";
import { MoreHorizontal } from "./icons/more-horizontal.js";
import { MoreVertical } from "./icons/more-vertical.js";
import { Move } from "./icons/move.js";
import { MusicNote } from "./icons/music-note.js";
import { Navigation } from "./icons/navigation.js";
import { Notebook } from "./icons/notebook.js";
import { Npm } from "./icons/npm.js";
import { Nvidia } from "./icons/nvidia.js";
import { OctagonX } from "./icons/octagon-x.js";
import { Openai } from "./icons/openai.js";
import { Openclaw } from "./icons/openclaw.js";
import { Opencode } from "./icons/opencode.js";
import { OutgoingCall } from "./icons/outgoing-call.js";
import { Package } from "./icons/package.js";
import { Palette } from "./icons/palette.js";
import { PaperPlane } from "./icons/paper-plane.js";
import { Paperclip } from "./icons/paperclip.js";
import { Pause } from "./icons/pause.js";
import { Pen } from "./icons/pen.js";
import { Perplexity } from "./icons/perplexity.js";
import { Phone } from "./icons/phone.js";
import { Pin } from "./icons/pin.js";
import { Pinterest } from "./icons/pinterest.js";
import { Pip } from "./icons/pip.js";
import { Play } from "./icons/play.js";
import { PlayMini } from "./icons/play-mini.js";
import { Power } from "./icons/power.js";
import { Printer } from "./icons/printer.js";
import { Puzzle } from "./icons/puzzle.js";
import { QrCode } from "./icons/qr-code.js";
import { Quote } from "./icons/quote.js";
import { Qwen } from "./icons/qwen.js";
import { React } from "./icons/react.js";
import { Reddit } from "./icons/reddit.js";
import { Redo } from "./icons/redo.js";
import { Reorder } from "./icons/reorder.js";
import { Repeat } from "./icons/repeat.js";
import { Reply } from "./icons/reply.js";
import { ResourcesAdd } from "./icons/resources-add.js";
import { Rhombus } from "./icons/rhombus.js";
import { Rocket } from "./icons/rocket.js";
import { Sad } from "./icons/sad.js";
import { Search } from "./icons/search.js";
import { Send } from "./icons/send.js";
import { Server } from "./icons/server.js";
import { Settings } from "./icons/settings.js";
import { Share } from "./icons/share.js";
import { ShieldAdd } from "./icons/shield-add.js";
import { SidebarBottom } from "./icons/sidebar-bottom.js";
import { SidebarLeft } from "./icons/sidebar-left.js";
import { SidebarRight } from "./icons/sidebar-right.js";
import { SidebarTop } from "./icons/sidebar-top.js";
import { SimCard } from "./icons/sim-card.js";
import { Slack } from "./icons/slack.js";
import { Slash } from "./icons/slash.js";
import { SlidersHorizontal } from "./icons/sliders-horizontal.js";
import { SlidersHorizontalAlt } from "./icons/sliders-horizontal-alt.js";
import { SlidersVertical } from "./icons/sliders-vertical.js";
import { SlidersVerticalAlt } from "./icons/sliders-vertical-alt.js";
import { Smartphone } from "./icons/smartphone.js";
import { Smile } from "./icons/smile.js";
import { Snapchat } from "./icons/snapchat.js";
import { Snowflake } from "./icons/snowflake.js";
import { Soundwave } from "./icons/soundwave.js";
import { Sparkles } from "./icons/sparkles.js";
import { Spinner } from "./icons/spinner.js";
import { SpinnerArc } from "./icons/spinner-arc.js";
import { SpinnerDiagonal } from "./icons/spinner-diagonal.js";
import { SpinnerOrbit } from "./icons/spinner-orbit.js";
import { SpinnerWave } from "./icons/spinner-wave.js";
import { SquarePen } from "./icons/square-pen.js";
import { Star } from "./icons/star.js";
import { StarOff } from "./icons/star-off.js";
import { Sticker } from "./icons/sticker.js";
import { Stop } from "./icons/stop.js";
import { Stopwatch } from "./icons/stopwatch.js";
import { Strikethrough } from "./icons/strikethrough.js";
import { Suitcase } from "./icons/suitcase.js";
import { Sun } from "./icons/sun.js";
import { Supabase } from "./icons/supabase.js";
import { Table } from "./icons/table.js";
import { Tablet } from "./icons/tablet.js";
import { Telegram } from "./icons/telegram.js";
import { Terminal } from "./icons/terminal.js";
import { TextAlignCenter } from "./icons/text-align-center.js";
import { TextAlignJustifyLeft } from "./icons/text-align-justify-left.js";
import { TextAlignJustifyRight } from "./icons/text-align-justify-right.js";
import { TextAlignLeft } from "./icons/text-align-left.js";
import { TextAlignRight } from "./icons/text-align-right.js";
import { TextUnderline } from "./icons/text-underline.js";
import { Threads } from "./icons/threads.js";
import { ThreeSquares } from "./icons/three-squares.js";
import { Ticket } from "./icons/ticket.js";
import { TicketDiscount } from "./icons/ticket-discount.js";
import { Tiktok } from "./icons/tiktok.js";
import { TransferHorizontal } from "./icons/transfer-horizontal.js";
import { TransferVertical } from "./icons/transfer-vertical.js";
import { Trash } from "./icons/trash.js";
import { Truck } from "./icons/truck.js";
import { Twitter } from "./icons/twitter.js";
import { Typescript } from "./icons/typescript.js";
import { Undo } from "./icons/undo.js";
import { UnfoldLess } from "./icons/unfold-less.js";
import { UnfoldMore } from "./icons/unfold-more.js";
import { Upload } from "./icons/upload.js";
import { User } from "./icons/user.js";
import { UserAdd } from "./icons/user-add.js";
import { UserCheck } from "./icons/user-check.js";
import { UserGroup } from "./icons/user-group.js";
import { UserRemove } from "./icons/user-remove.js";
import { UserX } from "./icons/user-x.js";
import { Vercel } from "./icons/vercel.js";
import { VerifiedCheck } from "./icons/verified-check.js";
import { VideoCamera } from "./icons/video-camera.js";
import { VideoFrame } from "./icons/video-frame.js";
import { VolumeHigh } from "./icons/volume-high.js";
import { VolumeLow } from "./icons/volume-low.js";
import { VolumeOff } from "./icons/volume-off.js";
import { Wallet } from "./icons/wallet.js";
import { Waves } from "./icons/waves.js";
import { Widget } from "./icons/widget.js";
import { WidgetAdd } from "./icons/widget-add.js";
import { WidgetSquare } from "./icons/widget-square.js";
import { WidgetSquareAdd } from "./icons/widget-square-add.js";
import { Wifi } from "./icons/wifi.js";
import { Wind } from "./icons/wind.js";
import { Windsurf } from "./icons/windsurf.js";
import { X } from "./icons/x.js";
import { Xai } from "./icons/xai.js";
import { Youtube } from "./icons/youtube.js";
import { Zai } from "./icons/zai.js";
import { ZoomIn } from "./icons/zoom-in.js";
import { ZoomOut } from "./icons/zoom-out.js";

export const icons = {
	"activity": Activity,
	"add": Add,
	"alarm": Alarm,
	"album": Album,
	"alert-triangle": AlertTriangle,
	"analytics": Analytics,
	"anthropic": Anthropic,
	"antigravity": Antigravity,
	"archive": Archive,
	"archive-alt": ArchiveAlt,
	"archive-up": ArchiveUp,
	"arrow-down": ArrowDown,
	"arrow-down-left": ArrowDownLeft,
	"arrow-down-right": ArrowDownRight,
	"arrow-left": ArrowLeft,
	"arrow-right": ArrowRight,
	"arrow-up": ArrowUp,
	"arrow-up-left": ArrowUpLeft,
	"arrow-up-right": ArrowUpRight,
	"at-sign": AtSign,
	"battery": Battery,
	"bell": Bell,
	"bell-off": BellOff,
	"bluetooth": Bluetooth,
	"bold": Bold,
	"bolt": Bolt,
	"book-open": BookOpen,
	"bookmark": Bookmark,
	"bookmarks": Bookmarks,
	"brain": Brain,
	"briefcase": Briefcase,
	"broadcast": Broadcast,
	"bug": Bug,
	"building": Building,
	"bun": Bun,
	"calculator": Calculator,
	"calendar": Calendar,
	"calendar-add": CalendarAdd,
	"calendar-mark": CalendarMark,
	"calendar-remove": CalendarRemove,
	"calendar-search": CalendarSearch,
	"calendar-x": CalendarX,
	"camera": Camera,
	"card": Card,
	"cart": Cart,
	"cart-bag": CartBag,
	"cart-large": CartLarge,
	"chair": Chair,
	"chart-analysis": ChartAnalysis,
	"chat": Chat,
	"check": Check,
	"check-double": CheckDouble,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"chevron-right": ChevronRight,
	"chevron-up": ChevronUp,
	"chevrons-down": ChevronsDown,
	"chevrons-left": ChevronsLeft,
	"chevrons-right": ChevronsRight,
	"chevrons-up": ChevronsUp,
	"chrome": Chrome,
	"clapperboard": Clapperboard,
	"clapperboard-text": ClapperboardText,
	"claude-ai": ClaudeAi,
	"claude-code": ClaudeCode,
	"clipboard": Clipboard,
	"clipboard-add": ClipboardAdd,
	"clipboard-check": ClipboardCheck,
	"clipboard-remove": ClipboardRemove,
	"clock": Clock,
	"close": Close,
	"cloud": Cloud,
	"cloud-download": CloudDownload,
	"cloud-rain": CloudRain,
	"cloud-upload": CloudUpload,
	"code": Code,
	"codex": Codex,
	"command": Command,
	"computer": Computer,
	"connect": Connect,
	"copy": Copy,
	"crop": Crop,
	"cursor": Cursor,
	"database": Database,
	"deepseek": Deepseek,
	"devin": Devin,
	"diamond": Diamond,
	"discord": Discord,
	"dislike": Dislike,
	"document": Document,
	"door-open": DoorOpen,
	"download": Download,
	"droplet": Droplet,
	"edit": Edit,
	"edit-off": EditOff,
	"email": Email,
	"external-link": ExternalLink,
	"eye": Eye,
	"eye-closed": EyeClosed,
	"eye-off": EyeOff,
	"facebook": Facebook,
	"figma": Figma,
	"file": File,
	"file-add": FileAdd,
	"file-code": FileCode,
	"file-remove": FileRemove,
	"file-text": FileText,
	"filter": Filter,
	"fingerprint": Fingerprint,
	"flag": Flag,
	"folder": Folder,
	"folder-add": FolderAdd,
	"folder-open": FolderOpen,
	"folder-tree": FolderTree,
	"folder-with-files": FolderWithFiles,
	"folders": Folders,
	"forward": Forward,
	"gamepad": Gamepad,
	"gemini": Gemini,
	"gift": Gift,
	"git": Git,
	"git-branch": GitBranch,
	"git-diff": GitDiff,
	"git-fork": GitFork,
	"git-graph": GitGraph,
	"git-pull-request": GitPullRequest,
	"github": Github,
	"github-copilot": GithubCopilot,
	"globe": Globe,
	"google": Google,
	"grip-horizontal": GripHorizontal,
	"grip-vertical": GripVertical,
	"grok": Grok,
	"hand": Hand,
	"hand-wave": HandWave,
	"hashtag": Hashtag,
	"heading": Heading,
	"headphones": Headphones,
	"heart": Heart,
	"history": History,
	"home": Home,
	"home-angle": HomeAngle,
	"image": Image,
	"image-add": ImageAdd,
	"image-edit": ImageEdit,
	"import": Import,
	"inbox": Inbox,
	"incoming-call": IncomingCall,
	"info-square": InfoSquare,
	"instagram": Instagram,
	"integration": Integration,
	"italic": Italic,
	"kanban": Kanban,
	"key": Key,
	"keyboard": Keyboard,
	"kimi": Kimi,
	"layers": Layers,
	"layout-align-bottom": LayoutAlignBottom,
	"layout-align-left": LayoutAlignLeft,
	"layout-align-right": LayoutAlignRight,
	"layout-align-top": LayoutAlignTop,
	"life-buoy": LifeBuoy,
	"lightbulb": Lightbulb,
	"lightning": Lightning,
	"like": Like,
	"link": Link,
	"linkedin": Linkedin,
	"list": List,
	"list-checks": ListChecks,
	"list-dash": ListDash,
	"list-down": ListDown,
	"list-filter": ListFilter,
	"list-up": ListUp,
	"lock": Lock,
	"lock-open": LockOpen,
	"login": Login,
	"logout": Logout,
	"map": Map,
	"map-arrow-down": MapArrowDown,
	"map-arrow-left": MapArrowLeft,
	"map-arrow-right": MapArrowRight,
	"map-arrow-up": MapArrowUp,
	"map-folded": MapFolded,
	"map-pin": MapPin,
	"market-analysis": MarketAnalysis,
	"maximize": Maximize,
	"menu": Menu,
	"meta-ai": MetaAi,
	"microphone": Microphone,
	"microphone-off": MicrophoneOff,
	"microsoft-copilot": MicrosoftCopilot,
	"minimize": Minimize,
	"minus": Minus,
	"mistral": Mistral,
	"moon": Moon,
	"more-horizontal": MoreHorizontal,
	"more-vertical": MoreVertical,
	"move": Move,
	"music-note": MusicNote,
	"navigation": Navigation,
	"notebook": Notebook,
	"npm": Npm,
	"nvidia": Nvidia,
	"octagon-x": OctagonX,
	"openai": Openai,
	"openclaw": Openclaw,
	"opencode": Opencode,
	"outgoing-call": OutgoingCall,
	"package": Package,
	"palette": Palette,
	"paper-plane": PaperPlane,
	"paperclip": Paperclip,
	"pause": Pause,
	"pen": Pen,
	"perplexity": Perplexity,
	"phone": Phone,
	"pin": Pin,
	"pinterest": Pinterest,
	"pip": Pip,
	"play": Play,
	"play-mini": PlayMini,
	"power": Power,
	"printer": Printer,
	"puzzle": Puzzle,
	"qr-code": QrCode,
	"quote": Quote,
	"qwen": Qwen,
	"react": React,
	"reddit": Reddit,
	"redo": Redo,
	"reorder": Reorder,
	"repeat": Repeat,
	"reply": Reply,
	"resources-add": ResourcesAdd,
	"rhombus": Rhombus,
	"rocket": Rocket,
	"sad": Sad,
	"search": Search,
	"send": Send,
	"server": Server,
	"settings": Settings,
	"share": Share,
	"shield-add": ShieldAdd,
	"sidebar-bottom": SidebarBottom,
	"sidebar-left": SidebarLeft,
	"sidebar-right": SidebarRight,
	"sidebar-top": SidebarTop,
	"sim-card": SimCard,
	"slack": Slack,
	"slash": Slash,
	"sliders-horizontal": SlidersHorizontal,
	"sliders-horizontal-alt": SlidersHorizontalAlt,
	"sliders-vertical": SlidersVertical,
	"sliders-vertical-alt": SlidersVerticalAlt,
	"smartphone": Smartphone,
	"smile": Smile,
	"snapchat": Snapchat,
	"snowflake": Snowflake,
	"soundwave": Soundwave,
	"sparkles": Sparkles,
	"spinner": Spinner,
	"spinner-arc": SpinnerArc,
	"spinner-diagonal": SpinnerDiagonal,
	"spinner-orbit": SpinnerOrbit,
	"spinner-wave": SpinnerWave,
	"square-pen": SquarePen,
	"star": Star,
	"star-off": StarOff,
	"sticker": Sticker,
	"stop": Stop,
	"stopwatch": Stopwatch,
	"strikethrough": Strikethrough,
	"suitcase": Suitcase,
	"sun": Sun,
	"supabase": Supabase,
	"table": Table,
	"tablet": Tablet,
	"telegram": Telegram,
	"terminal": Terminal,
	"text-align-center": TextAlignCenter,
	"text-align-justify-left": TextAlignJustifyLeft,
	"text-align-justify-right": TextAlignJustifyRight,
	"text-align-left": TextAlignLeft,
	"text-align-right": TextAlignRight,
	"text-underline": TextUnderline,
	"threads": Threads,
	"three-squares": ThreeSquares,
	"ticket": Ticket,
	"ticket-discount": TicketDiscount,
	"tiktok": Tiktok,
	"transfer-horizontal": TransferHorizontal,
	"transfer-vertical": TransferVertical,
	"trash": Trash,
	"truck": Truck,
	"twitter": Twitter,
	"typescript": Typescript,
	"undo": Undo,
	"unfold-less": UnfoldLess,
	"unfold-more": UnfoldMore,
	"upload": Upload,
	"user": User,
	"user-add": UserAdd,
	"user-check": UserCheck,
	"user-group": UserGroup,
	"user-remove": UserRemove,
	"user-x": UserX,
	"vercel": Vercel,
	"verified-check": VerifiedCheck,
	"video-camera": VideoCamera,
	"video-frame": VideoFrame,
	"volume-high": VolumeHigh,
	"volume-low": VolumeLow,
	"volume-off": VolumeOff,
	"wallet": Wallet,
	"waves": Waves,
	"widget": Widget,
	"widget-add": WidgetAdd,
	"widget-square": WidgetSquare,
	"widget-square-add": WidgetSquareAdd,
	"wifi": Wifi,
	"wind": Wind,
	"windsurf": Windsurf,
	"x": X,
	"xai": Xai,
	"youtube": Youtube,
	"zai": Zai,
	"zoom-in": ZoomIn,
	"zoom-out": ZoomOut,
} satisfies Record<string, HoneyIcon>;

export type IconName = keyof typeof icons;

export type IconVariantMap = {
	"activity": "linear";
	"add": "linear";
	"alarm": "linear";
	"album": "linear";
	"alert-triangle": "linear";
	"analytics": "linear";
	"anthropic": "bold";
	"antigravity": "bold";
	"archive": "linear";
	"archive-alt": "linear";
	"archive-up": "linear";
	"arrow-down": "linear";
	"arrow-down-left": "linear";
	"arrow-down-right": "linear";
	"arrow-left": "linear";
	"arrow-right": "linear";
	"arrow-up": "linear";
	"arrow-up-left": "linear";
	"arrow-up-right": "linear";
	"at-sign": "linear";
	"battery": "linear";
	"bell": "linear";
	"bell-off": "linear";
	"bluetooth": "linear";
	"bold": "linear";
	"bolt": "linear";
	"book-open": "linear";
	"bookmark": "linear";
	"bookmarks": "linear";
	"brain": "linear";
	"briefcase": "linear";
	"broadcast": "linear";
	"bug": "linear";
	"building": "linear";
	"bun": "bold";
	"calculator": "linear";
	"calendar": "linear";
	"calendar-add": "linear";
	"calendar-mark": "linear";
	"calendar-remove": "linear";
	"calendar-search": "linear";
	"calendar-x": "linear";
	"camera": "linear";
	"card": "linear";
	"cart": "linear";
	"cart-bag": "linear";
	"cart-large": "linear";
	"chair": "linear";
	"chart-analysis": "linear";
	"chat": "linear";
	"check": "linear";
	"check-double": "linear";
	"chevron-down": "linear";
	"chevron-left": "linear";
	"chevron-right": "linear";
	"chevron-up": "linear";
	"chevrons-down": "linear";
	"chevrons-left": "linear";
	"chevrons-right": "linear";
	"chevrons-up": "linear";
	"chrome": "bold";
	"clapperboard": "linear";
	"clapperboard-text": "linear";
	"claude-ai": "bold";
	"claude-code": "bold";
	"clipboard": "linear";
	"clipboard-add": "linear";
	"clipboard-check": "linear";
	"clipboard-remove": "linear";
	"clock": "linear";
	"close": "linear";
	"cloud": "linear";
	"cloud-download": "linear";
	"cloud-rain": "linear";
	"cloud-upload": "linear";
	"code": "linear";
	"codex": "bold";
	"command": "linear";
	"computer": "linear" | "bold";
	"connect": "linear";
	"copy": "linear";
	"crop": "linear";
	"cursor": "bold";
	"database": "linear";
	"deepseek": "bold";
	"devin": "bold";
	"diamond": "linear";
	"discord": "bold";
	"dislike": "linear";
	"document": "linear";
	"door-open": "linear";
	"download": "linear";
	"droplet": "linear";
	"edit": "linear";
	"edit-off": "linear";
	"email": "linear";
	"external-link": "linear";
	"eye": "linear";
	"eye-closed": "linear";
	"eye-off": "linear";
	"facebook": "bold";
	"figma": "linear";
	"file": "linear";
	"file-add": "linear";
	"file-code": "linear";
	"file-remove": "linear";
	"file-text": "linear";
	"filter": "linear";
	"fingerprint": "linear";
	"flag": "linear";
	"folder": "linear";
	"folder-add": "linear";
	"folder-open": "linear";
	"folder-tree": "linear";
	"folder-with-files": "linear";
	"folders": "linear";
	"forward": "linear";
	"gamepad": "linear";
	"gemini": "bold";
	"gift": "linear";
	"git": "bold";
	"git-branch": "linear";
	"git-diff": "linear";
	"git-fork": "linear";
	"git-graph": "linear";
	"git-pull-request": "linear";
	"github": "bold";
	"github-copilot": "bold";
	"globe": "linear";
	"google": "bold";
	"grip-horizontal": "linear";
	"grip-vertical": "linear";
	"grok": "linear";
	"hand": "linear";
	"hand-wave": "linear";
	"hashtag": "linear";
	"heading": "linear";
	"headphones": "linear";
	"heart": "linear";
	"history": "linear";
	"home": "linear";
	"home-angle": "linear";
	"image": "linear";
	"image-add": "linear";
	"image-edit": "linear";
	"import": "linear";
	"inbox": "linear";
	"incoming-call": "linear";
	"info-square": "linear";
	"instagram": "linear";
	"integration": "linear";
	"italic": "linear";
	"kanban": "linear";
	"key": "linear";
	"keyboard": "linear";
	"kimi": "bold";
	"layers": "linear";
	"layout-align-bottom": "linear";
	"layout-align-left": "linear";
	"layout-align-right": "linear";
	"layout-align-top": "linear";
	"life-buoy": "linear";
	"lightbulb": "linear";
	"lightning": "linear";
	"like": "linear";
	"link": "linear";
	"linkedin": "bold";
	"list": "linear";
	"list-checks": "linear";
	"list-dash": "linear";
	"list-down": "linear";
	"list-filter": "linear";
	"list-up": "linear";
	"lock": "linear";
	"lock-open": "linear";
	"login": "linear";
	"logout": "linear";
	"map": "linear";
	"map-arrow-down": "linear";
	"map-arrow-left": "linear";
	"map-arrow-right": "linear";
	"map-arrow-up": "linear";
	"map-folded": "linear";
	"map-pin": "linear";
	"market-analysis": "linear";
	"maximize": "linear";
	"menu": "linear";
	"meta-ai": "bold";
	"microphone": "linear";
	"microphone-off": "linear";
	"microsoft-copilot": "bold";
	"minimize": "linear";
	"minus": "linear";
	"mistral": "bold";
	"moon": "linear" | "bold";
	"more-horizontal": "linear";
	"more-vertical": "linear";
	"move": "linear";
	"music-note": "linear";
	"navigation": "linear";
	"notebook": "linear";
	"npm": "bold";
	"nvidia": "bold";
	"octagon-x": "linear";
	"openai": "linear";
	"openclaw": "bold";
	"opencode": "bold";
	"outgoing-call": "linear";
	"package": "linear";
	"palette": "linear";
	"paper-plane": "linear";
	"paperclip": "linear";
	"pause": "linear";
	"pen": "linear";
	"perplexity": "linear";
	"phone": "linear";
	"pin": "linear";
	"pinterest": "bold";
	"pip": "linear";
	"play": "linear";
	"play-mini": "linear";
	"power": "linear";
	"printer": "linear";
	"puzzle": "linear";
	"qr-code": "linear";
	"quote": "linear";
	"qwen": "bold";
	"react": "linear";
	"reddit": "bold";
	"redo": "linear";
	"reorder": "linear";
	"repeat": "linear";
	"reply": "linear";
	"resources-add": "linear";
	"rhombus": "linear";
	"rocket": "linear";
	"sad": "linear";
	"search": "linear";
	"send": "linear";
	"server": "linear";
	"settings": "linear";
	"share": "linear";
	"shield-add": "linear";
	"sidebar-bottom": "linear";
	"sidebar-left": "linear";
	"sidebar-right": "linear";
	"sidebar-top": "linear";
	"sim-card": "linear";
	"slack": "bold";
	"slash": "linear";
	"sliders-horizontal": "linear";
	"sliders-horizontal-alt": "linear";
	"sliders-vertical": "linear";
	"sliders-vertical-alt": "linear";
	"smartphone": "linear";
	"smile": "linear";
	"snapchat": "linear" | "bold";
	"snowflake": "linear";
	"soundwave": "linear";
	"sparkles": "linear";
	"spinner": "linear";
	"spinner-arc": "linear";
	"spinner-diagonal": "linear";
	"spinner-orbit": "linear";
	"spinner-wave": "linear";
	"square-pen": "linear";
	"star": "linear";
	"star-off": "linear";
	"sticker": "linear";
	"stop": "linear";
	"stopwatch": "linear";
	"strikethrough": "linear";
	"suitcase": "linear";
	"sun": "linear" | "bold";
	"supabase": "bold";
	"table": "linear";
	"tablet": "linear";
	"telegram": "bold";
	"terminal": "linear";
	"text-align-center": "linear";
	"text-align-justify-left": "linear";
	"text-align-justify-right": "linear";
	"text-align-left": "linear";
	"text-align-right": "linear";
	"text-underline": "linear";
	"threads": "linear";
	"three-squares": "linear";
	"ticket": "linear";
	"ticket-discount": "linear";
	"tiktok": "bold";
	"transfer-horizontal": "linear";
	"transfer-vertical": "linear";
	"trash": "linear";
	"truck": "linear";
	"twitter": "bold";
	"typescript": "bold";
	"undo": "linear";
	"unfold-less": "linear";
	"unfold-more": "linear";
	"upload": "linear";
	"user": "linear";
	"user-add": "linear";
	"user-check": "linear";
	"user-group": "linear";
	"user-remove": "linear";
	"user-x": "linear";
	"vercel": "bold";
	"verified-check": "linear";
	"video-camera": "linear";
	"video-frame": "linear";
	"volume-high": "linear";
	"volume-low": "linear";
	"volume-off": "linear";
	"wallet": "linear";
	"waves": "linear";
	"widget": "linear";
	"widget-add": "linear";
	"widget-square": "linear";
	"widget-square-add": "linear";
	"wifi": "linear";
	"wind": "linear";
	"windsurf": "linear";
	"x": "linear";
	"xai": "linear";
	"youtube": "bold";
	"zai": "bold";
	"zoom-in": "linear";
	"zoom-out": "linear";
};
