/* Generated by scripts/build-icons.ts. Do not edit. */
import type { HoneyIcon } from "./create-icon.js";
import { Activity } from "./icons/activity.js";
import { Add } from "./icons/add.js";
import { Alarm } from "./icons/alarm.js";
import { Album } from "./icons/album.js";
import { AlertTriangle } from "./icons/alert-triangle.js";
import { AlignCenterHorizontal } from "./icons/align-center-horizontal.js";
import { Analytics } from "./icons/analytics.js";
import { Anthropic } from "./icons/anthropic.js";
import { Antigravity } from "./icons/antigravity.js";
import { AppWindow } from "./icons/app-window.js";
import { Archive } from "./icons/archive.js";
import { ArchiveAlt } from "./icons/archive-alt.js";
import { ArchiveUp } from "./icons/archive-up.js";
import { ArrowDown } from "./icons/arrow-down.js";
import { ArrowDownLeft } from "./icons/arrow-down-left.js";
import { ArrowDownRight } from "./icons/arrow-down-right.js";
import { ArrowLeft } from "./icons/arrow-left.js";
import { ArrowRight } from "./icons/arrow-right.js";
import { ArrowUp } from "./icons/arrow-up.js";
import { ArrowUpLeft } from "./icons/arrow-up-left.js";
import { ArrowUpRight } from "./icons/arrow-up-right.js";
import { AtSign } from "./icons/at-sign.js";
import { Atom } from "./icons/atom.js";
import { Award } from "./icons/award.js";
import { Ban } from "./icons/ban.js";
import { Bank } from "./icons/bank.js";
import { Barcode } from "./icons/barcode.js";
import { Battery } from "./icons/battery.js";
import { BatteryCharging } from "./icons/battery-charging.js";
import { BatteryLow } from "./icons/battery-low.js";
import { Bell } from "./icons/bell.js";
import { BellOff } from "./icons/bell-off.js";
import { BellRing } from "./icons/bell-ring.js";
import { Bluetooth } from "./icons/bluetooth.js";
import { Bold } from "./icons/bold.js";
import { Bolt } from "./icons/bolt.js";
import { Book } from "./icons/book.js";
import { BookOpen } from "./icons/book-open.js";
import { Bookmark } from "./icons/bookmark.js";
import { Bookmarks } from "./icons/bookmarks.js";
import { Bot } from "./icons/bot.js";
import { Braces } from "./icons/braces.js";
import { Brain } from "./icons/brain.js";
import { Briefcase } from "./icons/briefcase.js";
import { Broadcast } from "./icons/broadcast.js";
import { Bug } from "./icons/bug.js";
import { Building } from "./icons/building.js";
import { Bun } from "./icons/bun.js";
import { Calculator } from "./icons/calculator.js";
import { Calendar } from "./icons/calendar.js";
import { CalendarAdd } from "./icons/calendar-add.js";
import { CalendarCheck } from "./icons/calendar-check.js";
import { CalendarMark } from "./icons/calendar-mark.js";
import { CalendarRange } from "./icons/calendar-range.js";
import { CalendarRemove } from "./icons/calendar-remove.js";
import { CalendarSearch } from "./icons/calendar-search.js";
import { CalendarX } from "./icons/calendar-x.js";
import { Camera } from "./icons/camera.js";
import { CameraOff } from "./icons/camera-off.js";
import { Captions } from "./icons/captions.js";
import { Card } from "./icons/card.js";
import { Cart } from "./icons/cart.js";
import { CartBag } from "./icons/cart-bag.js";
import { CartLarge } from "./icons/cart-large.js";
import { Chair } from "./icons/chair.js";
import { ChartAnalysis } from "./icons/chart-analysis.js";
import { ChartLine } from "./icons/chart-line.js";
import { ChartPie } from "./icons/chart-pie.js";
import { Chat } from "./icons/chat.js";
import { Check } from "./icons/check.js";
import { CheckDouble } from "./icons/check-double.js";
import { ChevronDown } from "./icons/chevron-down.js";
import { ChevronLeft } from "./icons/chevron-left.js";
import { ChevronRight } from "./icons/chevron-right.js";
import { ChevronUp } from "./icons/chevron-up.js";
import { ChevronsDown } from "./icons/chevrons-down.js";
import { ChevronsLeft } from "./icons/chevrons-left.js";
import { ChevronsRight } from "./icons/chevrons-right.js";
import { ChevronsUp } from "./icons/chevrons-up.js";
import { Chrome } from "./icons/chrome.js";
import { Clapperboard } from "./icons/clapperboard.js";
import { ClapperboardText } from "./icons/clapperboard-text.js";
import { ClaudeAi } from "./icons/claude-ai.js";
import { ClaudeCode } from "./icons/claude-code.js";
import { Clipboard } from "./icons/clipboard.js";
import { ClipboardAdd } from "./icons/clipboard-add.js";
import { ClipboardCheck } from "./icons/clipboard-check.js";
import { ClipboardRemove } from "./icons/clipboard-remove.js";
import { Clock } from "./icons/clock.js";
import { Close } from "./icons/close.js";
import { Cloud } from "./icons/cloud.js";
import { CloudDownload } from "./icons/cloud-download.js";
import { CloudRain } from "./icons/cloud-rain.js";
import { CloudUpload } from "./icons/cloud-upload.js";
import { Code } from "./icons/code.js";
import { Codex } from "./icons/codex.js";
import { Columns } from "./icons/columns.js";
import { Command } from "./icons/command.js";
import { Computer } from "./icons/computer.js";
import { Connect } from "./icons/connect.js";
import { Copy } from "./icons/copy.js";
import { CornerDownRight } from "./icons/corner-down-right.js";
import { Crop } from "./icons/crop.js";
import { Crown } from "./icons/crown.js";
import { Cursor } from "./icons/cursor.js";
import { CursorClick } from "./icons/cursor-click.js";
import { Dashboard } from "./icons/dashboard.js";
import { Database } from "./icons/database.js";
import { Deepseek } from "./icons/deepseek.js";
import { Devin } from "./icons/devin.js";
import { Diamond } from "./icons/diamond.js";
import { Discord } from "./icons/discord.js";
import { Dislike } from "./icons/dislike.js";
import { Document } from "./icons/document.js";
import { Dollar } from "./icons/dollar.js";
import { DoorOpen } from "./icons/door-open.js";
import { Download } from "./icons/download.js";
import { Droplet } from "./icons/droplet.js";
import { Edit } from "./icons/edit.js";
import { EditOff } from "./icons/edit-off.js";
import { Email } from "./icons/email.js";
import { Eraser } from "./icons/eraser.js";
import { ExternalLink } from "./icons/external-link.js";
import { Eye } from "./icons/eye.js";
import { EyeClosed } from "./icons/eye-closed.js";
import { EyeOff } from "./icons/eye-off.js";
import { Facebook } from "./icons/facebook.js";
import { Figma } from "./icons/figma.js";
import { File } from "./icons/file.js";
import { FileAdd } from "./icons/file-add.js";
import { FileArchive } from "./icons/file-archive.js";
import { FileCode } from "./icons/file-code.js";
import { FileImage } from "./icons/file-image.js";
import { FileRemove } from "./icons/file-remove.js";
import { FileSearch } from "./icons/file-search.js";
import { FileSpreadsheet } from "./icons/file-spreadsheet.js";
import { FileText } from "./icons/file-text.js";
import { FileVideo } from "./icons/file-video.js";
import { Film } from "./icons/film.js";
import { Filter } from "./icons/filter.js";
import { Fingerprint } from "./icons/fingerprint.js";
import { Flag } from "./icons/flag.js";
import { FlipHorizontal } from "./icons/flip-horizontal.js";
import { Folder } from "./icons/folder.js";
import { FolderAdd } from "./icons/folder-add.js";
import { FolderLock } from "./icons/folder-lock.js";
import { FolderOpen } from "./icons/folder-open.js";
import { FolderRemove } from "./icons/folder-remove.js";
import { FolderSearch } from "./icons/folder-search.js";
import { FolderTree } from "./icons/folder-tree.js";
import { FolderWithFiles } from "./icons/folder-with-files.js";
import { Folders } from "./icons/folders.js";
import { Forward } from "./icons/forward.js";
import { Gamepad } from "./icons/gamepad.js";
import { Gauge } from "./icons/gauge.js";
import { Gemini } from "./icons/gemini.js";
import { Gift } from "./icons/gift.js";
import { Git } from "./icons/git.js";
import { GitBranch } from "./icons/git-branch.js";
import { GitCommit } from "./icons/git-commit.js";
import { GitDiff } from "./icons/git-diff.js";
import { GitFork } from "./icons/git-fork.js";
import { GitGraph } from "./icons/git-graph.js";
import { GitMerge } from "./icons/git-merge.js";
import { GitPullRequest } from "./icons/git-pull-request.js";
import { Github } from "./icons/github.js";
import { GithubCopilot } from "./icons/github-copilot.js";
import { Globe } from "./icons/globe.js";
import { Google } from "./icons/google.js";
import { GraduationCap } from "./icons/graduation-cap.js";
import { GripHorizontal } from "./icons/grip-horizontal.js";
import { GripVertical } from "./icons/grip-vertical.js";
import { Grok } from "./icons/grok.js";
import { Hammer } from "./icons/hammer.js";
import { Hand } from "./icons/hand.js";
import { HandWave } from "./icons/hand-wave.js";
import { Hashtag } from "./icons/hashtag.js";
import { Heading } from "./icons/heading.js";
import { Heading1 } from "./icons/heading-1.js";
import { Heading2 } from "./icons/heading-2.js";
import { Heading3 } from "./icons/heading-3.js";
import { Headphones } from "./icons/headphones.js";
import { Heart } from "./icons/heart.js";
import { History } from "./icons/history.js";
import { Home } from "./icons/home.js";
import { HomeAngle } from "./icons/home-angle.js";
import { Hourglass } from "./icons/hourglass.js";
import { Image } from "./icons/image.js";
import { ImageAdd } from "./icons/image-add.js";
import { ImageEdit } from "./icons/image-edit.js";
import { Images } from "./icons/images.js";
import { Import } from "./icons/import.js";
import { Inbox } from "./icons/inbox.js";
import { IncomingCall } from "./icons/incoming-call.js";
import { Indent } from "./icons/indent.js";
import { InfoSquare } from "./icons/info-square.js";
import { Instagram } from "./icons/instagram.js";
import { Integration } from "./icons/integration.js";
import { Italic } from "./icons/italic.js";
import { Kanban } from "./icons/kanban.js";
import { Key } from "./icons/key.js";
import { Keyboard } from "./icons/keyboard.js";
import { Kimi } from "./icons/kimi.js";
import { Laptop } from "./icons/laptop.js";
import { Layers } from "./icons/layers.js";
import { LayoutAlignBottom } from "./icons/layout-align-bottom.js";
import { LayoutAlignLeft } from "./icons/layout-align-left.js";
import { LayoutAlignRight } from "./icons/layout-align-right.js";
import { LayoutAlignTop } from "./icons/layout-align-top.js";
import { LayoutList } from "./icons/layout-list.js";
import { Library } from "./icons/library.js";
import { LifeBuoy } from "./icons/life-buoy.js";
import { Lightbulb } from "./icons/lightbulb.js";
import { Lightning } from "./icons/lightning.js";
import { Like } from "./icons/like.js";
import { Link } from "./icons/link.js";
import { Linkedin } from "./icons/linkedin.js";
import { List } from "./icons/list.js";
import { ListChecks } from "./icons/list-checks.js";
import { ListDash } from "./icons/list-dash.js";
import { ListDown } from "./icons/list-down.js";
import { ListFilter } from "./icons/list-filter.js";
import { ListOrdered } from "./icons/list-ordered.js";
import { ListUp } from "./icons/list-up.js";
import { Locate } from "./icons/locate.js";
import { Lock } from "./icons/lock.js";
import { LockOpen } from "./icons/lock-open.js";
import { Login } from "./icons/login.js";
import { Logout } from "./icons/logout.js";
import { MagicWand } from "./icons/magic-wand.js";
import { Map } from "./icons/map.js";
import { MapArrowDown } from "./icons/map-arrow-down.js";
import { MapArrowLeft } from "./icons/map-arrow-left.js";
import { MapArrowRight } from "./icons/map-arrow-right.js";
import { MapArrowUp } from "./icons/map-arrow-up.js";
import { MapFolded } from "./icons/map-folded.js";
import { MapPin } from "./icons/map-pin.js";
import { MarketAnalysis } from "./icons/market-analysis.js";
import { Maximize } from "./icons/maximize.js";
import { Megaphone } from "./icons/megaphone.js";
import { Menu } from "./icons/menu.js";
import { MetaAi } from "./icons/meta-ai.js";
import { Microphone } from "./icons/microphone.js";
import { MicrophoneOff } from "./icons/microphone-off.js";
import { MicrosoftCopilot } from "./icons/microsoft-copilot.js";
import { Minimize } from "./icons/minimize.js";
import { Minus } from "./icons/minus.js";
import { Mistral } from "./icons/mistral.js";
import { Moon } from "./icons/moon.js";
import { MoreHorizontal } from "./icons/more-horizontal.js";
import { MoreVertical } from "./icons/more-vertical.js";
import { Mouse } from "./icons/mouse.js";
import { Move } from "./icons/move.js";
import { MusicNote } from "./icons/music-note.js";
import { Navigation } from "./icons/navigation.js";
import { Newspaper } from "./icons/newspaper.js";
import { Notebook } from "./icons/notebook.js";
import { Npm } from "./icons/npm.js";
import { Nvidia } from "./icons/nvidia.js";
import { OctagonX } from "./icons/octagon-x.js";
import { Openai } from "./icons/openai.js";
import { Openclaw } from "./icons/openclaw.js";
import { Opencode } from "./icons/opencode.js";
import { Outdent } from "./icons/outdent.js";
import { OutgoingCall } from "./icons/outgoing-call.js";
import { Package } from "./icons/package.js";
import { Palette } from "./icons/palette.js";
import { PaperPlane } from "./icons/paper-plane.js";
import { Paperclip } from "./icons/paperclip.js";
import { Pause } from "./icons/pause.js";
import { Pen } from "./icons/pen.js";
import { Percent } from "./icons/percent.js";
import { Perplexity } from "./icons/perplexity.js";
import { Phone } from "./icons/phone.js";
import { PhoneOff } from "./icons/phone-off.js";
import { Pin } from "./icons/pin.js";
import { PinOff } from "./icons/pin-off.js";
import { Pinterest } from "./icons/pinterest.js";
import { Pip } from "./icons/pip.js";
import { Pipette } from "./icons/pipette.js";
import { Plane } from "./icons/plane.js";
import { Play } from "./icons/play.js";
import { PlayMini } from "./icons/play-mini.js";
import { Playlist } from "./icons/playlist.js";
import { Podcast } from "./icons/podcast.js";
import { Pointer } from "./icons/pointer.js";
import { Power } from "./icons/power.js";
import { Presentation } from "./icons/presentation.js";
import { Printer } from "./icons/printer.js";
import { Puzzle } from "./icons/puzzle.js";
import { QrCode } from "./icons/qr-code.js";
import { QuestionMark } from "./icons/question-mark.js";
import { Quote } from "./icons/quote.js";
import { Qwen } from "./icons/qwen.js";
import { React } from "./icons/react.js";
import { Receipt } from "./icons/receipt.js";
import { Reddit } from "./icons/reddit.js";
import { Redo } from "./icons/redo.js";
import { Refresh } from "./icons/refresh.js";
import { Reorder } from "./icons/reorder.js";
import { Repeat } from "./icons/repeat.js";
import { RepeatOne } from "./icons/repeat-one.js";
import { Reply } from "./icons/reply.js";
import { ResourcesAdd } from "./icons/resources-add.js";
import { Rewind } from "./icons/rewind.js";
import { Rhombus } from "./icons/rhombus.js";
import { Rocket } from "./icons/rocket.js";
import { RotateCcw } from "./icons/rotate-ccw.js";
import { RotateCw } from "./icons/rotate-cw.js";
import { Route } from "./icons/route.js";
import { Router } from "./icons/router.js";
import { Rows } from "./icons/rows.js";
import { Ruler } from "./icons/ruler.js";
import { Sad } from "./icons/sad.js";
import { Save } from "./icons/save.js";
import { Scan } from "./icons/scan.js";
import { ScreenShare } from "./icons/screen-share.js";
import { Search } from "./icons/search.js";
import { Send } from "./icons/send.js";
import { Server } from "./icons/server.js";
import { Settings } from "./icons/settings.js";
import { Share } from "./icons/share.js";
import { ShieldAdd } from "./icons/shield-add.js";
import { Shuffle } from "./icons/shuffle.js";
import { SidebarBottom } from "./icons/sidebar-bottom.js";
import { SidebarLeft } from "./icons/sidebar-left.js";
import { SidebarRight } from "./icons/sidebar-right.js";
import { SidebarTop } from "./icons/sidebar-top.js";
import { Signal } from "./icons/signal.js";
import { SimCard } from "./icons/sim-card.js";
import { SkipBack } from "./icons/skip-back.js";
import { SkipForward } from "./icons/skip-forward.js";
import { Slack } from "./icons/slack.js";
import { Slash } from "./icons/slash.js";
import { SlidersHorizontal } from "./icons/sliders-horizontal.js";
import { SlidersHorizontalAlt } from "./icons/sliders-horizontal-alt.js";
import { SlidersVertical } from "./icons/sliders-vertical.js";
import { SlidersVerticalAlt } from "./icons/sliders-vertical-alt.js";
import { Smartphone } from "./icons/smartphone.js";
import { Smile } from "./icons/smile.js";
import { Snapchat } from "./icons/snapchat.js";
import { Snowflake } from "./icons/snowflake.js";
import { SortAscending } from "./icons/sort-ascending.js";
import { SortDescending } from "./icons/sort-descending.js";
import { Soundwave } from "./icons/soundwave.js";
import { Sparkles } from "./icons/sparkles.js";
import { Spinner } from "./icons/spinner.js";
import { SpinnerArc } from "./icons/spinner-arc.js";
import { SpinnerDiagonal } from "./icons/spinner-diagonal.js";
import { SpinnerOrbit } from "./icons/spinner-orbit.js";
import { SpinnerWave } from "./icons/spinner-wave.js";
import { SquarePen } from "./icons/square-pen.js";
import { Star } from "./icons/star.js";
import { StarOff } from "./icons/star-off.js";
import { Sticker } from "./icons/sticker.js";
import { StickyNote } from "./icons/sticky-note.js";
import { Stop } from "./icons/stop.js";
import { Stopwatch } from "./icons/stopwatch.js";
import { Store } from "./icons/store.js";
import { Strikethrough } from "./icons/strikethrough.js";
import { Suitcase } from "./icons/suitcase.js";
import { Sun } from "./icons/sun.js";
import { SunMoon } from "./icons/sun-moon.js";
import { Supabase } from "./icons/supabase.js";
import { Superscript } from "./icons/superscript.js";
import { Table } from "./icons/table.js";
import { Tablet } from "./icons/tablet.js";
import { Tag } from "./icons/tag.js";
import { Target } from "./icons/target.js";
import { Telegram } from "./icons/telegram.js";
import { Terminal } from "./icons/terminal.js";
import { TextAlignCenter } from "./icons/text-align-center.js";
import { TextAlignJustifyLeft } from "./icons/text-align-justify-left.js";
import { TextAlignJustifyRight } from "./icons/text-align-justify-right.js";
import { TextAlignLeft } from "./icons/text-align-left.js";
import { TextAlignRight } from "./icons/text-align-right.js";
import { TextSize } from "./icons/text-size.js";
import { TextUnderline } from "./icons/text-underline.js";
import { Threads } from "./icons/threads.js";
import { ThreeSquares } from "./icons/three-squares.js";
import { Ticket } from "./icons/ticket.js";
import { TicketDiscount } from "./icons/ticket-discount.js";
import { Tiktok } from "./icons/tiktok.js";
import { Toggle } from "./icons/toggle.js";
import { TransferHorizontal } from "./icons/transfer-horizontal.js";
import { TransferVertical } from "./icons/transfer-vertical.js";
import { Trash } from "./icons/trash.js";
import { TrendingDown } from "./icons/trending-down.js";
import { TrendingUp } from "./icons/trending-up.js";
import { Trophy } from "./icons/trophy.js";
import { Truck } from "./icons/truck.js";
import { Tv } from "./icons/tv.js";
import { Twitter } from "./icons/twitter.js";
import { Type } from "./icons/type.js";
import { Typescript } from "./icons/typescript.js";
import { Undo } from "./icons/undo.js";
import { UnfoldLess } from "./icons/unfold-less.js";
import { UnfoldMore } from "./icons/unfold-more.js";
import { Unlink } from "./icons/unlink.js";
import { Upload } from "./icons/upload.js";
import { Usb } from "./icons/usb.js";
import { User } from "./icons/user.js";
import { UserAdd } from "./icons/user-add.js";
import { UserCheck } from "./icons/user-check.js";
import { UserGroup } from "./icons/user-group.js";
import { UserLock } from "./icons/user-lock.js";
import { UserRemove } from "./icons/user-remove.js";
import { UserSettings } from "./icons/user-settings.js";
import { UserX } from "./icons/user-x.js";
import { Variable } from "./icons/variable.js";
import { Vercel } from "./icons/vercel.js";
import { VerifiedCheck } from "./icons/verified-check.js";
import { VideoCamera } from "./icons/video-camera.js";
import { VideoFrame } from "./icons/video-frame.js";
import { VideoOff } from "./icons/video-off.js";
import { VolumeHigh } from "./icons/volume-high.js";
import { VolumeLow } from "./icons/volume-low.js";
import { VolumeOff } from "./icons/volume-off.js";
import { Wallet } from "./icons/wallet.js";
import { Waves } from "./icons/waves.js";
import { Webcam } from "./icons/webcam.js";
import { Webhook } from "./icons/webhook.js";
import { Widget } from "./icons/widget.js";
import { WidgetAdd } from "./icons/widget-add.js";
import { WidgetSquare } from "./icons/widget-square.js";
import { WidgetSquareAdd } from "./icons/widget-square-add.js";
import { Wifi } from "./icons/wifi.js";
import { WifiOff } from "./icons/wifi-off.js";
import { Wind } from "./icons/wind.js";
import { Windsurf } from "./icons/windsurf.js";
import { X } from "./icons/x.js";
import { Xai } from "./icons/xai.js";
import { Youtube } from "./icons/youtube.js";
import { Zai } from "./icons/zai.js";
import { ZoomIn } from "./icons/zoom-in.js";
import { ZoomOut } from "./icons/zoom-out.js";

export const icons = {
	"activity": Activity,
	"add": Add,
	"alarm": Alarm,
	"album": Album,
	"alert-triangle": AlertTriangle,
	"align-center-horizontal": AlignCenterHorizontal,
	"analytics": Analytics,
	"anthropic": Anthropic,
	"antigravity": Antigravity,
	"app-window": AppWindow,
	"archive": Archive,
	"archive-alt": ArchiveAlt,
	"archive-up": ArchiveUp,
	"arrow-down": ArrowDown,
	"arrow-down-left": ArrowDownLeft,
	"arrow-down-right": ArrowDownRight,
	"arrow-left": ArrowLeft,
	"arrow-right": ArrowRight,
	"arrow-up": ArrowUp,
	"arrow-up-left": ArrowUpLeft,
	"arrow-up-right": ArrowUpRight,
	"at-sign": AtSign,
	"atom": Atom,
	"award": Award,
	"ban": Ban,
	"bank": Bank,
	"barcode": Barcode,
	"battery": Battery,
	"battery-charging": BatteryCharging,
	"battery-low": BatteryLow,
	"bell": Bell,
	"bell-off": BellOff,
	"bell-ring": BellRing,
	"bluetooth": Bluetooth,
	"bold": Bold,
	"bolt": Bolt,
	"book": Book,
	"book-open": BookOpen,
	"bookmark": Bookmark,
	"bookmarks": Bookmarks,
	"bot": Bot,
	"braces": Braces,
	"brain": Brain,
	"briefcase": Briefcase,
	"broadcast": Broadcast,
	"bug": Bug,
	"building": Building,
	"bun": Bun,
	"calculator": Calculator,
	"calendar": Calendar,
	"calendar-add": CalendarAdd,
	"calendar-check": CalendarCheck,
	"calendar-mark": CalendarMark,
	"calendar-range": CalendarRange,
	"calendar-remove": CalendarRemove,
	"calendar-search": CalendarSearch,
	"calendar-x": CalendarX,
	"camera": Camera,
	"camera-off": CameraOff,
	"captions": Captions,
	"card": Card,
	"cart": Cart,
	"cart-bag": CartBag,
	"cart-large": CartLarge,
	"chair": Chair,
	"chart-analysis": ChartAnalysis,
	"chart-line": ChartLine,
	"chart-pie": ChartPie,
	"chat": Chat,
	"check": Check,
	"check-double": CheckDouble,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"chevron-right": ChevronRight,
	"chevron-up": ChevronUp,
	"chevrons-down": ChevronsDown,
	"chevrons-left": ChevronsLeft,
	"chevrons-right": ChevronsRight,
	"chevrons-up": ChevronsUp,
	"chrome": Chrome,
	"clapperboard": Clapperboard,
	"clapperboard-text": ClapperboardText,
	"claude-ai": ClaudeAi,
	"claude-code": ClaudeCode,
	"clipboard": Clipboard,
	"clipboard-add": ClipboardAdd,
	"clipboard-check": ClipboardCheck,
	"clipboard-remove": ClipboardRemove,
	"clock": Clock,
	"close": Close,
	"cloud": Cloud,
	"cloud-download": CloudDownload,
	"cloud-rain": CloudRain,
	"cloud-upload": CloudUpload,
	"code": Code,
	"codex": Codex,
	"columns": Columns,
	"command": Command,
	"computer": Computer,
	"connect": Connect,
	"copy": Copy,
	"corner-down-right": CornerDownRight,
	"crop": Crop,
	"crown": Crown,
	"cursor": Cursor,
	"cursor-click": CursorClick,
	"dashboard": Dashboard,
	"database": Database,
	"deepseek": Deepseek,
	"devin": Devin,
	"diamond": Diamond,
	"discord": Discord,
	"dislike": Dislike,
	"document": Document,
	"dollar": Dollar,
	"door-open": DoorOpen,
	"download": Download,
	"droplet": Droplet,
	"edit": Edit,
	"edit-off": EditOff,
	"email": Email,
	"eraser": Eraser,
	"external-link": ExternalLink,
	"eye": Eye,
	"eye-closed": EyeClosed,
	"eye-off": EyeOff,
	"facebook": Facebook,
	"figma": Figma,
	"file": File,
	"file-add": FileAdd,
	"file-archive": FileArchive,
	"file-code": FileCode,
	"file-image": FileImage,
	"file-remove": FileRemove,
	"file-search": FileSearch,
	"file-spreadsheet": FileSpreadsheet,
	"file-text": FileText,
	"file-video": FileVideo,
	"film": Film,
	"filter": Filter,
	"fingerprint": Fingerprint,
	"flag": Flag,
	"flip-horizontal": FlipHorizontal,
	"folder": Folder,
	"folder-add": FolderAdd,
	"folder-lock": FolderLock,
	"folder-open": FolderOpen,
	"folder-remove": FolderRemove,
	"folder-search": FolderSearch,
	"folder-tree": FolderTree,
	"folder-with-files": FolderWithFiles,
	"folders": Folders,
	"forward": Forward,
	"gamepad": Gamepad,
	"gauge": Gauge,
	"gemini": Gemini,
	"gift": Gift,
	"git": Git,
	"git-branch": GitBranch,
	"git-commit": GitCommit,
	"git-diff": GitDiff,
	"git-fork": GitFork,
	"git-graph": GitGraph,
	"git-merge": GitMerge,
	"git-pull-request": GitPullRequest,
	"github": Github,
	"github-copilot": GithubCopilot,
	"globe": Globe,
	"google": Google,
	"graduation-cap": GraduationCap,
	"grip-horizontal": GripHorizontal,
	"grip-vertical": GripVertical,
	"grok": Grok,
	"hammer": Hammer,
	"hand": Hand,
	"hand-wave": HandWave,
	"hashtag": Hashtag,
	"heading": Heading,
	"heading-1": Heading1,
	"heading-2": Heading2,
	"heading-3": Heading3,
	"headphones": Headphones,
	"heart": Heart,
	"history": History,
	"home": Home,
	"home-angle": HomeAngle,
	"hourglass": Hourglass,
	"image": Image,
	"image-add": ImageAdd,
	"image-edit": ImageEdit,
	"images": Images,
	"import": Import,
	"inbox": Inbox,
	"incoming-call": IncomingCall,
	"indent": Indent,
	"info-square": InfoSquare,
	"instagram": Instagram,
	"integration": Integration,
	"italic": Italic,
	"kanban": Kanban,
	"key": Key,
	"keyboard": Keyboard,
	"kimi": Kimi,
	"laptop": Laptop,
	"layers": Layers,
	"layout-align-bottom": LayoutAlignBottom,
	"layout-align-left": LayoutAlignLeft,
	"layout-align-right": LayoutAlignRight,
	"layout-align-top": LayoutAlignTop,
	"layout-list": LayoutList,
	"library": Library,
	"life-buoy": LifeBuoy,
	"lightbulb": Lightbulb,
	"lightning": Lightning,
	"like": Like,
	"link": Link,
	"linkedin": Linkedin,
	"list": List,
	"list-checks": ListChecks,
	"list-dash": ListDash,
	"list-down": ListDown,
	"list-filter": ListFilter,
	"list-ordered": ListOrdered,
	"list-up": ListUp,
	"locate": Locate,
	"lock": Lock,
	"lock-open": LockOpen,
	"login": Login,
	"logout": Logout,
	"magic-wand": MagicWand,
	"map": Map,
	"map-arrow-down": MapArrowDown,
	"map-arrow-left": MapArrowLeft,
	"map-arrow-right": MapArrowRight,
	"map-arrow-up": MapArrowUp,
	"map-folded": MapFolded,
	"map-pin": MapPin,
	"market-analysis": MarketAnalysis,
	"maximize": Maximize,
	"megaphone": Megaphone,
	"menu": Menu,
	"meta-ai": MetaAi,
	"microphone": Microphone,
	"microphone-off": MicrophoneOff,
	"microsoft-copilot": MicrosoftCopilot,
	"minimize": Minimize,
	"minus": Minus,
	"mistral": Mistral,
	"moon": Moon,
	"more-horizontal": MoreHorizontal,
	"more-vertical": MoreVertical,
	"mouse": Mouse,
	"move": Move,
	"music-note": MusicNote,
	"navigation": Navigation,
	"newspaper": Newspaper,
	"notebook": Notebook,
	"npm": Npm,
	"nvidia": Nvidia,
	"octagon-x": OctagonX,
	"openai": Openai,
	"openclaw": Openclaw,
	"opencode": Opencode,
	"outdent": Outdent,
	"outgoing-call": OutgoingCall,
	"package": Package,
	"palette": Palette,
	"paper-plane": PaperPlane,
	"paperclip": Paperclip,
	"pause": Pause,
	"pen": Pen,
	"percent": Percent,
	"perplexity": Perplexity,
	"phone": Phone,
	"phone-off": PhoneOff,
	"pin": Pin,
	"pin-off": PinOff,
	"pinterest": Pinterest,
	"pip": Pip,
	"pipette": Pipette,
	"plane": Plane,
	"play": Play,
	"play-mini": PlayMini,
	"playlist": Playlist,
	"podcast": Podcast,
	"pointer": Pointer,
	"power": Power,
	"presentation": Presentation,
	"printer": Printer,
	"puzzle": Puzzle,
	"qr-code": QrCode,
	"question-mark": QuestionMark,
	"quote": Quote,
	"qwen": Qwen,
	"react": React,
	"receipt": Receipt,
	"reddit": Reddit,
	"redo": Redo,
	"refresh": Refresh,
	"reorder": Reorder,
	"repeat": Repeat,
	"repeat-one": RepeatOne,
	"reply": Reply,
	"resources-add": ResourcesAdd,
	"rewind": Rewind,
	"rhombus": Rhombus,
	"rocket": Rocket,
	"rotate-ccw": RotateCcw,
	"rotate-cw": RotateCw,
	"route": Route,
	"router": Router,
	"rows": Rows,
	"ruler": Ruler,
	"sad": Sad,
	"save": Save,
	"scan": Scan,
	"screen-share": ScreenShare,
	"search": Search,
	"send": Send,
	"server": Server,
	"settings": Settings,
	"share": Share,
	"shield-add": ShieldAdd,
	"shuffle": Shuffle,
	"sidebar-bottom": SidebarBottom,
	"sidebar-left": SidebarLeft,
	"sidebar-right": SidebarRight,
	"sidebar-top": SidebarTop,
	"signal": Signal,
	"sim-card": SimCard,
	"skip-back": SkipBack,
	"skip-forward": SkipForward,
	"slack": Slack,
	"slash": Slash,
	"sliders-horizontal": SlidersHorizontal,
	"sliders-horizontal-alt": SlidersHorizontalAlt,
	"sliders-vertical": SlidersVertical,
	"sliders-vertical-alt": SlidersVerticalAlt,
	"smartphone": Smartphone,
	"smile": Smile,
	"snapchat": Snapchat,
	"snowflake": Snowflake,
	"sort-ascending": SortAscending,
	"sort-descending": SortDescending,
	"soundwave": Soundwave,
	"sparkles": Sparkles,
	"spinner": Spinner,
	"spinner-arc": SpinnerArc,
	"spinner-diagonal": SpinnerDiagonal,
	"spinner-orbit": SpinnerOrbit,
	"spinner-wave": SpinnerWave,
	"square-pen": SquarePen,
	"star": Star,
	"star-off": StarOff,
	"sticker": Sticker,
	"sticky-note": StickyNote,
	"stop": Stop,
	"stopwatch": Stopwatch,
	"store": Store,
	"strikethrough": Strikethrough,
	"suitcase": Suitcase,
	"sun": Sun,
	"sun-moon": SunMoon,
	"supabase": Supabase,
	"superscript": Superscript,
	"table": Table,
	"tablet": Tablet,
	"tag": Tag,
	"target": Target,
	"telegram": Telegram,
	"terminal": Terminal,
	"text-align-center": TextAlignCenter,
	"text-align-justify-left": TextAlignJustifyLeft,
	"text-align-justify-right": TextAlignJustifyRight,
	"text-align-left": TextAlignLeft,
	"text-align-right": TextAlignRight,
	"text-size": TextSize,
	"text-underline": TextUnderline,
	"threads": Threads,
	"three-squares": ThreeSquares,
	"ticket": Ticket,
	"ticket-discount": TicketDiscount,
	"tiktok": Tiktok,
	"toggle": Toggle,
	"transfer-horizontal": TransferHorizontal,
	"transfer-vertical": TransferVertical,
	"trash": Trash,
	"trending-down": TrendingDown,
	"trending-up": TrendingUp,
	"trophy": Trophy,
	"truck": Truck,
	"tv": Tv,
	"twitter": Twitter,
	"type": Type,
	"typescript": Typescript,
	"undo": Undo,
	"unfold-less": UnfoldLess,
	"unfold-more": UnfoldMore,
	"unlink": Unlink,
	"upload": Upload,
	"usb": Usb,
	"user": User,
	"user-add": UserAdd,
	"user-check": UserCheck,
	"user-group": UserGroup,
	"user-lock": UserLock,
	"user-remove": UserRemove,
	"user-settings": UserSettings,
	"user-x": UserX,
	"variable": Variable,
	"vercel": Vercel,
	"verified-check": VerifiedCheck,
	"video-camera": VideoCamera,
	"video-frame": VideoFrame,
	"video-off": VideoOff,
	"volume-high": VolumeHigh,
	"volume-low": VolumeLow,
	"volume-off": VolumeOff,
	"wallet": Wallet,
	"waves": Waves,
	"webcam": Webcam,
	"webhook": Webhook,
	"widget": Widget,
	"widget-add": WidgetAdd,
	"widget-square": WidgetSquare,
	"widget-square-add": WidgetSquareAdd,
	"wifi": Wifi,
	"wifi-off": WifiOff,
	"wind": Wind,
	"windsurf": Windsurf,
	"x": X,
	"xai": Xai,
	"youtube": Youtube,
	"zai": Zai,
	"zoom-in": ZoomIn,
	"zoom-out": ZoomOut,
} satisfies Record<string, HoneyIcon>;

export type IconName = keyof typeof icons;

export type IconVariantMap = {
	"activity": "linear" | "bold";
	"add": "linear" | "bold";
	"alarm": "linear" | "bold";
	"album": "linear" | "bold";
	"alert-triangle": "linear" | "bold";
	"align-center-horizontal": "linear" | "bold";
	"analytics": "linear" | "bold";
	"anthropic": "linear" | "bold";
	"antigravity": "linear" | "bold";
	"app-window": "linear" | "bold";
	"archive": "linear" | "bold";
	"archive-alt": "linear" | "bold";
	"archive-up": "linear" | "bold";
	"arrow-down": "linear" | "bold";
	"arrow-down-left": "linear" | "bold";
	"arrow-down-right": "linear" | "bold";
	"arrow-left": "linear" | "bold";
	"arrow-right": "linear" | "bold";
	"arrow-up": "linear" | "bold";
	"arrow-up-left": "linear" | "bold";
	"arrow-up-right": "linear" | "bold";
	"at-sign": "linear" | "bold";
	"atom": "linear" | "bold";
	"award": "linear" | "bold";
	"ban": "linear" | "bold";
	"bank": "linear" | "bold";
	"barcode": "linear" | "bold";
	"battery": "linear" | "bold";
	"battery-charging": "linear" | "bold";
	"battery-low": "linear" | "bold";
	"bell": "linear" | "bold";
	"bell-off": "linear" | "bold";
	"bell-ring": "linear" | "bold";
	"bluetooth": "linear" | "bold";
	"bold": "linear" | "bold";
	"bolt": "linear" | "bold";
	"book": "linear" | "bold";
	"book-open": "linear" | "bold";
	"bookmark": "linear" | "bold";
	"bookmarks": "linear" | "bold";
	"bot": "linear" | "bold";
	"braces": "linear" | "bold";
	"brain": "linear" | "bold";
	"briefcase": "linear" | "bold";
	"broadcast": "linear" | "bold";
	"bug": "linear" | "bold";
	"building": "linear" | "bold";
	"bun": "linear" | "bold";
	"calculator": "linear" | "bold";
	"calendar": "linear" | "bold";
	"calendar-add": "linear" | "bold";
	"calendar-check": "linear" | "bold";
	"calendar-mark": "linear" | "bold";
	"calendar-range": "linear" | "bold";
	"calendar-remove": "linear" | "bold";
	"calendar-search": "linear" | "bold";
	"calendar-x": "linear" | "bold";
	"camera": "linear" | "bold";
	"camera-off": "linear" | "bold";
	"captions": "linear" | "bold";
	"card": "linear" | "bold";
	"cart": "linear" | "bold";
	"cart-bag": "linear" | "bold";
	"cart-large": "linear" | "bold";
	"chair": "linear" | "bold";
	"chart-analysis": "linear" | "bold";
	"chart-line": "linear" | "bold";
	"chart-pie": "linear" | "bold";
	"chat": "linear" | "bold";
	"check": "linear" | "bold";
	"check-double": "linear" | "bold";
	"chevron-down": "linear" | "bold";
	"chevron-left": "linear" | "bold";
	"chevron-right": "linear" | "bold";
	"chevron-up": "linear" | "bold";
	"chevrons-down": "linear" | "bold";
	"chevrons-left": "linear" | "bold";
	"chevrons-right": "linear" | "bold";
	"chevrons-up": "linear" | "bold";
	"chrome": "linear" | "bold";
	"clapperboard": "linear" | "bold";
	"clapperboard-text": "linear" | "bold";
	"claude-ai": "linear" | "bold";
	"claude-code": "linear" | "bold";
	"clipboard": "linear" | "bold";
	"clipboard-add": "linear" | "bold";
	"clipboard-check": "linear" | "bold";
	"clipboard-remove": "linear" | "bold";
	"clock": "linear" | "bold";
	"close": "linear" | "bold";
	"cloud": "linear" | "bold";
	"cloud-download": "linear" | "bold";
	"cloud-rain": "linear" | "bold";
	"cloud-upload": "linear" | "bold";
	"code": "linear" | "bold";
	"codex": "linear" | "bold";
	"columns": "linear" | "bold";
	"command": "linear" | "bold";
	"computer": "linear" | "bold";
	"connect": "linear" | "bold";
	"copy": "linear" | "bold";
	"corner-down-right": "linear" | "bold";
	"crop": "linear" | "bold";
	"crown": "linear" | "bold";
	"cursor": "linear" | "bold";
	"cursor-click": "linear" | "bold";
	"dashboard": "linear" | "bold";
	"database": "linear" | "bold";
	"deepseek": "linear" | "bold";
	"devin": "linear" | "bold";
	"diamond": "linear" | "bold";
	"discord": "linear" | "bold";
	"dislike": "linear" | "bold";
	"document": "linear" | "bold";
	"dollar": "linear" | "bold";
	"door-open": "linear" | "bold";
	"download": "linear" | "bold";
	"droplet": "linear" | "bold";
	"edit": "linear" | "bold";
	"edit-off": "linear" | "bold";
	"email": "linear" | "bold";
	"eraser": "linear" | "bold";
	"external-link": "linear" | "bold";
	"eye": "linear" | "bold";
	"eye-closed": "linear" | "bold";
	"eye-off": "linear" | "bold";
	"facebook": "linear" | "bold";
	"figma": "linear" | "bold";
	"file": "linear" | "bold";
	"file-add": "linear" | "bold";
	"file-archive": "linear" | "bold";
	"file-code": "linear" | "bold";
	"file-image": "linear" | "bold";
	"file-remove": "linear" | "bold";
	"file-search": "linear" | "bold";
	"file-spreadsheet": "linear" | "bold";
	"file-text": "linear" | "bold";
	"file-video": "linear" | "bold";
	"film": "linear" | "bold";
	"filter": "linear" | "bold";
	"fingerprint": "linear" | "bold";
	"flag": "linear" | "bold";
	"flip-horizontal": "linear" | "bold";
	"folder": "linear" | "bold";
	"folder-add": "linear" | "bold";
	"folder-lock": "linear" | "bold";
	"folder-open": "linear" | "bold";
	"folder-remove": "linear" | "bold";
	"folder-search": "linear" | "bold";
	"folder-tree": "linear" | "bold";
	"folder-with-files": "linear" | "bold";
	"folders": "linear" | "bold";
	"forward": "linear" | "bold";
	"gamepad": "linear" | "bold";
	"gauge": "linear" | "bold";
	"gemini": "linear" | "bold";
	"gift": "linear" | "bold";
	"git": "linear" | "bold";
	"git-branch": "linear" | "bold";
	"git-commit": "linear" | "bold";
	"git-diff": "linear" | "bold";
	"git-fork": "linear" | "bold";
	"git-graph": "linear" | "bold";
	"git-merge": "linear" | "bold";
	"git-pull-request": "linear" | "bold";
	"github": "linear" | "bold";
	"github-copilot": "linear" | "bold";
	"globe": "linear" | "bold";
	"google": "linear" | "bold";
	"graduation-cap": "linear" | "bold";
	"grip-horizontal": "linear" | "bold";
	"grip-vertical": "linear" | "bold";
	"grok": "linear" | "bold";
	"hammer": "linear" | "bold";
	"hand": "linear" | "bold";
	"hand-wave": "linear" | "bold";
	"hashtag": "linear" | "bold";
	"heading": "linear" | "bold";
	"heading-1": "linear" | "bold";
	"heading-2": "linear" | "bold";
	"heading-3": "linear" | "bold";
	"headphones": "linear" | "bold";
	"heart": "linear" | "bold";
	"history": "linear" | "bold";
	"home": "linear" | "bold";
	"home-angle": "linear" | "bold";
	"hourglass": "linear" | "bold";
	"image": "linear" | "bold";
	"image-add": "linear" | "bold";
	"image-edit": "linear" | "bold";
	"images": "linear" | "bold";
	"import": "linear" | "bold";
	"inbox": "linear" | "bold";
	"incoming-call": "linear" | "bold";
	"indent": "linear" | "bold";
	"info-square": "linear" | "bold";
	"instagram": "linear" | "bold";
	"integration": "linear" | "bold";
	"italic": "linear" | "bold";
	"kanban": "linear" | "bold";
	"key": "linear" | "bold";
	"keyboard": "linear" | "bold";
	"kimi": "linear" | "bold";
	"laptop": "linear" | "bold";
	"layers": "linear" | "bold";
	"layout-align-bottom": "linear" | "bold";
	"layout-align-left": "linear" | "bold";
	"layout-align-right": "linear" | "bold";
	"layout-align-top": "linear" | "bold";
	"layout-list": "linear" | "bold";
	"library": "linear" | "bold";
	"life-buoy": "linear" | "bold";
	"lightbulb": "linear" | "bold";
	"lightning": "linear" | "bold";
	"like": "linear" | "bold";
	"link": "linear" | "bold";
	"linkedin": "linear" | "bold";
	"list": "linear" | "bold";
	"list-checks": "linear" | "bold";
	"list-dash": "linear" | "bold";
	"list-down": "linear" | "bold";
	"list-filter": "linear" | "bold";
	"list-ordered": "linear" | "bold";
	"list-up": "linear" | "bold";
	"locate": "linear" | "bold";
	"lock": "linear" | "bold";
	"lock-open": "linear" | "bold";
	"login": "linear" | "bold";
	"logout": "linear" | "bold";
	"magic-wand": "linear" | "bold";
	"map": "linear" | "bold";
	"map-arrow-down": "linear" | "bold";
	"map-arrow-left": "linear" | "bold";
	"map-arrow-right": "linear" | "bold";
	"map-arrow-up": "linear" | "bold";
	"map-folded": "linear" | "bold";
	"map-pin": "linear" | "bold";
	"market-analysis": "linear" | "bold";
	"maximize": "linear" | "bold";
	"megaphone": "linear" | "bold";
	"menu": "linear" | "bold";
	"meta-ai": "linear" | "bold";
	"microphone": "linear" | "bold";
	"microphone-off": "linear" | "bold";
	"microsoft-copilot": "linear" | "bold";
	"minimize": "linear" | "bold";
	"minus": "linear" | "bold";
	"mistral": "linear" | "bold";
	"moon": "linear" | "bold";
	"more-horizontal": "linear" | "bold";
	"more-vertical": "linear" | "bold";
	"mouse": "linear" | "bold";
	"move": "linear" | "bold";
	"music-note": "linear" | "bold";
	"navigation": "linear" | "bold";
	"newspaper": "linear" | "bold";
	"notebook": "linear" | "bold";
	"npm": "linear" | "bold";
	"nvidia": "linear" | "bold";
	"octagon-x": "linear" | "bold";
	"openai": "linear" | "bold";
	"openclaw": "linear" | "bold";
	"opencode": "linear" | "bold";
	"outdent": "linear" | "bold";
	"outgoing-call": "linear" | "bold";
	"package": "linear" | "bold";
	"palette": "linear" | "bold";
	"paper-plane": "linear" | "bold";
	"paperclip": "linear" | "bold";
	"pause": "linear" | "bold";
	"pen": "linear" | "bold";
	"percent": "linear" | "bold";
	"perplexity": "linear" | "bold";
	"phone": "linear" | "bold";
	"phone-off": "linear" | "bold";
	"pin": "linear" | "bold";
	"pin-off": "linear" | "bold";
	"pinterest": "linear" | "bold";
	"pip": "linear" | "bold";
	"pipette": "linear" | "bold";
	"plane": "linear" | "bold";
	"play": "linear" | "bold";
	"play-mini": "linear" | "bold";
	"playlist": "linear" | "bold";
	"podcast": "linear" | "bold";
	"pointer": "linear" | "bold";
	"power": "linear" | "bold";
	"presentation": "linear" | "bold";
	"printer": "linear" | "bold";
	"puzzle": "linear" | "bold";
	"qr-code": "linear" | "bold";
	"question-mark": "linear" | "bold";
	"quote": "linear" | "bold";
	"qwen": "linear" | "bold";
	"react": "linear" | "bold";
	"receipt": "linear" | "bold";
	"reddit": "linear" | "bold";
	"redo": "linear" | "bold";
	"refresh": "linear" | "bold";
	"reorder": "linear" | "bold";
	"repeat": "linear" | "bold";
	"repeat-one": "linear" | "bold";
	"reply": "linear" | "bold";
	"resources-add": "linear" | "bold";
	"rewind": "linear" | "bold";
	"rhombus": "linear" | "bold";
	"rocket": "linear" | "bold";
	"rotate-ccw": "linear" | "bold";
	"rotate-cw": "linear" | "bold";
	"route": "linear" | "bold";
	"router": "linear" | "bold";
	"rows": "linear" | "bold";
	"ruler": "linear" | "bold";
	"sad": "linear" | "bold";
	"save": "linear" | "bold";
	"scan": "linear" | "bold";
	"screen-share": "linear" | "bold";
	"search": "linear" | "bold";
	"send": "linear" | "bold";
	"server": "linear" | "bold";
	"settings": "linear" | "bold";
	"share": "linear" | "bold";
	"shield-add": "linear" | "bold";
	"shuffle": "linear" | "bold";
	"sidebar-bottom": "linear" | "bold";
	"sidebar-left": "linear" | "bold";
	"sidebar-right": "linear" | "bold";
	"sidebar-top": "linear" | "bold";
	"signal": "linear" | "bold";
	"sim-card": "linear" | "bold";
	"skip-back": "linear" | "bold";
	"skip-forward": "linear" | "bold";
	"slack": "linear" | "bold";
	"slash": "linear" | "bold";
	"sliders-horizontal": "linear" | "bold";
	"sliders-horizontal-alt": "linear" | "bold";
	"sliders-vertical": "linear" | "bold";
	"sliders-vertical-alt": "linear" | "bold";
	"smartphone": "linear" | "bold";
	"smile": "linear" | "bold";
	"snapchat": "linear" | "bold";
	"snowflake": "linear" | "bold";
	"sort-ascending": "linear" | "bold";
	"sort-descending": "linear" | "bold";
	"soundwave": "linear" | "bold";
	"sparkles": "linear" | "bold";
	"spinner": "linear" | "bold";
	"spinner-arc": "linear" | "bold";
	"spinner-diagonal": "linear" | "bold";
	"spinner-orbit": "linear" | "bold";
	"spinner-wave": "linear" | "bold";
	"square-pen": "linear" | "bold";
	"star": "linear" | "bold";
	"star-off": "linear" | "bold";
	"sticker": "linear" | "bold";
	"sticky-note": "linear" | "bold";
	"stop": "linear" | "bold";
	"stopwatch": "linear" | "bold";
	"store": "linear" | "bold";
	"strikethrough": "linear" | "bold";
	"suitcase": "linear" | "bold";
	"sun": "linear" | "bold";
	"sun-moon": "linear" | "bold";
	"supabase": "linear" | "bold";
	"superscript": "linear" | "bold";
	"table": "linear" | "bold";
	"tablet": "linear" | "bold";
	"tag": "linear" | "bold";
	"target": "linear" | "bold";
	"telegram": "linear" | "bold";
	"terminal": "linear" | "bold";
	"text-align-center": "linear" | "bold";
	"text-align-justify-left": "linear" | "bold";
	"text-align-justify-right": "linear" | "bold";
	"text-align-left": "linear" | "bold";
	"text-align-right": "linear" | "bold";
	"text-size": "linear" | "bold";
	"text-underline": "linear" | "bold";
	"threads": "linear" | "bold";
	"three-squares": "linear" | "bold";
	"ticket": "linear" | "bold";
	"ticket-discount": "linear" | "bold";
	"tiktok": "linear" | "bold";
	"toggle": "linear" | "bold";
	"transfer-horizontal": "linear" | "bold";
	"transfer-vertical": "linear" | "bold";
	"trash": "linear" | "bold";
	"trending-down": "linear" | "bold";
	"trending-up": "linear" | "bold";
	"trophy": "linear" | "bold";
	"truck": "linear" | "bold";
	"tv": "linear" | "bold";
	"twitter": "linear" | "bold";
	"type": "linear" | "bold";
	"typescript": "linear" | "bold";
	"undo": "linear" | "bold";
	"unfold-less": "linear" | "bold";
	"unfold-more": "linear" | "bold";
	"unlink": "linear" | "bold";
	"upload": "linear" | "bold";
	"usb": "linear" | "bold";
	"user": "linear" | "bold";
	"user-add": "linear" | "bold";
	"user-check": "linear" | "bold";
	"user-group": "linear" | "bold";
	"user-lock": "linear" | "bold";
	"user-remove": "linear" | "bold";
	"user-settings": "linear" | "bold";
	"user-x": "linear" | "bold";
	"variable": "linear" | "bold";
	"vercel": "linear" | "bold";
	"verified-check": "linear" | "bold";
	"video-camera": "linear" | "bold";
	"video-frame": "linear" | "bold";
	"video-off": "linear" | "bold";
	"volume-high": "linear" | "bold";
	"volume-low": "linear" | "bold";
	"volume-off": "linear" | "bold";
	"wallet": "linear" | "bold";
	"waves": "linear" | "bold";
	"webcam": "linear" | "bold";
	"webhook": "linear" | "bold";
	"widget": "linear" | "bold";
	"widget-add": "linear" | "bold";
	"widget-square": "linear" | "bold";
	"widget-square-add": "linear" | "bold";
	"wifi": "linear" | "bold";
	"wifi-off": "linear" | "bold";
	"wind": "linear" | "bold";
	"windsurf": "linear" | "bold";
	"x": "linear" | "bold";
	"xai": "linear" | "bold";
	"youtube": "linear" | "bold";
	"zai": "linear" | "bold";
	"zoom-in": "linear" | "bold";
	"zoom-out": "linear" | "bold";
};
